import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
const sidebars: SidebarsConfig = {
  bible: [{ type: "autogenerated", dirName: "bible" }],
  study: [{ type: "autogenerated", dirName: "study" }],
  classes: [{ type: "autogenerated", dirName: "classes" }],
  encyclopedia: [{ type: "autogenerated", dirName: "encyclopedia" }],
  law: [{ type: "autogenerated", dirName: "law" }],
  precepts: [{ type: "autogenerated", dirName: "precepts" }],
  cases: [{ type: "autogenerated", dirName: "cases" }],
  concordance: [{ type: "autogenerated", dirName: "concordance" }],
};
export default sidebars;
