/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApiRouteImport } from './routes/api'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BibleIndexRouteImport } from './routes/bible/index'
import { Route as CaptainsIndexRouteImport } from './routes/captains/index'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as ClassesIndexRouteImport } from './routes/classes/index'
import { Route as ConcordanceIndexRouteImport } from './routes/concordance/index'
import { Route as ConcordanceBookRouteImport } from './routes/concordance/$book'
import { Route as EncyclopediaIndexRouteImport } from './routes/encyclopedia/index'
import { Route as EncyclopediaSlugRouteImport } from './routes/encyclopedia/$slug'
import { Route as LawIndexRouteImport } from './routes/law/index'
import { Route as PreceptsIndexRouteImport } from './routes/precepts/index'
import { Route as PreceptsSlugRouteImport } from './routes/precepts/$slug'
import { Route as StudyIndexRouteImport } from './routes/study/index'
import { Route as TopicsIndexRouteImport } from './routes/topics/index'
import { Route as TopicsSlugRouteImport } from './routes/topics/$slug'
import { Route as BibleBookIndexRouteImport } from './routes/bible/$book/index'
import { Route as BibleBookChapterRouteImport } from './routes/bible/$book/$chapter'
import { Route as CaptainsYearSlugRouteImport } from './routes/captains/$year/$slug'
import { Route as CasesEraSlugRouteImport } from './routes/cases/$era/$slug'
import { Route as ClassesYearSlugRouteImport } from './routes/classes/$year/$slug'
import { Route as LawPartIndexRouteImport } from './routes/law/$part/index'
import { Route as LawPartSectionRouteImport } from './routes/law/$part/$section'
import { Route as StudyBookIndexRouteImport } from './routes/study/$book/index'
import { Route as StudyBookChapterRouteImport } from './routes/study/$book/$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleIndexRoute = BibleIndexRouteImport.update({
  id: '/bible/',
  path: '/bible/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainsIndexRoute = CaptainsIndexRouteImport.update({
  id: '/captains/',
  path: '/captains/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcordanceIndexRoute = ConcordanceIndexRouteImport.update({
  id: '/concordance/',
  path: '/concordance/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcordanceBookRoute = ConcordanceBookRouteImport.update({
  id: '/concordance/$book',
  path: '/concordance/$book',
  getParentRoute: () => rootRouteImport,
} as any)
const EncyclopediaIndexRoute = EncyclopediaIndexRouteImport.update({
  id: '/encyclopedia/',
  path: '/encyclopedia/',
  getParentRoute: () => rootRouteImport,
} as any)
const EncyclopediaSlugRoute = EncyclopediaSlugRouteImport.update({
  id: '/encyclopedia/$slug',
  path: '/encyclopedia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LawIndexRoute = LawIndexRouteImport.update({
  id: '/law/',
  path: '/law/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreceptsIndexRoute = PreceptsIndexRouteImport.update({
  id: '/precepts/',
  path: '/precepts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreceptsSlugRoute = PreceptsSlugRouteImport.update({
  id: '/precepts/$slug',
  path: '/precepts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleBookIndexRoute = BibleBookIndexRouteImport.update({
  id: '/bible/$book/',
  path: '/bible/$book/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleBookChapterRoute = BibleBookChapterRouteImport.update({
  id: '/bible/$book/$chapter',
  path: '/bible/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainsYearSlugRoute = CaptainsYearSlugRouteImport.update({
  id: '/captains/$year/$slug',
  path: '/captains/$year/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesEraSlugRoute = CasesEraSlugRouteImport.update({
  id: '/cases/$era/$slug',
  path: '/cases/$era/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesYearSlugRoute = ClassesYearSlugRouteImport.update({
  id: '/classes/$year/$slug',
  path: '/classes/$year/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LawPartIndexRoute = LawPartIndexRouteImport.update({
  id: '/law/$part/',
  path: '/law/$part/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawPartSectionRoute = LawPartSectionRouteImport.update({
  id: '/law/$part/$section',
  path: '/law/$part/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyBookIndexRoute = StudyBookIndexRouteImport.update({
  id: '/study/$book/',
  path: '/study/$book/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyBookChapterRoute = StudyBookChapterRouteImport.update({
  id: '/study/$book/$chapter',
  path: '/study/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api': typeof ApiRoute
  '/downloads': typeof DownloadsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/concordance/$book': typeof ConcordanceBookRoute
  '/encyclopedia/$slug': typeof EncyclopediaSlugRoute
  '/precepts/$slug': typeof PreceptsSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/bible/': typeof BibleIndexRoute
  '/captains/': typeof CaptainsIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/concordance/': typeof ConcordanceIndexRoute
  '/encyclopedia/': typeof EncyclopediaIndexRoute
  '/law/': typeof LawIndexRoute
  '/precepts/': typeof PreceptsIndexRoute
  '/study/': typeof StudyIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/bible/$book/$chapter': typeof BibleBookChapterRoute
  '/captains/$year/$slug': typeof CaptainsYearSlugRoute
  '/cases/$era/$slug': typeof CasesEraSlugRoute
  '/classes/$year/$slug': typeof ClassesYearSlugRoute
  '/law/$part/$section': typeof LawPartSectionRoute
  '/study/$book/$chapter': typeof StudyBookChapterRoute
  '/bible/$book/': typeof BibleBookIndexRoute
  '/law/$part/': typeof LawPartIndexRoute
  '/study/$book/': typeof StudyBookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api': typeof ApiRoute
  '/downloads': typeof DownloadsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/concordance/$book': typeof ConcordanceBookRoute
  '/encyclopedia/$slug': typeof EncyclopediaSlugRoute
  '/precepts/$slug': typeof PreceptsSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/bible': typeof BibleIndexRoute
  '/captains': typeof CaptainsIndexRoute
  '/cases': typeof CasesIndexRoute
  '/classes': typeof ClassesIndexRoute
  '/concordance': typeof ConcordanceIndexRoute
  '/encyclopedia': typeof EncyclopediaIndexRoute
  '/law': typeof LawIndexRoute
  '/precepts': typeof PreceptsIndexRoute
  '/study': typeof StudyIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/bible/$book/$chapter': typeof BibleBookChapterRoute
  '/captains/$year/$slug': typeof CaptainsYearSlugRoute
  '/cases/$era/$slug': typeof CasesEraSlugRoute
  '/classes/$year/$slug': typeof ClassesYearSlugRoute
  '/law/$part/$section': typeof LawPartSectionRoute
  '/study/$book/$chapter': typeof StudyBookChapterRoute
  '/bible/$book': typeof BibleBookIndexRoute
  '/law/$part': typeof LawPartIndexRoute
  '/study/$book': typeof StudyBookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api': typeof ApiRoute
  '/downloads': typeof DownloadsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/concordance/$book': typeof ConcordanceBookRoute
  '/encyclopedia/$slug': typeof EncyclopediaSlugRoute
  '/precepts/$slug': typeof PreceptsSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/bible/': typeof BibleIndexRoute
  '/captains/': typeof CaptainsIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/concordance/': typeof ConcordanceIndexRoute
  '/encyclopedia/': typeof EncyclopediaIndexRoute
  '/law/': typeof LawIndexRoute
  '/precepts/': typeof PreceptsIndexRoute
  '/study/': typeof StudyIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/bible/$book/$chapter': typeof BibleBookChapterRoute
  '/captains/$year/$slug': typeof CaptainsYearSlugRoute
  '/cases/$era/$slug': typeof CasesEraSlugRoute
  '/classes/$year/$slug': typeof ClassesYearSlugRoute
  '/law/$part/$section': typeof LawPartSectionRoute
  '/study/$book/$chapter': typeof StudyBookChapterRoute
  '/bible/$book/': typeof BibleBookIndexRoute
  '/law/$part/': typeof LawPartIndexRoute
  '/study/$book/': typeof StudyBookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api'
    | '/downloads'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/concordance/$book'
    | '/encyclopedia/$slug'
    | '/precepts/$slug'
    | '/topics/$slug'
    | '/bible/'
    | '/captains/'
    | '/cases/'
    | '/classes/'
    | '/concordance/'
    | '/encyclopedia/'
    | '/law/'
    | '/precepts/'
    | '/study/'
    | '/topics/'
    | '/bible/$book/$chapter'
    | '/captains/$year/$slug'
    | '/cases/$era/$slug'
    | '/classes/$year/$slug'
    | '/law/$part/$section'
    | '/study/$book/$chapter'
    | '/bible/$book/'
    | '/law/$part/'
    | '/study/$book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api'
    | '/downloads'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/concordance/$book'
    | '/encyclopedia/$slug'
    | '/precepts/$slug'
    | '/topics/$slug'
    | '/bible'
    | '/captains'
    | '/cases'
    | '/classes'
    | '/concordance'
    | '/encyclopedia'
    | '/law'
    | '/precepts'
    | '/study'
    | '/topics'
    | '/bible/$book/$chapter'
    | '/captains/$year/$slug'
    | '/cases/$era/$slug'
    | '/classes/$year/$slug'
    | '/law/$part/$section'
    | '/study/$book/$chapter'
    | '/bible/$book'
    | '/law/$part'
    | '/study/$book'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api'
    | '/downloads'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/concordance/$book'
    | '/encyclopedia/$slug'
    | '/precepts/$slug'
    | '/topics/$slug'
    | '/bible/'
    | '/captains/'
    | '/cases/'
    | '/classes/'
    | '/concordance/'
    | '/encyclopedia/'
    | '/law/'
    | '/precepts/'
    | '/study/'
    | '/topics/'
    | '/bible/$book/$chapter'
    | '/captains/$year/$slug'
    | '/cases/$era/$slug'
    | '/classes/$year/$slug'
    | '/law/$part/$section'
    | '/study/$book/$chapter'
    | '/bible/$book/'
    | '/law/$part/'
    | '/study/$book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiRoute: typeof ApiRoute
  DownloadsRoute: typeof DownloadsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ConcordanceBookRoute: typeof ConcordanceBookRoute
  EncyclopediaSlugRoute: typeof EncyclopediaSlugRoute
  PreceptsSlugRoute: typeof PreceptsSlugRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
  BibleIndexRoute: typeof BibleIndexRoute
  CaptainsIndexRoute: typeof CaptainsIndexRoute
  CasesIndexRoute: typeof CasesIndexRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  ConcordanceIndexRoute: typeof ConcordanceIndexRoute
  EncyclopediaIndexRoute: typeof EncyclopediaIndexRoute
  LawIndexRoute: typeof LawIndexRoute
  PreceptsIndexRoute: typeof PreceptsIndexRoute
  StudyIndexRoute: typeof StudyIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  BibleBookChapterRoute: typeof BibleBookChapterRoute
  CaptainsYearSlugRoute: typeof CaptainsYearSlugRoute
  CasesEraSlugRoute: typeof CasesEraSlugRoute
  ClassesYearSlugRoute: typeof ClassesYearSlugRoute
  LawPartSectionRoute: typeof LawPartSectionRoute
  StudyBookChapterRoute: typeof StudyBookChapterRoute
  BibleBookIndexRoute: typeof BibleBookIndexRoute
  LawPartIndexRoute: typeof LawPartIndexRoute
  StudyBookIndexRoute: typeof StudyBookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/': {
      id: '/bible/'
      path: '/bible'
      fullPath: '/bible/'
      preLoaderRoute: typeof BibleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captains/': {
      id: '/captains/'
      path: '/captains'
      fullPath: '/captains/'
      preLoaderRoute: typeof CaptainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concordance/': {
      id: '/concordance/'
      path: '/concordance'
      fullPath: '/concordance/'
      preLoaderRoute: typeof ConcordanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concordance/$book': {
      id: '/concordance/$book'
      path: '/concordance/$book'
      fullPath: '/concordance/$book'
      preLoaderRoute: typeof ConcordanceBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encyclopedia/': {
      id: '/encyclopedia/'
      path: '/encyclopedia'
      fullPath: '/encyclopedia/'
      preLoaderRoute: typeof EncyclopediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encyclopedia/$slug': {
      id: '/encyclopedia/$slug'
      path: '/encyclopedia/$slug'
      fullPath: '/encyclopedia/$slug'
      preLoaderRoute: typeof EncyclopediaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/law/': {
      id: '/law/'
      path: '/law'
      fullPath: '/law/'
      preLoaderRoute: typeof LawIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precepts/': {
      id: '/precepts/'
      path: '/precepts'
      fullPath: '/precepts/'
      preLoaderRoute: typeof PreceptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precepts/$slug': {
      id: '/precepts/$slug'
      path: '/precepts/$slug'
      fullPath: '/precepts/$slug'
      preLoaderRoute: typeof PreceptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/$book/': {
      id: '/bible/$book/'
      path: '/bible/$book'
      fullPath: '/bible/$book/'
      preLoaderRoute: typeof BibleBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/$book/$chapter': {
      id: '/bible/$book/$chapter'
      path: '/bible/$book/$chapter'
      fullPath: '/bible/$book/$chapter'
      preLoaderRoute: typeof BibleBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captains/$year/$slug': {
      id: '/captains/$year/$slug'
      path: '/captains/$year/$slug'
      fullPath: '/captains/$year/$slug'
      preLoaderRoute: typeof CaptainsYearSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$era/$slug': {
      id: '/cases/$era/$slug'
      path: '/cases/$era/$slug'
      fullPath: '/cases/$era/$slug'
      preLoaderRoute: typeof CasesEraSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$year/$slug': {
      id: '/classes/$year/$slug'
      path: '/classes/$year/$slug'
      fullPath: '/classes/$year/$slug'
      preLoaderRoute: typeof ClassesYearSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/law/$part/': {
      id: '/law/$part/'
      path: '/law/$part'
      fullPath: '/law/$part/'
      preLoaderRoute: typeof LawPartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/law/$part/$section': {
      id: '/law/$part/$section'
      path: '/law/$part/$section'
      fullPath: '/law/$part/$section'
      preLoaderRoute: typeof LawPartSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$book/': {
      id: '/study/$book/'
      path: '/study/$book'
      fullPath: '/study/$book/'
      preLoaderRoute: typeof StudyBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$book/$chapter': {
      id: '/study/$book/$chapter'
      path: '/study/$book/$chapter'
      fullPath: '/study/$book/$chapter'
      preLoaderRoute: typeof StudyBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiRoute: ApiRoute,
  DownloadsRoute: DownloadsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ConcordanceBookRoute: ConcordanceBookRoute,
  EncyclopediaSlugRoute: EncyclopediaSlugRoute,
  PreceptsSlugRoute: PreceptsSlugRoute,
  TopicsSlugRoute: TopicsSlugRoute,
  BibleIndexRoute: BibleIndexRoute,
  CaptainsIndexRoute: CaptainsIndexRoute,
  CasesIndexRoute: CasesIndexRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  ConcordanceIndexRoute: ConcordanceIndexRoute,
  EncyclopediaIndexRoute: EncyclopediaIndexRoute,
  LawIndexRoute: LawIndexRoute,
  PreceptsIndexRoute: PreceptsIndexRoute,
  StudyIndexRoute: StudyIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  BibleBookChapterRoute: BibleBookChapterRoute,
  CaptainsYearSlugRoute: CaptainsYearSlugRoute,
  CasesEraSlugRoute: CasesEraSlugRoute,
  ClassesYearSlugRoute: ClassesYearSlugRoute,
  LawPartSectionRoute: LawPartSectionRoute,
  StudyBookChapterRoute: StudyBookChapterRoute,
  BibleBookIndexRoute: BibleBookIndexRoute,
  LawPartIndexRoute: LawPartIndexRoute,
  StudyBookIndexRoute: StudyBookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
