/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BibleIndexRouteImport } from './routes/bible/index'
import { Route as CaptainsIndexRouteImport } from './routes/captains/index'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as ClassesIndexRouteImport } from './routes/classes/index'
import { Route as StudyIndexRouteImport } from './routes/study/index'
import { Route as BibleBookIndexRouteImport } from './routes/bible/$book/index'
import { Route as BibleBookChapterRouteImport } from './routes/bible/$book/$chapter'
import { Route as CaptainsYearSlugRouteImport } from './routes/captains/$year/$slug'
import { Route as CasesEraSlugRouteImport } from './routes/cases/$era/$slug'
import { Route as ClassesYearSlugRouteImport } from './routes/classes/$year/$slug'
import { Route as StudyBookChapterRouteImport } from './routes/study/$book/$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleIndexRoute = BibleIndexRouteImport.update({
  id: '/bible/',
  path: '/bible/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainsIndexRoute = CaptainsIndexRouteImport.update({
  id: '/captains/',
  path: '/captains/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleBookIndexRoute = BibleBookIndexRouteImport.update({
  id: '/bible/$book/',
  path: '/bible/$book/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleBookChapterRoute = BibleBookChapterRouteImport.update({
  id: '/bible/$book/$chapter',
  path: '/bible/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainsYearSlugRoute = CaptainsYearSlugRouteImport.update({
  id: '/captains/$year/$slug',
  path: '/captains/$year/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesEraSlugRoute = CasesEraSlugRouteImport.update({
  id: '/cases/$era/$slug',
  path: '/cases/$era/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesYearSlugRoute = ClassesYearSlugRouteImport.update({
  id: '/classes/$year/$slug',
  path: '/classes/$year/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyBookChapterRoute = StudyBookChapterRouteImport.update({
  id: '/study/$book/$chapter',
  path: '/study/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bible/': typeof BibleIndexRoute
  '/captains/': typeof CaptainsIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/study/': typeof StudyIndexRoute
  '/bible/$book/$chapter': typeof BibleBookChapterRoute
  '/captains/$year/$slug': typeof CaptainsYearSlugRoute
  '/cases/$era/$slug': typeof CasesEraSlugRoute
  '/classes/$year/$slug': typeof ClassesYearSlugRoute
  '/study/$book/$chapter': typeof StudyBookChapterRoute
  '/bible/$book/': typeof BibleBookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bible': typeof BibleIndexRoute
  '/captains': typeof CaptainsIndexRoute
  '/cases': typeof CasesIndexRoute
  '/classes': typeof ClassesIndexRoute
  '/study': typeof StudyIndexRoute
  '/bible/$book/$chapter': typeof BibleBookChapterRoute
  '/captains/$year/$slug': typeof CaptainsYearSlugRoute
  '/cases/$era/$slug': typeof CasesEraSlugRoute
  '/classes/$year/$slug': typeof ClassesYearSlugRoute
  '/study/$book/$chapter': typeof StudyBookChapterRoute
  '/bible/$book': typeof BibleBookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bible/': typeof BibleIndexRoute
  '/captains/': typeof CaptainsIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/study/': typeof StudyIndexRoute
  '/bible/$book/$chapter': typeof BibleBookChapterRoute
  '/captains/$year/$slug': typeof CaptainsYearSlugRoute
  '/cases/$era/$slug': typeof CasesEraSlugRoute
  '/classes/$year/$slug': typeof ClassesYearSlugRoute
  '/study/$book/$chapter': typeof StudyBookChapterRoute
  '/bible/$book/': typeof BibleBookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/bible/'
    | '/captains/'
    | '/cases/'
    | '/classes/'
    | '/study/'
    | '/bible/$book/$chapter'
    | '/captains/$year/$slug'
    | '/cases/$era/$slug'
    | '/classes/$year/$slug'
    | '/study/$book/$chapter'
    | '/bible/$book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/bible'
    | '/captains'
    | '/cases'
    | '/classes'
    | '/study'
    | '/bible/$book/$chapter'
    | '/captains/$year/$slug'
    | '/cases/$era/$slug'
    | '/classes/$year/$slug'
    | '/study/$book/$chapter'
    | '/bible/$book'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/bible/'
    | '/captains/'
    | '/cases/'
    | '/classes/'
    | '/study/'
    | '/bible/$book/$chapter'
    | '/captains/$year/$slug'
    | '/cases/$era/$slug'
    | '/classes/$year/$slug'
    | '/study/$book/$chapter'
    | '/bible/$book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BibleIndexRoute: typeof BibleIndexRoute
  CaptainsIndexRoute: typeof CaptainsIndexRoute
  CasesIndexRoute: typeof CasesIndexRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  StudyIndexRoute: typeof StudyIndexRoute
  BibleBookChapterRoute: typeof BibleBookChapterRoute
  CaptainsYearSlugRoute: typeof CaptainsYearSlugRoute
  CasesEraSlugRoute: typeof CasesEraSlugRoute
  ClassesYearSlugRoute: typeof ClassesYearSlugRoute
  StudyBookChapterRoute: typeof StudyBookChapterRoute
  BibleBookIndexRoute: typeof BibleBookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/': {
      id: '/bible/'
      path: '/bible'
      fullPath: '/bible/'
      preLoaderRoute: typeof BibleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captains/': {
      id: '/captains/'
      path: '/captains'
      fullPath: '/captains/'
      preLoaderRoute: typeof CaptainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/$book/': {
      id: '/bible/$book/'
      path: '/bible/$book'
      fullPath: '/bible/$book/'
      preLoaderRoute: typeof BibleBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/$book/$chapter': {
      id: '/bible/$book/$chapter'
      path: '/bible/$book/$chapter'
      fullPath: '/bible/$book/$chapter'
      preLoaderRoute: typeof BibleBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captains/$year/$slug': {
      id: '/captains/$year/$slug'
      path: '/captains/$year/$slug'
      fullPath: '/captains/$year/$slug'
      preLoaderRoute: typeof CaptainsYearSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$era/$slug': {
      id: '/cases/$era/$slug'
      path: '/cases/$era/$slug'
      fullPath: '/cases/$era/$slug'
      preLoaderRoute: typeof CasesEraSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$year/$slug': {
      id: '/classes/$year/$slug'
      path: '/classes/$year/$slug'
      fullPath: '/classes/$year/$slug'
      preLoaderRoute: typeof ClassesYearSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$book/$chapter': {
      id: '/study/$book/$chapter'
      path: '/study/$book/$chapter'
      fullPath: '/study/$book/$chapter'
      preLoaderRoute: typeof StudyBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BibleIndexRoute: BibleIndexRoute,
  CaptainsIndexRoute: CaptainsIndexRoute,
  CasesIndexRoute: CasesIndexRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  StudyIndexRoute: StudyIndexRoute,
  BibleBookChapterRoute: BibleBookChapterRoute,
  CaptainsYearSlugRoute: CaptainsYearSlugRoute,
  CasesEraSlugRoute: CasesEraSlugRoute,
  ClassesYearSlugRoute: ClassesYearSlugRoute,
  StudyBookChapterRoute: StudyBookChapterRoute,
  BibleBookIndexRoute: BibleBookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
