"""Seed data for the original 21 case studies. Used only by build_vault.py to write the first
version of a case note into the vault; after that the vault note is the source of truth.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from cases_lib import R

CORE = [
 {
  "slug": "adam-and-eve",
  "name": "Adam and Eve",
  "era": "Primeval",
  "charge": "Eating from the tree God forbade",
  "verdict": "curse",
  "summary": "Given one prohibition in the garden, they ate from the tree of the knowledge of good and evil after the serpent's persuasion. The first transgression, and the pattern for every one after it: a plain command, a rationalization, a broken boundary.",
  "offense": "The Lord permitted every tree but one. The woman, deceived, took the fruit and gave it to the man, who ate knowingly. Both then hid, and both shifted blame, to the serpent, to each other, to God for the gift of the other.",
  "judgment": "No death that day, but a sentence on all that followed: pain in childbearing, toil against a cursed ground, and expulsion from the garden lest they eat of the tree of life. Death entered as the long consequence.",
  "refs": R("Genesis 2:16-17", "Genesis 3:1-7", "Genesis 3:11-13", "Genesis 3:16-19", "Genesis 3:22-24", "Romans 5:12"),
  "laws": ["2C", "2D"],
  "topics": ["obedience", "temptation", "good-and-evil", "tree-of-life"],
  "themes": ["disobedience", "the-fall"],
 },
 {
  "slug": "cain",
  "name": "Cain",
  "era": "Primeval",
  "charge": "Murder of his brother Abel",
  "verdict": "curse",
  "summary": "The first murder. Angry that his brother's offering was accepted and his own was not, Cain rose up in the field and killed Abel, then denied knowledge of it to God's face.",
  "offense": "Warned directly that sin crouched at his door and that he must master it, Cain instead led his brother out and struck him down. Asked where Abel was, he answered with a lie and a taunt: am I my brother's keeper?",
  "judgment": "Not death but a heavier exile: the ground would no longer yield to him, and he became a fugitive and a wanderer. God set a mark on him so that no one would kill him, extending the very mercy Cain had denied.",
  "refs": R("Genesis 4:3-8", "Genesis 4:9-12", "Genesis 4:15", "1 John 3:12"),
  "laws": ["1A.6", "2F"],
  "topics": ["murder", "anger", "envy"],
  "themes": ["murder", "bloodshed"],
 },
 {
  "slug": "the-flood-generation",
  "name": "The generation of the Flood",
  "era": "Primeval",
  "charge": "Corruption and violence filling the earth",
  "verdict": "death",
  "summary": "A whole world under judgment. The earth was filled with violence and every imagination of the heart was continually evil, so God resolved to blot out what he had made, sparing only Noah's household.",
  "offense": "Not one offense but a saturation: corruption of all flesh, violence without restraint, wickedness so total that it grieved God that he had made man.",
  "judgment": "The Flood. Every living thing on the dry land perished; eight souls were carried through in the ark. The waters were both execution and cleansing.",
  "refs": R("Genesis 6:5-7", "Genesis 6:11-13", "Genesis 7:21-23", "2 Peter 2:5", "Matthew 24:37-39"),
  "laws": ["2F", "4A"],
  "topics": ["the-wicked", "judgement", "doctrine-flood", "giants"],
  "themes": ["violence", "corporate-judgment"],
 },
 {
  "slug": "sodom-and-gomorrah",
  "name": "Sodom and Gomorrah",
  "era": "Patriarchal",
  "charge": "Grievous sin; inhospitality and violence against strangers",
  "verdict": "death",
  "summary": "Cities whose sin was grave enough that its cry reached heaven. When two visitors lodged with Lot, the men of the city surrounded the house demanding them. Judgment fell the next morning.",
  "offense": "The prophets later name the fuller charge: pride, fullness of bread, careless ease, and no help for the poor and needy, a hardness that showed itself in the mob at Lot's door.",
  "judgment": "Fire and brimstone from the Lord out of heaven, overthrowing the cities and the plain. Lot's wife, looking back, became a pillar of salt. Held up ever after as the type of sudden ruin.",
  "refs": R("Genesis 18:20-21", "Genesis 19:4-5", "Genesis 19:24-26", "Ezekiel 16:49-50", "Jude 1:7"),
  "laws": ["11B", "15B", "10J"],
  "topics": ["strangers", "pride", "sodomy", "judgement-of-nations"],
  "themes": ["violence", "corporate-judgment"],
 },
 {
  "slug": "the-golden-calf",
  "name": "Aaron and Israel at the golden calf",
  "era": "Wilderness",
  "charge": "Idolatry within weeks of the covenant",
  "verdict": "plague",
  "summary": "While Moses was on the mountain receiving the law that forbade it, the people made a golden calf and worshipped it. The covenant was broken almost before the ink was dry.",
  "offense": "Impatient at Moses' delay, they pressed Aaron, who gathered their gold and cast a calf; they declared it the god that brought them out of Egypt and rose up to play. Aaron built it an altar and proclaimed a feast.",
  "judgment": "Moses ground the calf to powder and made them drink it. The Levites, called to the Lord's side, put about three thousand to the sword, and the Lord sent a plague on the people. Aaron was spared but not excused.",
  "refs": R("Exodus 32:1-6", "Exodus 32:19-20", "Exodus 32:26-28", "Exodus 32:35", "Deuteronomy 9:16-21"),
  "laws": ["1A.1", "1A.2", "2D.3", "2D.12"],
  "topics": ["idolatry", "abomination", "graven-images", "egypt"],
  "themes": ["idolatry"],
 },
 {
  "slug": "nadab-and-abihu",
  "name": "Nadab and Abihu",
  "era": "Wilderness",
  "charge": "Offering strange fire not commanded",
  "verdict": "death",
  "summary": "Two priests, sons of Aaron, offered fire before the Lord that he had not commanded. Fire came out from the Lord and consumed them on the spot.",
  "offense": "They took their censers, put fire and incense in them, and offered 'strange fire before the Lord, which he commanded them not.' Presumption in the very act of worship, from those who of all people knew the ordinances.",
  "judgment": "Fire from before the Lord devoured them, and they died. Aaron was forbidden even to mourn. A warning that nearness to holy things raises the standard rather than lowering it.",
  "refs": R("Leviticus 10:1-3", "Leviticus 16:1", "Numbers 3:4", "Numbers 26:61"),
  "laws": ["20A", "20B", "9A"],
  "topics": ["false-worship", "kings-and-priests", "obedience", "holiness"],
  "themes": ["irreverence", "priesthood"],
 },
 {
  "slug": "the-sabbath-breaker",
  "name": "The man gathering sticks on the Sabbath",
  "era": "Wilderness",
  "charge": "Working on the Sabbath",
  "verdict": "death",
  "summary": "A man was found gathering sticks on the Sabbath day. Because the penalty had not yet been specified, he was held while the Lord's judgment was sought.",
  "offense": "The command to keep the Sabbath was already given; his act of gathering fuel was plain work on the day of rest, done openly and witnessed.",
  "judgment": "The Lord commanded that he be put to death; the congregation stoned him outside the camp. A hard case, preserved precisely because the sentence was not obvious and had to be asked.",
  "refs": R("Numbers 15:32-36", "Exodus 31:14-15", "Exodus 35:2"),
  "laws": ["1A.4", "9C", "10B"],
  "topics": ["sabbath", "seventh-day"],
  "themes": ["sabbath"],
 },
 {
  "slug": "korah",
  "name": "Korah, Dathan, and Abiram",
  "era": "Wilderness",
  "charge": "Rebellion against God-appointed authority",
  "verdict": "death",
  "summary": "Korah led 250 leaders in a challenge to Moses and Aaron, claiming the whole congregation was holy and needed no mediator. The earth answered the claim.",
  "offense": "They gathered against Moses, charging him with lifting himself above the assembly. It was not merely a personnel dispute but a rejection of the order God had set, framed in the language of equality.",
  "judgment": "The ground opened and swallowed Korah's company with their households, and fire consumed the 250 who offered incense. When the people murmured the next day, a plague killed 14,700 more until Aaron's incense stayed it.",
  "refs": R("Numbers 16:1-3", "Numbers 16:31-35", "Numbers 16:49", "Jude 1:11"),
  "laws": ["8A", "19A", "20A"],
  "topics": ["rebellious", "ranking-system", "murmuring", "not-equality"],
  "themes": ["rebellion", "priesthood"],
 },
 {
  "slug": "moses-at-meribah",
  "name": "Moses at the waters of Meribah",
  "era": "Wilderness",
  "charge": "Failing to honor God as holy before the people",
  "verdict": "reprieve",
  "summary": "Told to speak to the rock so it would give water, Moses instead struck it twice and spoke rashly to the people. The water came, but so did a sentence: he would not enter the promised land.",
  "offense": "God said speak to the rock; Moses struck it and said, 'must we fetch you water?', taking to himself and Aaron what belonged to God, and disobeying the specific instruction in anger.",
  "judgment": "No death, but the leader who had carried the nation forty years was barred from the land for it. A case that measures how much is required of those entrusted with much.",
  "refs": R("Numbers 20:7-12", "Deuteronomy 32:48-52", "Psalms 106:32-33"),
  "laws": ["2K", "8A"],
  "topics": ["anger", "obedience", "sanctify"],
  "themes": ["irreverence", "leadership"],
 },
 {
  "slug": "achan",
  "name": "Achan",
  "era": "Conquest",
  "charge": "Taking devoted spoil from Jericho",
  "verdict": "death",
  "summary": "Jericho's spoil was placed under the ban, devoted wholly to God. Achan took a garment, silver, and a wedge of gold and hid them in his tent. Israel's next battle failed because of it.",
  "offense": "He 'saw, coveted, and took,' then buried the goods under his tent. One man's hidden theft brought defeat at Ai and the death of thirty-six soldiers before the cause was found by lot.",
  "judgment": "Achan and his household, with the stolen goods, were stoned and burned in the valley of Achor. The accursed thing, once purged, restored Israel's standing.",
  "refs": R("Joshua 7:1", "Joshua 7:11", "Joshua 7:20-21", "Joshua 7:24-26"),
  "laws": ["1A.8", "1A.10", "22A.11"],
  "topics": ["stealing", "covet", "cover-up-sin", "exposed"],
  "themes": ["theft", "covetousness"],
 },
 {
  "slug": "the-blasphemer",
  "name": "The blasphemer in the camp",
  "era": "Wilderness",
  "charge": "Blaspheming the Name in a quarrel",
  "verdict": "death",
  "summary": "In a fight within the camp, a man blasphemed the Name and cursed. He was held until the Lord's mind was made known, and his case set the statute for all Israel.",
  "offense": "The son of an Israelite woman and an Egyptian man blasphemed the Name in the course of a brawl. The offense was against God directly, spoken and heard by witnesses.",
  "judgment": "The Lord commanded that the whole congregation stone him outside the camp, the witnesses laying their hands on his head. From his case came the law: whoever blasphemes the Name shall be put to death.",
  "refs": R("Leviticus 24:10-16", "Leviticus 24:23", "Exodus 20:7"),
  "laws": ["1A.3", "2K.2", "2K.3"],
  "topics": ["the-name", "mixed-multitudes"],
  "themes": ["blasphemy"],
 },
 {
  "slug": "aaron-and-miriam",
  "name": "Aaron and Miriam",
  "era": "Wilderness",
  "charge": "Speaking against Moses; challenging his authority",
  "verdict": "temporal",
  "summary": "Miriam and Aaron spoke against Moses, using his marriage as a pretext to ask whether the Lord had not also spoken through them. God summoned all three and answered plainly.",
  "offense": "Envy of Moses' unique standing, aired as a grievance. God declared that with Moses he spoke mouth to mouth, not in visions, and asked why they were not afraid to speak against him.",
  "judgment": "Miriam became leprous, white as snow; struck, it seems, as the instigator. Moses interceded, and after seven days shut out of the camp she was healed. A measured discipline, not death.",
  "refs": R("Numbers 12:1-2", "Numbers 12:6-10", "Numbers 12:13-15", "Deuteronomy 24:9"),
  "laws": ["8A", "17K", "19A"],
  "topics": ["envy", "ranking-system", "talebearer", "family-order"],
  "themes": ["rebellion", "leadership"],
 },
 {
  "slug": "eli-and-sons",
  "name": "Eli and his sons",
  "era": "Judges",
  "charge": "Corrupt priesthood; a father who would not restrain it",
  "verdict": "death",
  "summary": "Eli's sons Hophni and Phinehas treated the Lord's offering with contempt and lay with the women at the tabernacle door. Eli rebuked them weakly but did not remove them. The house fell together.",
  "offense": "The sons seized the sacrifices by force and defiled worship; the father honored his sons above God by tolerating it. A failure of office compounded by a failure of discipline.",
  "judgment": "Both sons died on the same day in battle; the ark was captured; Eli fell and broke his neck at the news. The priesthood was stripped from his line as foretold.",
  "refs": R("1 Samuel 2:12-17", "1 Samuel 2:22-25", "1 Samuel 2:29-34", "1 Samuel 4:11", "1 Samuel 4:18"),
  "laws": ["8A", "20A", "20B", "3A"],
  "topics": ["kings-and-priests", "correction", "honour", "training-children"],
  "themes": ["priesthood", "negligence"],
 },
 {
  "slug": "saul",
  "name": "King Saul",
  "era": "Monarchy",
  "charge": "Unlawful sacrifice; sparing what was devoted; consulting a medium",
  "verdict": "death",
  "summary": "A king undone by a pattern of partial obedience. He offered a sacrifice that was not his to offer, spared Agag and the best of the spoil against a direct command, and at the end sought a medium the law condemned.",
  "offense": "At Gilgal he would not wait for Samuel and offered the burnt offering himself. Sent to devote Amalek utterly, he kept the king and the best livestock and called it sacrifice. Finally, cut off from God, he consulted the witch of Endor.",
  "judgment": "The kingdom was torn from him and given to another. 'To obey is better than sacrifice.' He died by his own hand on Gilboa the next day, his sons with him.",
  "refs": R("1 Samuel 13:8-14", "1 Samuel 15:3", "1 Samuel 15:9", "1 Samuel 15:22-23", "1 Samuel 28:7", "1 Samuel 31:4-6"),
  "laws": ["20A", "2N", "22A"],
  "topics": ["obedience", "divination", "rebellious", "stiff-necked"],
  "themes": ["rebellion", "occult", "kingship"],
 },
 {
  "slug": "david-and-bathsheba",
  "name": "David and Bathsheba",
  "era": "Monarchy",
  "charge": "Adultery and the arranged death of Uriah",
  "verdict": "temporal",
  "summary": "The king took another man's wife, and when she conceived, engineered her husband's death to cover it. The prophet Nathan exposed it with a parable, and David confessed, but the consequences ran through his house for years.",
  "offense": "David lay with Bathsheba, wife of Uriah the Hittite, then recalled Uriah to mask the pregnancy; when that failed, he had him set in the front of battle to die. Adultery, deceit, and murder by another's hand.",
  "judgment": "The child died. Nathan declared that the sword would never depart from David's house, and it did not, his own sons rose against him. David was not executed; he repented, and the throne stood, but under a lasting wound.",
  "refs": R("2 Samuel 11:2-4", "2 Samuel 11:14-17", "2 Samuel 12:7-14", "Psalms 51:1-4"),
  "laws": ["1A.6", "1A.7", "5D", "4E"],
  "topics": ["adultery", "murder", "repentance"],
  "themes": ["adultery", "murder", "kingship", "repentance"],
 },
 {
  "slug": "gehazi",
  "name": "Gehazi",
  "era": "Monarchy",
  "charge": "Greed and lying to a prophet",
  "verdict": "curse",
  "summary": "Elisha refused payment from the healed Syrian Naaman. His servant Gehazi ran after Naaman, invented a story to collect silver and garments, then lied to Elisha's face about where he had been.",
  "offense": "Covetousness turned to fraud: he claimed the prophet had sent him, took the goods, hid them, and denied it. He traded the integrity of the prophetic office for money.",
  "judgment": "Elisha, knowing all of it, pronounced that Naaman's leprosy would cling to Gehazi and his seed forever. He went out from his presence a leper, white as snow.",
  "refs": R("2 Kings 5:20-22", "2 Kings 5:25-27"),
  "laws": ["1A.8", "16C", "4E"],
  "topics": ["covet", "lying", "bribe", "money"],
  "themes": ["covetousness", "deceit"],
 },
 {
  "slug": "jezebel-and-naboth",
  "name": "Jezebel and Naboth's vineyard",
  "era": "Monarchy",
  "charge": "Judicial murder to seize an inheritance",
  "verdict": "death",
  "summary": "Ahab coveted Naboth's vineyard; Naboth would not sell his fathers' inheritance. Jezebel arranged false witnesses to accuse him of blaspheming God and the king, had him stoned, and handed the land to Ahab.",
  "offense": "Covetousness executed through the machinery of law itself: a proclaimed fast, suborned witnesses, a capital charge, and a stoning, every step a mockery of the statutes it borrowed.",
  "judgment": "Elijah met Ahab in the stolen vineyard with a sentence on the whole house. Dogs would lick Ahab's blood and eat Jezebel by the wall of Jezreel. Both came to pass.",
  "refs": R("1 Kings 21:1-4", "1 Kings 21:8-13", "1 Kings 21:17-19", "1 Kings 21:23", "2 Kings 9:30-37"),
  "laws": ["1A.8", "1A.10", "4E.1", "4E.3"],
  "topics": ["covet", "witnesses", "murder", "heritage"],
  "themes": ["covetousness", "false-witness", "murder", "kingship"],
 },
 {
  "slug": "uzzah",
  "name": "Uzzah and the ark",
  "era": "Monarchy",
  "charge": "Touching the ark, transported unlawfully",
  "verdict": "death",
  "summary": "The ark was moved on a new cart rather than borne by the Levites as the law required. When the oxen stumbled, Uzzah put out his hand to steady it and died at once.",
  "offense": "The deeper fault was corporate: the ark was to be carried on staves by Kohathites, never touched, never carted. Uzzah's reach was the moment the accumulated carelessness came due.",
  "judgment": "God struck him for his error, and he died there beside the ark. David, first angry then afraid, left the ark three months until he learned to move it the way the law prescribed.",
  "refs": R("2 Samuel 6:3-7", "Numbers 4:15", "1 Chronicles 15:13-15"),
  "laws": ["9A", "20A"],
  "topics": ["ark-of-covenant", "in-order", "obedience"],
  "themes": ["irreverence"],
 },
 {
  "slug": "ananias-and-sapphira",
  "name": "Ananias and Sapphira",
  "era": "Apostolic",
  "charge": "Lying to the Holy Spirit about a gift",
  "verdict": "death",
  "summary": "A couple sold property and gave part of the proceeds to the apostles while claiming it was the whole. The gift was never required; the lie was the offense. Each fell dead as it was exposed.",
  "offense": "They agreed together to keep back part of the price and present the rest as the full amount, a staged generosity meant to buy standing. Peter named it: not a lie to men but to God.",
  "judgment": "Ananias fell dead at Peter's word; Sapphira, questioned three hours later and holding to the same story, fell dead as well. Great fear came on the whole church.",
  "refs": R("Acts 5:1-4", "Acts 5:5-10", "Leviticus 19:11"),
  "laws": ["4E.1", "17K", "2B"],
  "topics": ["lying", "whitewashing", "agreement", "holy-ghost"],
  "themes": ["deceit"],
 },
 {
  "slug": "herod-agrippa",
  "name": "Herod Agrippa",
  "era": "Apostolic",
  "charge": "Accepting worship due to God alone",
  "verdict": "death",
  "summary": "Arrayed in royal robes, the king gave an oration and the crowd shouted that his was the voice of a god, not a man. He accepted the acclaim. The judgment was immediate and public.",
  "offense": "The sin was not the speech but the silence after it: he took to himself the honor owed to God, receiving worship he should have refused as Paul and Barnabas had refused it at Lystra.",
  "judgment": "Immediately an angel of the Lord struck him because he gave not God the glory; he was eaten of worms and died. The contrast follows at once: but the word of God grew and multiplied.",
  "refs": R("Acts 12:21-23", "Isaiah 42:8", "Exodus 20:3"),
  "laws": ["1A.1", "2D", "2H"],
  "topics": ["idolatry", "pride", "vainglory"],
  "themes": ["idolatry", "pride", "kingship"],
 },
 # A case from the Apocrypha, to show the corpus reaches there too
 {
  "slug": "antiochus-epiphanes",
  "name": "Antiochus Epiphanes",
  "era": "Second Temple (Apocrypha)",
  "charge": "Defiling the temple; forbidding the law; murdering the faithful",
  "verdict": "death",
  "summary": "The Seleucid king outlawed the law of Moses, defiled the temple with an idol, and put to death those who kept the covenant. The books of Maccabees record both his persecution and his end.",
  "offense": "He forbade circumcision and the sabbaths, set up the abomination on the altar, forced sacrifice to idols, and killed mothers who circumcised their sons and families who kept the law in secret.",
  "judgment": "Struck with an incurable disease of the bowels, worms rising from the living body, he died in a strange land in bitter grief, by the account, confessing at the last that it was right to be subject to God.",
  "refs": R("1 Maccabees 1:41-50", "1 Maccabees 1:54-64", "2 Maccabees 6:1-2", "2 Maccabees 9:5-10", "Daniel 11:31"),
  "laws": ["1A.1", "1A.4", "2D.3", "9A"],
  "topics": ["idolatry", "abomination", "persecution", "sabbath"],
  "themes": ["idolatry", "persecution", "kingship"],
 },
]


# The original set predates the finer era split; map its eras onto ERA_ORDER.
RE_ERA = {
  "moses-at-meribah": "Wilderness", "saul": "United Monarchy", "david-and-bathsheba": "United Monarchy",
  "uzzah": "United Monarchy", "gehazi": "Divided Kingdom", "jezebel-and-naboth": "Divided Kingdom",
  "eli-and-sons": "Judges",
}
# Apocrypha and later-scripture cross references that recall these same cases.
EXTRA_REFS = {
  "adam-and-eve": R("2 Esdras 3:7", "2 Esdras 3:21-22"),
  "cain": R("Wisdom of Solomon 10:3", "Hebrews 11:4"),
  "the-flood-generation": R("Wisdom of Solomon 10:4", "2 Esdras 3:8-10", "Sirach 16:7"),
  "sodom-and-gomorrah": R("Wisdom of Solomon 10:6-8", "Sirach 16:8", "Luke 17:28-30"),
  "the-golden-calf": R("Psalms 106:19-23", "Acts 7:39-41", "1 Corinthians 10:7"),
  "korah": R("Sirach 45:18-19", "Sirach 16:6", "Psalms 106:16-18"),
  "achan": R("Joshua 22:20", "2 Maccabees 12:40-41"),
  "saul": R("1 Chronicles 10:13-14", "Sirach 46:19-20"),
  "david-and-bathsheba": R("1 Kings 15:5", "Sirach 47:11"),
  "eli-and-sons": R("1 Samuel 3:11-14", "Sirach 46:13"),
  "antiochus-epiphanes": R("1 Maccabees 6:8-13"),
}
for c in CORE:
    c["era"] = RE_ERA.get(c["slug"], c["era"])
    c["refs"] = c["refs"] + EXTRA_REFS.get(c["slug"], [])

