from cases_lib import R

CASES = [
 {
  "slug": "the-elders-and-susanna",
  "name": "The two elders who accused Susanna",
  "era": "Second Temple (Apocrypha)",
  "charge": "Attempted adultery by extortion; false witness against an innocent woman",
  "verdict": "death",
  "summary": "Two elders of Babylon's Jews, appointed judges, hid in Joacim's garden, tried to force his wife Susanna, and when she cried out, accused her of adultery with a young man. The assembly believed them, as elders and judges, and condemned her to death. Daniel stopped the execution and examined them apart.",
  "offense": "Lust turned to extortion and then to perjury: they perverted their own hearts and turned away their eyes that they might not look unto heaven nor remember just judgments. Examined separately, one said the pair were under a mastick tree and the other under a holm tree. Their own mouths convicted them of false witness.",
  "judgment": "According to the law of Moses they did unto them in such sort as they maliciously intended to do to their neighbour: and they put them to death. Thus the innocent blood was saved the same day. Deuteronomy 19 is the statute; this is its clearest case.",
  "refs": R("Susanna 1:5-9", "Susanna 1:19-27", "Susanna 1:34-41", "Susanna 1:45-49", "Susanna 1:52-59", "Susanna 1:60-62", "Deuteronomy 19:16-19", "Exodus 23:1"),
  "laws": ["4E.1", "4E.7", "4E.12", "4E.13", "8C.9", "17H.5", "10J.1"],
  "topics": ["witnesses", "lying", "sexual-lust", "justice"],
  "themes": ["false-witness", "sexual-immorality", "retribution", "leadership"],
 },
 {
  "slug": "the-priests-of-bel",
  "name": "The priests of Bel",
  "era": "Second Temple (Apocrypha)",
  "charge": "Deceiving the king and the people with an idol that seemed to eat",
  "verdict": "death",
  "summary": "The Babylonians spent twelve measures of fine flour, forty sheep, and six vessels of wine daily on Bel, and the king asked Daniel why he would not worship a living god who ate so much. Daniel laughed. Ashes strewn on the temple floor showed the footprints of the seventy priests, their wives and children, who came in by a secret door under the table every night.",
  "offense": "Priests feeding themselves on offerings made to a lump of clay and brass, and threatening Daniel with death to protect the trade. The Epistle of Jeremiah describes the same racket: as for the things sacrificed unto them, their priests sell and abuse.",
  "judgment": "Therefore the king slew them, and delivered Bel into Daniel's power, who destroyed him and his temple. When Daniel then destroyed the dragon, the Babylonians forced the king to throw him to the lions; he came out unharmed, and those that were the cause of his destruction were cast into the den and devoured in a moment.",
  "refs": R("Bel and the Dragon 1:3-7", "Bel and the Dragon 1:8-15", "Bel and the Dragon 1:18-22", "Bel and the Dragon 1:28-32", "Bel and the Dragon 1:40-42", "Epistle of Jeremiah 1:26-28", "Isaiah 44:9-11", "Deuteronomy 13:5"),
  "laws": ["2D.10", "3J.15", "10F.3", "20F.9", "2D.9", "3E.5"],
  "topics": ["graven-images", "false-worship", "wood-and-stone", "false-prophets"],
  "themes": ["idolatry", "deceit", "priesthood"],
 },
 {
  "slug": "heliodorus",
  "name": "Heliodorus",
  "era": "Second Temple (Apocrypha)",
  "charge": "Attempting to plunder the temple treasury",
  "verdict": "reprieve",
  "summary": "Sent by King Seleucus on the information of Simon the temple governor, Heliodorus came to seize the money laid up in the treasury, though the high priest Onias told him it was the relief of widows and fatherless children and deposits held in trust. The whole city lay in sackcloth. He went in anyway.",
  "offense": "Sacrilege against the place, and theft from the poor the place protected. The law that forbids afflicting widows and the fatherless, and the law that makes God's house holy, were both in front of him. He proceeded as he had resolved.",
  "judgment": "A horse with a terrible rider in golden armor struck him with its forefeet, and two young men scourged him without ceasing; he fell to the ground in darkness and was carried out on a litter. Onias offered sacrifice for his life, and he lived. He returned to the king and testified: if thou hast any enemy or traitor, send him thither, and thou shalt receive him well scourged.",
  "refs": R("2 Maccabees 3:4-12", "2 Maccabees 3:13-21", "2 Maccabees 3:22-30", "2 Maccabees 3:31-40", "Exodus 22:22-24", "Psalms 93:5"),
  "laws": ["15C.3", "15C.5", "18B.1", "18B.2", "20A.15", "2C"],
  "topics": ["poor", "chosen-place", "fear-god", "treasure"],
  "themes": ["sacrilege", "theft", "oppression", "mercy"],
 },
 {
  "slug": "jason",
  "name": "Jason the high priest",
  "era": "Second Temple (Apocrypha)",
  "charge": "Buying the priesthood; setting up a Greek gymnasium; drawing his countrymen to heathen customs",
  "verdict": "exile",
  "summary": "Onias' brother Jason obtained the high priesthood from Antiochus for three hundred and sixty talents and a promise of more, then built a place of exercise under the tower itself, brought the young men under the Greek hat, and had the priests neglect the sacrifices to hasten to the games. He sent silver for the sacrifice of Hercules.",
  "offense": "The narrator's summary: such was the height of Greek fashions, and increase of heathenish manners, through the exceeding profaneness of Jason, that ungodly wretch, and no high priest. A bought office, a foreign religion imported into the sanctuary's shadow, and the law despised for the sake of the games. Then Menelaus outbid him.",
  "judgment": "Driven out, he attacked Jerusalem with a thousand men, slew his own citizens without mercy, and was driven out again. He fled from city to city, pursued of all men, hated as a forsaker of the laws; he that had cast out many unburied had none to mourn for him, and perished in a strange land.",
  "refs": R("2 Maccabees 4:7-10", "2 Maccabees 4:11-17", "2 Maccabees 4:18-20", "2 Maccabees 4:23-26", "2 Maccabees 5:5-10", "1 Maccabees 1:11-15"),
  "laws": ["4C.1", "20E.5", "2G.1", "20A.2", "9A", "2I.2", "20B.14"],
  "topics": ["assimilation", "heathen-greeks", "compromise", "kings-and-priests"],
  "themes": ["priesthood", "assimilation", "bribery", "exile"],
 },
 {
  "slug": "menelaus",
  "name": "Menelaus",
  "era": "Second Temple (Apocrypha)",
  "charge": "Buying the priesthood over Jason; stealing the temple vessels; procuring the murder of Onias; bribing his way past the king's judgment",
  "verdict": "death",
  "summary": "Sent by Jason to carry the king's money, Menelaus outbid him by three hundred talents and came back high priest, though he was not of Aaron's line by the account. He stole gold vessels from the temple to pay his debt, had the righteous Onias murdered for exposing him, and bought off the king when the Jews accused him.",
  "offense": "Second Maccabees lists him as the cause of all the mischief: a great traitor to the laws and to his own country, bringing nothing worthy the high priesthood, but having the fury of a cruel tyrant and the rage of a savage beast. The bribe that acquitted him sent his three accusers to death instead.",
  "judgment": "At last the King of kings moved Antiochus Eupator against him. In Beroea he was thrust into a tower of ashes fifty cubits high, the death for sacrilege, not having so much as burial in the earth: for inasmuch as he had committed many sins about the altar, whose fire and ashes were holy, he received his death in ashes.",
  "refs": R("2 Maccabees 4:23-27", "2 Maccabees 4:32-35", "2 Maccabees 4:39", "2 Maccabees 4:43-50", "2 Maccabees 5:15", "2 Maccabees 13:3-8"),
  "laws": ["4C.1", "4C.8", "10A.5", "18B.1", "20B.14", "20A.15", "4F.13"],
  "topics": ["bribe", "murder", "stealing", "kings-and-priests"],
  "themes": ["priesthood", "bribery", "murder", "theft"],
 },
 {
  "slug": "andronicus",
  "name": "Andronicus",
  "era": "Second Temple (Apocrypha)",
  "charge": "Murder of Onias the high priest under a sworn assurance",
  "verdict": "death",
  "summary": "Onias, having exposed Menelaus' theft of the temple vessels, took sanctuary at Daphne. Menelaus persuaded the king's deputy Andronicus to lure him out; he came to Onias in deceit, gave him his right hand with oaths, and though suspected, persuaded him to leave the sanctuary, and shut him up immediately without regard of justice.",
  "offense": "A murder achieved by a false oath and the violation of asylum. Even the Greeks, the text says, were grieved for the unjust death of a man who had lived soberly and in virtue.",
  "judgment": "When Antiochus heard of it he was sorry in his mind, and sent for Andronicus, stripped him of his purple, rent his clothes, led him through the city, and slew him in the same place where he had committed impiety against Onias. Thus the Lord rewarded him his punishment, as he had deserved.",
  "refs": R("2 Maccabees 4:30-38", "Exodus 21:14", "Leviticus 19:12", "Deuteronomy 27:24"),
  "laws": ["10A.5", "4D.2", "4D.3", "4D.15", "8A.14"],
  "topics": ["murder", "agreement", "lying"],
  "themes": ["murder", "deceit", "false-oath"],
 },
 {
  "slug": "lysimachus",
  "name": "Lysimachus",
  "era": "Second Temple (Apocrypha)",
  "charge": "Sacrilege: robbing the temple with Menelaus' consent",
  "verdict": "death",
  "summary": "Menelaus' brother committed many sacrileges in the city by his brother's consent and carried away much gold. The multitude gathered against him; he armed three thousand men under a captain of years and madness and attacked the crowd.",
  "offense": "Plunder of the sanctuary treated as family business, then armed force against the people who objected. The narrator calls him the church-robber.",
  "judgment": "The people took up stones and clubs and ashes, wounded many, killed some, put the rest to flight, and slew Lysimachus himself beside the treasury. Judgment executed by the congregation at the scene of the crime.",
  "refs": R("2 Maccabees 4:39-42", "Exodus 22:1", "Deuteronomy 17:7"),
  "laws": ["18B.1", "20A.15", "2P.15", "19A.14"],
  "topics": ["stealing", "judgement"],
  "themes": ["sacrilege", "theft"],
 },
 {
  "slug": "alcimus",
  "name": "Alcimus",
  "era": "Second Temple (Apocrypha)",
  "charge": "Slandering Judas to the king; slaying sixty Asideans under a sworn peace; pulling down the wall of the inner court",
  "verdict": "death",
  "summary": "Alcimus, who had defiled himself wilfully in the times of the mingling with the Gentiles, sought the high priesthood from Demetrius by accusing Judas Maccabeus of sedition. Sent with an army, he swore peace to the Asideans and killed sixty of them in one day. Later he commanded the wall of the inner court of the sanctuary pulled down, the work of the prophets.",
  "offense": "Perjury, judicial murder, and sacrilege by a priest. The people remembered the psalm over the dead: the flesh of thy saints have they cast out, and their blood have they shed round about Jerusalem, and there was none to bury them.",
  "judgment": "As he began to pull down the wall, Alcimus was plagued; his mouth was stopped, he was taken with a palsy, and could no more speak or set his house in order. So Alcimus died at that time with great torment.",
  "refs": R("1 Maccabees 7:5-9", "1 Maccabees 7:12-18", "1 Maccabees 7:21-25", "1 Maccabees 9:54-56", "2 Maccabees 14:3-10", "2 Maccabees 14:26-27", "Psalms 79:2-3"),
  "laws": ["4D.2", "4D.15", "10A.5", "12E.2", "20A.15", "20B.3", "4E.1"],
  "topics": ["false-brethren", "lying", "murder", "kings-and-priests"],
  "themes": ["priesthood", "deceit", "murder", "sacrilege"],
 },
 {
  "slug": "nicanor",
  "name": "Nicanor",
  "era": "Second Temple (Apocrypha)",
  "charge": "Blasphemy against the temple; breaking covenant with Judas; resolving to attack on the Sabbath",
  "verdict": "death",
  "summary": "Demetrius' general, having sworn friendship to Judas and broken it at Alcimus' instigation, stretched out his hand toward the temple and swore that if Judas were not delivered to him he would burn the house and build a temple to Bacchus. He resolved to attack on the Sabbath; asked if there were a Mighty one in heaven who commanded the day, he answered that he was mighty on earth.",
  "offense": "Contempt for the sanctuary, for the Sabbath, and for the God of both, spoken aloud as policy. The priests prayed at the altar for vengeance on the blasphemer; Judas' army prayed the prayer of Hezekiah against Sennacherib.",
  "judgment": "Nicanor fell first in the battle at Adasa, and his army fled. They cut off his head and the right hand which he stretched out so proudly, cut out the tongue of the blasphemer, hung the head from the tower over against the temple, and ordained the day a yearly feast, the day before Mordecai's day.",
  "refs": R("1 Maccabees 7:26-35", "1 Maccabees 7:39-47", "1 Maccabees 7:48-49", "2 Maccabees 14:26-36", "2 Maccabees 15:1-5", "2 Maccabees 15:28-36", "Psalms 74:22-23"),
  "laws": ["2K.2", "2K.5", "9C.2", "4D.2", "17G.13", "22D.8"],
  "topics": ["destruction-of-nicanor", "sabbath", "the-name", "our-enemies"],
  "themes": ["blasphemy", "sabbath", "pride", "war"],
 },
 {
  "slug": "holofernes",
  "name": "Holofernes",
  "era": "Second Temple (Apocrypha)",
  "charge": "Making Nebuchadnezzar a god; blasphemy against the God of Israel; lust and drunkenness",
  "verdict": "death",
  "summary": "Nebuchadnezzar's captain, sent to make all the earth worship the king alone as god, cut down the groves and gods of every nation and besieged Bethulia. Who is God but Nebuchadnezzar, he asked, and told Achior that the God of Israel would not save his people. Judith came to his camp.",
  "offense": "Idolatry enforced by the sword, and contempt for the Lord spoken to his face through Achior. On the fourth night his heart was ravished with Judith and he was filled with wine, more than he had drunk at any time in one day since he was born.",
  "judgment": "Judith took his own fauchion, smote twice upon his neck with all her might, and took away his head; his army, finding him headless in his tent, fled and was cut down. Judith's song: the Lord Almighty hath disappointed them by the hand of a woman.",
  "refs": R("Judith 2:4-13", "Judith 3:8", "Judith 6:2-4", "Judith 12:16-20", "Judith 13:2", "Judith 13:6-10", "Judith 14:18-19", "Judith 16:5-6", "Judith 9:7-10"),
  "laws": ["2D.2", "2D.1", "2K.2", "17G.13", "12G.12", "17H.5", "22A.19"],
  "topics": ["pride", "drinking", "sexual-lust", "our-enemies", "other-gods"],
  "themes": ["pride", "blasphemy", "drunkenness", "lust", "war"],
 },
 {
  "slug": "nadab-and-achiacharus",
  "name": "Aman, who ensnared Achiacharus",
  "era": "Second Temple (Apocrypha)",
  "charge": "Treachery against the man who brought him up",
  "verdict": "death",
  "summary": "Tobit's dying counsel to his son holds up one case: remember how Aman handled Achiacharus that brought him up, how out of light he brought him into darkness, and how he rewarded him again. Achiacharus, the king's cupbearer and Tobit's kinsman, had once interceded for Tobit himself.",
  "offense": "Ingratitude become betrayal, against a benefactor who stood as a father. The story assumed by the text is the tale of Ahikar: the adopted nephew who forged evidence to have his uncle executed.",
  "judgment": "Achiacharus was saved, but the other had his reward: for he went down into darkness. Aman fell into the snare and perished. Tobit's moral: consider what alms doeth, and how righteousness doth deliver.",
  "refs": R("Tobit 14:10-11", "Tobit 1:21-22", "Tobit 2:10", "Tobit 11:18", "Proverbs 26:27", "Psalms 35:7-8"),
  "laws": ["3J.6", "3J.15", "17M.7", "2P.2", "3E.11"],
  "topics": ["alms-deliver", "lying", "false-brethren"],
  "themes": ["betrayal", "deceit", "retribution"],
 },
 {
  "slug": "soldiers-with-idol-tokens",
  "name": "Judas' soldiers with idol tokens under their coats",
  "era": "Second Temple (Apocrypha)",
  "charge": "Carrying things consecrated to idols into battle",
  "verdict": "death",
  "summary": "After the battle near Adullam, Judas and his company came to bury their dead and found under the coat of every slain man things consecrated to the idols of the Jamnites, which is forbidden the Jews by the law. Then every man saw that this was the cause wherefore they were slain.",
  "offense": "Deuteronomy: thou shalt not bring an abomination into thine house, lest thou be a cursed thing like it. Joshua's men had died at Ai for Achan's hidden spoil; these had died in a battle they otherwise won.",
  "judgment": "The survivors praised the Lord, the righteous Judge, who had opened the things that were hid, and prayed that the sin might be wholly put out of remembrance. Judas took a collection and sent it to Jerusalem for a sin offering for the dead.",
  "refs": R("2 Maccabees 12:38-45", "Deuteronomy 7:25-26", "Joshua 7:11-13", "Joshua 6:18"),
  "laws": ["22A.11", "2D.8", "1A.2", "22A.12"],
  "topics": ["idolatry", "exposed", "army"],
  "themes": ["idolatry", "war", "hidden-sin"],
 },
 {
  "slug": "the-apostate-at-modin",
  "name": "The Jew who sacrificed at Modin",
  "era": "Second Temple (Apocrypha)",
  "charge": "Sacrificing on the heathen altar at the king's command",
  "verdict": "death",
  "summary": "The king's officers came to Modin to compel sacrifice and offered Mattathias silver, gold, and the title of king's friend to go first. He refused for himself and his sons. A Jew stepped forward in the sight of all to sacrifice on the altar according to the king's commandment.",
  "offense": "Deuteronomy 13 and 17: the man who serves other gods, or entices to it, in Israel shall be put to death, and the hand of the witnesses first upon him. He did it publicly, for reward, to lead the rest.",
  "judgment": "Mattathias was inflamed with zeal, ran upon him, and slew him at the altar, and the king's commissioner with him, and pulled down the altar. Thus dealt he zealously for the law of God, like as Phinees did unto Zambri. The revolt began there.",
  "refs": R("1 Maccabees 2:15-22", "1 Maccabees 2:23-28", "Deuteronomy 13:6-10", "Deuteronomy 17:2-7", "Numbers 25:7-8", "Numbers 25:11"),
  "laws": ["10F.1", "10F.6", "2D.12", "19E"],
  "topics": ["idolatry", "compromise", "peer-pressure"],
  "themes": ["idolatry", "apostasy", "enticement"],
 },
 {
  "slug": "the-hellenizers",
  "name": "The Hellenizers who forsook the holy covenant",
  "era": "Second Temple (Apocrypha)",
  "charge": "Covenanting with the heathen; removing circumcision; profaning the Sabbath; sacrificing to idols",
  "verdict": "death",
  "summary": "In the days of Antiochus, wicked men went out of Israel persuading many to make a covenant with the heathen round about. They built a place of exercise at Jerusalem, made themselves uncircumcised, forsook the holy covenant, and were sold to do mischief. When the king's decree came, many Israelites consented to his religion.",
  "offense": "First Maccabees calls them sinners and wicked men; Second Maccabees traces the profaneness to Jason. Every mark of the covenant was surrendered by choice: circumcision, Sabbath, sacrifice, food, and the company of the nations.",
  "judgment": "Mattathias and his friends smote sinful men in their anger and wicked men in their wrath; the rest fled to the heathen for succour. Judas burnt up those that vexed his people, and the wicked shrunk for fear of him. After Antiochus, the ungodly out of Israel who sought Alcimus' priesthood found Judas had taken vengeance on their sort.",
  "refs": R("1 Maccabees 1:11-15", "1 Maccabees 1:43", "1 Maccabees 1:52", "1 Maccabees 2:44-48", "1 Maccabees 3:5-8", "2 Maccabees 4:13-15", "Genesis 17:14", "Exodus 31:14"),
  "laws": ["2G.1", "2G.6", "11C.1", "14F.9", "9C.4", "10F.1", "2I.2"],
  "topics": ["assimilation", "compromise", "heathen-greeks", "peer-pressure", "circumcision"],
  "themes": ["assimilation", "apostasy", "corporate-judgment"],
 },
]
