# Judgment cases missing from data/cases.json, added 2026-09. Run scripts/cases-merge.py.
def R(book, ch, vv=None):
    return {"book": book, "chapter": ch, **({"verses": vv} if vv else {})}

CASES = [
 # ---------------- Patriarchal ----------------
 dict(slug="pharaoh-and-abimelech-with-sarah", name="Pharaoh and Abimelech, who took Sarah", era="Patriarchal",
  charge="Taking another man's wife into the king's house", verdict="plague",
  summary="Twice Abraham called Sarah his sister, and twice a king took her. Neither king knew she was married, and both were judged before they touched her: the Lord guards the marriage bed even where the husband has failed to.",
  offense="In Egypt, Pharaoh's princes commended Sarai and she was taken into Pharaoh's house. In Gerar, Abimelech sent and took Sarah. Both acted on Abraham's word that she was his sister, and Abimelech pleaded the integrity of his heart; but the woman was a man's wife, and that fact, not their knowledge of it, was what the Lord answered.",
  judgment="The Lord plagued Pharaoh and his house with great plagues because of Sarai. To Abimelech he came in a dream: thou art but a dead man, for the woman is a man's wife. The Lord had closed up every womb of the house of Abimelech, and opened them only when Sarah was restored and Abraham, the prophet, prayed for him.",
  refs=[R("Genesis",12,"14-20"),R("Genesis",20,"1-7"),R("Genesis",20,"14-18"),R("Psalms",105,"13-15"),R("Exodus",20,"14"),R("Hebrews",13,"4")],
  laws=["5D","5A","1A"], topics=["adultery","wife","marriage"], themes=["sexual-immorality","retribution","kingship","covenant"]),

 dict(slug="judah-and-tamar", name="Judah and Tamar", era="Patriarchal",
  charge="Withholding Shelah from his brother's widow; going in to a woman he took for a harlot", verdict="spared",
  summary="Judah promised Tamar his third son and never gave him, then lay with her himself on the road to Timnath. When her pregnancy came to light he ordered her burned, until she produced his signet, bracelets and staff. He judged himself: she hath been more righteous than I.",
  offense="After Er and Onan died, Judah sent Tamar to her father's house to wait for Shelah, and let her wait. Tamar covered her face and sat in an open place, and Judah, taking her for a harlot, went in to her for the price of a kid, leaving his signet and staff as a pledge. Three months later he was told his daughter in law was with child by whoredom, and said, Bring her forth, and let her be burnt.",
  judgment="No sentence fell on Tamar; Judah stopped it himself when the pledge was laid before him, confessed that the fault was his for withholding Shelah, and knew her again no more. She bore Pharez and Zarah, and Pharez stands in the line of David and of Christ. The judgment recorded is a confession that spared the innocent and let the guilty man's own mouth condemn him.",
  refs=[R("Genesis",38,"6-11"),R("Genesis",38,"12-19"),R("Genesis",38,"24-26"),R("Deuteronomy",25,"5-10"),R("Ruth",4,"12"),R("Matthew",1,"3")],
  laws=["5E","6E","4D","3D"], topics=["honest","marriage","repentance","witnesses"], themes=["sexual-immorality","deceit","repentance","family"]),

 # ---------------- Wilderness ----------------
 dict(slug="the-plague-after-korah", name="The congregation, the day after Korah", era="Wilderness",
  charge="Murmuring that Moses and Aaron had killed the people of the Lord", verdict="plague",
  summary="The earth had swallowed Korah's company the day before, and fire had consumed the two hundred and fifty. The next morning the whole congregation gathered against Moses and Aaron and called the dead the people of the Lord. The plague began before the sentence was finished being spoken.",
  offense="On the morrow all the congregation murmured against Moses and against Aaron, saying, Ye have killed the people of the Lord. They took the side of the rebels the Lord had just judged, and made the judgment itself the grievance.",
  judgment="The glory of the Lord appeared and wrath went out from him; the plague was begun. Moses sent Aaron running into the congregation with a censer to make an atonement, and he stood between the dead and the living, and the plague was stayed. Fourteen thousand and seven hundred died, beside them that died about the matter of Korah.",
  refs=[R("Numbers",16,"41-50"),R("Numbers",17,"10"),R("1 Corinthians",10,"10"),R("Psalms",106,"16-18")],
  laws=["2H","8D","2P"], topics=["murmuring","rebellious","submission"], themes=["murmuring","corporate-judgment","rebellion","priesthood"]),

 dict(slug="sihon-and-og", name="Sihon and Og", era="Wilderness",
  charge="Refusing Israel passage and coming out to battle against them", verdict="death",
  summary="Israel asked only to pass through on the king's highway, turning neither to the right nor to the left. Sihon gathered his people and came out to fight, and Og after him. Both kingdoms were given into Israel's hand, and the land east of Jordan became the first inheritance.",
  offense="Moses sent messengers to Sihon king of the Amorites with words of peace: let me pass through thy land; we will not turn into the fields or the vineyards. Sihon would not suffer Israel to pass, but gathered all his people and fought at Jahaz. Og king of Bashan came out against them at Edrei, the last of the remnant of giants.",
  judgment="Israel smote Sihon with the edge of the sword and possessed his land from Arnon to Jabbok. Of Og the Lord said, Fear him not, for I have delivered him into thy hand; they smote him and his sons and all his people until none was left him alive. The psalms remember it as mercy that endureth for ever: who smote great kings, and gave their land for an heritage.",
  refs=[R("Numbers",21,"21-26"),R("Numbers",21,"33-35"),R("Deuteronomy",2,"26-36"),R("Deuteronomy",3,"1-11"),R("Psalms",136,"17-22"),R("Deuteronomy",20,"10-12")],
  laws=["22E","22A","11A"], topics=["our-enemies","judgement-of-nations","giants"], themes=["war","corporate-judgment","inheritance"]),

 dict(slug="the-midianites-at-peor", name="The Midianites, in the matter of Peor", era="Wilderness",
  charge="Beguiling Israel with their wiles into fornication and the worship of Baal-peor", verdict="death",
  summary="Balaam could not curse Israel, so he taught Balak how to make Israel curse itself. The daughters of Midian and Moab drew the people to Peor, and twenty-four thousand died in the plague. The Lord then told Moses to avenge Israel of the Midianites before he was gathered to his people.",
  offense="On Balaam's counsel the women of Midian invited the people to the sacrifices of their gods; the people ate, and bowed down, and joined themselves to Baal-peor. Cozbi, the daughter of a prince of Midian, was brought into the camp itself. They vexed Israel with their wiles, wherewith they beguiled you in the matter of Peor.",
  judgment="Vex the Midianites, and smite them. Israel warred against Midian as the Lord commanded Moses and slew all the males, the five kings of Midian, and Balaam the son of Beor with the sword. Moses was angry that the women who had caused the trespass were kept alive, and the sentence was carried through on them also.",
  refs=[R("Numbers",25,"1-3"),R("Numbers",25,"16-18"),R("Numbers",31,"1-8"),R("Numbers",31,"14-18"),R("Revelation",2,"14"),R("Deuteronomy",7,"2-4")],
  laws=["2D","22A","5E","11A"], topics=["other-gods","our-enemies","sexual-lust","peer-pressure"], themes=["enticement","idolatry","war","corporate-judgment","sexual-immorality"]),

 # ---------------- Judges ----------------
 dict(slug="eglon-king-of-moab", name="Eglon king of Moab", era="Judges",
  charge="Possessing the city of palm trees and taking tribute of Israel eighteen years", verdict="death",
  summary="The Lord strengthened Eglon against Israel because Israel did evil, and for eighteen years Israel served him. When they cried, the Lord raised up Ehud, a left-handed Benjamite with a message from God, and the message was a dagger.",
  offense="Eglon gathered Ammon and Amalek, smote Israel, and took the city of palm trees. He held Israel under tribute for eighteen years, a fat man in a summer parlour receiving the present of the people he oppressed.",
  judgment="Ehud brought the present, then said, I have a message from God unto thee, and thrust the dagger into his belly so that the haft went in after the blade. Israel followed him down and slew about ten thousand men of Moab, all lusty and men of valour, and Moab was subdued, and the land had rest fourscore years.",
  refs=[R("Judges",3,"12-14"),R("Judges",3,"15-26"),R("Judges",3,"27-30"),R("Deuteronomy",28,"47-48")],
  laws=["11A","22D","2P"], topics=["our-enemies","deliverance","captivity"], themes=["oppression","war","retribution","deliverance"]),

 dict(slug="jabin-and-sisera", name="Jabin and Sisera", era="Judges",
  charge="Mightily oppressing Israel twenty years with nine hundred chariots of iron", verdict="death",
  summary="Jabin reigned in Hazor and Sisera commanded his host, and for twenty years they mightily oppressed the children of Israel. Deborah sent for Barak, the Lord discomfited the chariots at Kishon, and Sisera died in a tent with a nail through his temples.",
  offense="Israel again did evil after Ehud was dead, and the Lord sold them into the hand of Jabin king of Canaan. Sisera, captain of his host, had nine hundred chariots of iron and used them to oppress Israel mightily for twenty years, so that the highways were unoccupied and the travellers walked through byways.",
  judgment="The Lord discomfited Sisera and all his chariots and all his host with the edge of the sword before Barak; the river of Kishon swept them away. Sisera fled on foot to the tent of Jael, who gave him milk and a nail. The hand of Israel prospered and prevailed against Jabin until they had destroyed him. Deborah sang it: so let all thine enemies perish, O Lord.",
  refs=[R("Judges",4,"1-3"),R("Judges",4,"12-16"),R("Judges",4,"17-24"),R("Judges",5,"19-22"),R("Judges",5,"24-31"),R("Psalms",83,"9-10")],
  laws=["11A","22D","2P"], topics=["our-enemies","deliverance","judgement-of-nations"], themes=["oppression","war","retribution","deliverance"]),

 dict(slug="the-philistines-and-the-ark", name="The Philistines and the captured ark", era="Judges",
  charge="Setting the ark of God in the house of Dagon, and keeping it seven months", verdict="plague",
  summary="The Philistines took the ark in battle and set it beside Dagon as a trophy. Dagon fell on his face before it twice, the second time without head or hands, and the men of Ashdod, Gath and Ekron were smitten with emerods until they sent it home on a new cart with golden offerings.",
  offense="They carried the ark of God into the house of Dagon and set it by Dagon, as if the God of Israel had been taken captive by their god. When Ashdod could bear it no longer they moved it to Gath, and Gath to Ekron, each city passing the judgment along rather than sending the ark back.",
  judgment="The hand of the Lord was heavy upon them of Ashdod, and he destroyed them and smote them with emerods; the men of Gath, small and great, were smitten; in Ekron there was a deadly destruction throughout all the city. Their priests and diviners told them to give glory unto the God of Israel and not harden their hearts as the Egyptians and Pharaoh did, and the ark went back with five golden emerods and five golden mice, a trespass offering.",
  refs=[R("1 Samuel",5,"1-7"),R("1 Samuel",5,"8-12"),R("1 Samuel",6,"1-9"),R("1 Samuel",6,"10-16"),R("Psalms",78,"61-66")],
  laws=["2D","10F","2M"], topics=["other-gods","ark-of-covenant","our-enemies"], themes=["idolatry","irreverence","corporate-judgment","retribution"]),

 # ---------------- United Monarchy ----------------
 dict(slug="agag", name="Agag king of the Amalekites", era="United Monarchy",
  charge="The sword that made women childless", verdict="death",
  summary="The Lord had sworn war with Amalek from generation to generation for what they did to Israel on the way out of Egypt. Saul was sent to finish it and spared Agag. Samuel did not: as thy sword hath made women childless, so shall thy mother be childless among women.",
  offense="Agag was king of a people whose whole memory before the Lord was one act: smiting the feeble and the faint at the rear of Israel's march, without fear of God. In his own day he came to Samuel delicately, saying, Surely the bitterness of death is past, as though the old blood had dried.",
  judgment="Samuel said, Bring ye hither to me Agag the king of the Amalekites, and hewed Agag in pieces before the Lord in Gilgal. The sentence pronounced at Rephidim was carried out by a prophet's hand when the king's hand failed.",
  refs=[R("Exodus",17,"14-16"),R("Deuteronomy",25,"17-19"),R("1 Samuel",15,"1-3"),R("1 Samuel",15,"8-9"),R("1 Samuel",15,"32-33")],
  laws=["22D","11A","10A"], topics=["our-enemies","avenge","judgement-of-nations"], themes=["retribution","war","bloodshed"]),

 dict(slug="goliath", name="Goliath of Gath", era="United Monarchy",
  charge="Defying the armies of the living God, morning and evening, forty days", verdict="death",
  summary="Six cubits and a span, with a spear like a weaver's beam, Goliath stood in the valley of Elah and reproached Israel for forty days. A shepherd boy came in the name of the Lord of hosts and took his head with his own sword.",
  offense="He stood and cried unto the armies of Israel, I defy the armies of Israel this day; give me a man, that we may fight together. When David came he cursed him by his gods and promised his flesh to the fowls. David named the crime exactly: he hath defied the armies of the living God.",
  judgment="This day will the Lord deliver thee into mine hand, that all the earth may know that there is a God in Israel. The stone sunk into his forehead and he fell upon his face to the earth; David stood upon him, drew his sword out of the sheath, and cut off his head with it. The Philistines fled and Israel spoiled their tents.",
  refs=[R("1 Samuel",17,"4-11"),R("1 Samuel",17,"23-26"),R("1 Samuel",17,"41-47"),R("1 Samuel",17,"48-54"),R("Sirach",47,"3-5")],
  laws=["2K","11A","22A"], topics=["our-enemies","the-name","pride"], themes=["blasphemy","pride","war","deliverance"]),

 dict(slug="sauls-oath-and-jonathan", name="Saul's rash oath, and the people at the blood", era="United Monarchy",
  charge="A rash oath that snared the army; the people eating flesh with the blood; the son who unknowingly broke the oath", verdict="spared",
  summary="Saul adjured the people to eat nothing until evening, and the army fainted in the pursuit. Jonathan, who had not heard, ate honey; the people, famished, fell on the spoil and ate with the blood; and when the lot fell on Jonathan the people would not let the king kill the man who had wrought the day's salvation.",
  offense="Saul's oath was his own, not the Lord's, and it was a curse on any man that eateth any food until evening. The people were so faint that when evening came they flew upon the spoil and did eat with the blood, which the law forbids. Jonathan tasted a little honey on the end of his rod and his eyes were enlightened; he called his father's oath a trouble to the land.",
  judgment="Saul was told, The people sin against the Lord, in that they eat with the blood, and he rolled a great stone and had the beasts slain on it, and built his first altar. Then the Lord answered him not, and the lot taken to find the cause fell on Jonathan. Saul swore he should surely die; the people rescued Jonathan, that he died not, on the witness that he had wrought with God that day. The oath was Saul's; the mercy was the people's; the silence was the Lord's.",
  refs=[R("1 Samuel",14,"24-30"),R("1 Samuel",14,"31-35"),R("1 Samuel",14,"36-46"),R("Leviticus",17,"10-12"),R("Ecclesiastes",5,"2-5")],
  laws=["4D","14D","19B"], topics=["agreement","clean-food","obedience"], themes=["irreverence","negligence","kingship","mercy"]),

 # ---------------- Divided Kingdom ----------------
 dict(slug="baasha", name="Baasha", era="Divided Kingdom",
  charge="Walking in the way of Jeroboam after being raised up to destroy Jeroboam's house", verdict="death",
  summary="Baasha killed Nadab and every soul of the house of Jeroboam, exactly as Ahijah had prophesied. Then he reigned twenty-four years in the same sins, and the same prophecy was spoken over his own house by Jehu the son of Hanani.",
  offense="He conspired against Nadab at Gibbethon and slew him, and left not to Jeroboam any that breathed. That was the word of the Lord. But he walked in the way of Jeroboam and in his sin, wherewith he made Israel to sin, and provoked the Lord with the work of his hands, in being like the house of Jeroboam, and because he killed him.",
  judgment="Forasmuch as I exalted thee out of the dust and made thee prince over my people Israel, and thou hast walked in the way of Jeroboam: I will take away the posterity of Baasha. Him that dieth of Baasha in the city shall the dogs eat. Zimri did it in the days of Elah his son, leaving him not one that pisseth against a wall, neither of his kinsfolks nor of his friends.",
  refs=[R("1 Kings",15,"27-30"),R("1 Kings",15,"33-34"),R("1 Kings",16,"1-7"),R("1 Kings",16,"11-13"),R("2 Chronicles",16,"1-6")],
  laws=["2D","2I","8A"], topics=["idolatry","kings-and-priests","stiff-necked"], themes=["idolatry","kingship","retribution","backsliding"]),

 dict(slug="zimri", name="Zimri", era="Divided Kingdom",
  charge="Conspiring against his master Elah as he drank himself drunk; slaying all the house of Baasha", verdict="death",
  summary="Captain of half the chariots, Zimri killed his king in a steward's house and took the throne. Seven days later the army chose Omri, Tirzah was taken, and Zimri burned the king's house over his own head. His name became a byword: Had Zimri peace, who slew his master?",
  offense="Elah was in Tirzah, drinking himself drunk, and Zimri went in and smote him. He slew all the house of Baasha, sparing not one, and reigned in his stead. Scripture records that he too walked in the way of Jeroboam, in his sin which he did, making Israel to sin.",
  judgment="The people that were encamped heard, and made Omri king that same day, and besieged Tirzah. When Zimri saw that the city was taken, he went into the palace of the king's house, and burnt the king's house over him with fire, and died, for his sins which he sinned. Jezebel would throw his name at Jehu a generation later as the name of a traitor who did not last.",
  refs=[R("1 Kings",16,"8-14"),R("1 Kings",16,"15-20"),R("2 Kings",9,"31"),R("Proverbs",28,"17")],
  laws=["10A","10G","8D"], topics=["murder","kings-and-priests","rebellious"], themes=["murder","kingship","rebellion","retribution"]),

 dict(slug="hiel-the-bethelite", name="Hiel the Bethelite", era="Divided Kingdom",
  charge="Rebuilding Jericho under the oath Joshua swore before the Lord", verdict="curse",
  summary="When Jericho fell, Joshua adjured Israel: cursed be the man that riseth up and buildeth this city; he shall lay the foundation in his firstborn and set up the gates in his youngest son. Five hundred years later, in the days of Ahab, Hiel built it, and buried both.",
  offense="In the days of Ahab, when every old boundary was being moved, Hiel of Bethel undertook what the oath forbade and rebuilt Jericho. Whether he mocked the curse or had never learned it, he laid the foundation and hung the gates.",
  judgment="He laid the foundation thereof in Abiram his firstborn, and set up the gates thereof in his youngest son Segub, according to the word of the Lord, which he spake by Joshua the son of Nun. The sentence waited five centuries and lost nothing in the waiting.",
  refs=[R("Joshua",6,"26"),R("1 Kings",16,"33-34"),R("Numbers",30,"2"),R("Ecclesiastes",8,"11")],
  laws=["4D","2F","2P"], topics=["curse-of-the-law","obedience","agreement"], themes=["disobedience","retribution","covenant"]),

 dict(slug="ben-hadad-and-the-syrians", name="Ben-hadad and the Syrians at Aphek", era="Divided Kingdom",
  charge="Saying the Lord is a god of the hills and not of the valleys", verdict="death",
  summary="Beaten at Samaria, the Syrians told their king the God of Israel was a hill god and would lose on level ground. The Lord heard it. A prophet told Ahab the outcome before the battle: that ye may know that I am the Lord.",
  offense="The servants of the king of Syria said, Their gods are gods of the hills; therefore they were stronger than we: but let us fight against them in the plain, and surely we shall be stronger than they. Ben-hadad numbered the Syrians and went up to Aphek with a host that filled the country.",
  judgment="Because the Syrians have said, The Lord is God of the hills, but he is not God of the valleys, therefore will I deliver all this great multitude into thine hand. Israel slew of the Syrians an hundred thousand footmen in one day; the rest fled to Aphek, and a wall fell on twenty and seven thousand of them. Ben-hadad survived only because Ahab, against the word of the Lord, let him go.",
  refs=[R("1 Kings",20,"23-25"),R("1 Kings",20,"26-30"),R("1 Kings",20,"13"),R("Psalms",96,"4-5")],
  laws=["2K","11A","2M"], topics=["whose-god","our-enemies","omnipotent"], themes=["blasphemy","war","corporate-judgment"]),

 dict(slug="jehoram-of-judah", name="Jehoram of Judah", era="Divided Kingdom",
  charge="Slaying all his brethren with the sword; walking in the way of the house of Ahab; making high places and compelling Judah to fornication", verdict="death",
  summary="Jehoshaphat's eldest son married Ahab's daughter, killed his six brothers to secure the throne, and led Judah to the high places. A writing came to him from Elijah naming the sentence: a great plague on his people, his children and his wives, and a disease of the bowels that would take two years to kill him.",
  offense="When Jehoram was risen up to the kingdom of his father, he strengthened himself and slew all his brethren with the sword, and divers also of the princes of Israel. He walked in the way of the kings of Israel, like as did the house of Ahab, for he had the daughter of Ahab to wife. He made high places in the mountains of Judah and caused the inhabitants of Jerusalem to commit fornication, and compelled Judah thereto.",
  judgment="Edom revolted, and Libnah. The Philistines and Arabians came up and carried away all the substance of the king's house, and his sons also and his wives, so that there was never a son left him save the youngest. After all this the Lord smote him in his bowels with an incurable disease, and after two years his bowels fell out and he died of sore diseases. His people made no burning for him; he departed without being desired; and they buried him in the city of David, but not in the sepulchres of the kings.",
  refs=[R("2 Chronicles",21,"4-7"),R("2 Chronicles",21,"11-15"),R("2 Chronicles",21,"16-20"),R("2 Kings",8,"16-22"),R("Deuteronomy",28,"58-61")],
  laws=["10A","2D","2I","8A"], topics=["murder","idolatry","kings-and-priests","intermarrying"], themes=["murder","idolatry","kingship","retribution","intermarriage"]),

 dict(slug="ahaziah-of-judah", name="Ahaziah of Judah", era="Divided Kingdom",
  charge="Walking in the ways of the house of Ahab, his mother being his counsellor to do wickedly", verdict="death",
  summary="Athaliah's son reigned one year. He took the house of Ahab for his counsellors after his father's death, went with Joram to war, and went to visit him in Jezreel on the very day Jehu came to execute the house of Ahab. His destruction, the chronicler says, was of God.",
  offense="He also walked in the ways of the house of Ahab: for his mother was his counsellor to do wickedly. Wherefore he did evil in the sight of the Lord like the house of Ahab, for they were his counsellors after the death of his father to his destruction. He walked also after their counsel, and went with Jehoram to fight against Hazael.",
  judgment="The destruction of Ahaziah was of God by coming to Joram: for when he was come, he went out with Jehoram against Jehu, whom the Lord had anointed to cut off the house of Ahab. Jehu's men found him hid in Samaria, brought him to Jehu, and slew him; and they buried him, because, they said, he is the son of Jehoshaphat, who sought the Lord with all his heart. His father's name bought him a grave; his mother's counsel had cost him the throne.",
  refs=[R("2 Chronicles",22,"1-6"),R("2 Chronicles",22,"7-9"),R("2 Kings",8,"25-29"),R("2 Kings",9,"27-29"),R("Proverbs",13,"20")],
  laws=["2I","11C","8A","6B"], topics=["kings-and-priests","seek-counsel","peer-pressure","intermarrying"], themes=["kingship","idolatry","backsliding","corporate-judgment"]),

 dict(slug="the-lord-on-whose-hand-the-king-leaned", name="The lord on whose hand the king leaned", era="Divided Kingdom",
  charge="Scoffing at the word of the Lord by Elisha in the famine of Samaria", verdict="death",
  summary="In a siege so hard that women ate their children, Elisha said that by the next day fine flour would sell for a shekel in the gate. The king's officer answered that it could not happen if the Lord opened windows in heaven. He saw it, and was trampled in the gate by the crowd rushing to buy.",
  offense="Elisha said, Hear ye the word of the Lord; Thus saith the Lord, To morrow about this time shall a measure of fine flour be sold for a shekel in the gate of Samaria. A lord on whose hand the king leaned answered the man of God: Behold, if the Lord would make windows in heaven, might this thing be? The unbelief was spoken aloud, in the king's hearing, against a word that had just been named as the Lord's.",
  judgment="Elisha answered, Behold, thou shalt see it with thine eyes, but shalt not eat thereof. The Syrians fled in the night from a noise the Lord made them hear; the people went out and spoiled their tents; and the king appointed that same lord to have charge of the gate, and the people trode upon him in the gate, and he died, as the man of God had said.",
  refs=[R("2 Kings",7,"1-2"),R("2 Kings",7,"6-7"),R("2 Kings",7,"16-20"),R("Hebrews",3,"12"),R("2 Chronicles",20,"20")],
  laws=["2B","2K","2F"], topics=["believe","windows-of-heaven","scoffer"], themes=["irreverence","retribution","reproof"]),

 dict(slug="asa-in-his-latter-years", name="Asa in his latter years", era="Divided Kingdom",
  charge="Hiring the king of Syria against Israel; imprisoning the seer who reproved him; seeking to the physicians and not to the Lord", verdict="temporal",
  summary="For thirty-five years Asa was one of Judah's best kings. Then Baasha fortified Ramah, and Asa emptied the temple treasury to buy Ben-hadad's help instead of relying on the Lord who had given him the Ethiopians. Rebuked, he put the seer in the stocks; diseased, he sought physicians; and he died in the forty-first year of his reign.",
  offense="Hanani the seer said: Because thou hast relied on the king of Syria, and not relied on the Lord thy God, therefore is the host of the king of Syria escaped out of thine hand. Were not the Ethiopians a huge host? Yet because thou didst rely on the Lord he delivered them into thine hand. Asa was wroth with the seer and put him in a prison house, and oppressed some of the people the same time. When his feet were diseased, in his disease he sought not to the Lord, but to the physicians.",
  judgment="Herein thou hast done foolishly: therefore from henceforth thou shalt have wars. The disease in his feet became exceeding great, and he slept with his fathers in the forty-first year. The chronicler is careful to keep the account whole: the heart of Asa was perfect all his days, and the last chapter is still written.",
  refs=[R("2 Chronicles",16,"1-6"),R("2 Chronicles",16,"7-10"),R("2 Chronicles",16,"11-14"),R("1 Kings",15,"23"),R("Jeremiah",17,"5-8"),R("2 Chronicles",15,"17")],
  laws=["11C","2B","3L","8A"], topics=["trust-god","seek-the-lord","sickness","persecution"], themes=["kingship","backsliding","reproof","persecution"]),

 dict(slug="jehoshaphats-alliances", name="Jehoshaphat's alliances", era="Divided Kingdom",
  charge="Joining affinity with Ahab; going to Ramoth-gilead with him; joining with Ahaziah to make ships", verdict="temporal",
  summary="A king who sought the Lord and taught the law through Judah kept making common cause with the house of Ahab. He nearly died at Ramoth-gilead in Ahab's place, was told by Jehu the seer that wrath was upon him for helping the ungodly, and later lost a whole fleet at Ezion-geber for the same fault.",
  offense="Jehoshaphat had riches and honour in abundance, and joined affinity with Ahab. He went down to Samaria and said, I am as thou art, and my people as thy people; and we will be with thee in the war. Years afterward he joined himself with Ahaziah king of Israel, who did very wickedly, to make ships to go to Tarshish.",
  judgment="At Ramoth-gilead the captains of the chariots compassed him about to fight, and he cried out, and the Lord helped him and moved them to depart from him. On his return Jehu the son of Hanani met him: Shouldest thou help the ungodly, and love them that hate the Lord? therefore is wrath upon thee from before the Lord. Of the ships, Eliezer prophesied, Because thou hast joined thyself with Ahaziah, the Lord hath broken thy works; and the ships were broken, that they were not able to go to Tarshish.",
  refs=[R("2 Chronicles",18,"1-3"),R("2 Chronicles",18,"28-34"),R("2 Chronicles",19,"1-3"),R("2 Chronicles",20,"35-37"),R("1 Kings",22,"48-49"),R("2 Corinthians",6,"14-17")],
  laws=["11C","3G","2E"], topics=["agreement","compromise","fellowship","false-brethren"], themes=["kingship","enticement","reproof","covenant"]),

 dict(slug="zedekiah-son-of-chenaanah", name="Zedekiah the son of Chenaanah, and the four hundred prophets", era="Divided Kingdom",
  charge="Prophesying victory at Ramoth-gilead by a lying spirit; smiting Micaiah on the cheek", verdict="unrecorded",
  summary="Four hundred prophets told Ahab to go up and prosper. One, Micaiah, saw the Lord on his throne and a lying spirit sent into the mouths of the rest. Zedekiah struck him for it and asked which way the Spirit had gone. The battle answered for Ahab; scripture leaves Zedekiah hiding in an inner chamber.",
  offense="Zedekiah made him horns of iron and said, Thus saith the Lord, With these shalt thou push the Syrians, until thou have consumed them; and all the prophets prophesied so. When Micaiah spoke the true word, Zedekiah went near and smote him on the cheek, and said, Which way went the Spirit of the Lord from me to speak unto thee?",
  judgment="Micaiah answered, Behold, thou shalt see in that day, when thou shalt go into an inner chamber to hide thyself. Ahab was killed by a bow drawn at a venture, and the dogs licked his blood as the true prophet had said. What became of Zedekiah in the inner chamber is not written; the law's own sentence on a prophet whose word does not come to pass is.",
  refs=[R("1 Kings",22,"6-12"),R("1 Kings",22,"19-25"),R("1 Kings",22,"29-38"),R("Deuteronomy",18,"20-22"),R("Jeremiah",23,"16-17")],
  laws=["20F","3E","4E"], topics=["false-prophets","lying","spirit-of-prophecy"], themes=["false-prophets","deceit","kingship"]),

 dict(slug="sennacherib-and-rabshakeh", name="Sennacherib and Rabshakeh", era="Divided Kingdom",
  charge="Reproaching the living God; setting him among the gods of the nations that could not save", verdict="death",
  summary="Rabshakeh stood by the conduit of the upper pool and told Jerusalem in the Jews' language that no god of any nation had ever delivered a land from the king of Assyria. Hezekiah spread the letter before the Lord. That night an angel slew a hundred and eighty-five thousand in the Assyrian camp, and Sennacherib went home to be murdered by his sons in the house of his god.",
  offense="Who are they among all the gods of the countries, that have delivered their country out of mine hand, that the Lord should deliver Jerusalem out of mine hand? Sennacherib wrote letters to rail on the Lord God of Israel, and to speak against him, saying, As the gods of the nations of other lands have not delivered their people, so shall not the God of Hezekiah deliver his people out of mine hand. Tobit, a captive in Nineveh, buried the Israelites Sennacherib slew in his rage when he came back from Judea.",
  judgment="Whom hast thou reproached and blasphemed? and against whom hast thou exalted thy voice? even against the Holy One of Israel. I will put my hook in thy nose, and my bridle in thy lips, and I will turn thee back by the way by which thou camest. The angel of the Lord went out and smote in the camp of the Assyrians an hundred fourscore and five thousand. Sennacherib returned with shame of face to Nineveh, and as he was worshipping in the house of Nisroch his god, Adrammelech and Sharezer his sons smote him with the sword.",
  refs=[R("2 Kings",18,"28-35"),R("2 Kings",19,"14-19"),R("2 Kings",19,"20-28"),R("2 Kings",19,"32-37"),R("2 Chronicles",32,"16-22"),R("Isaiah",37,"33-38"),R("Tobit",1,"18-21")],
  laws=["2K","11A","17G","2P"], topics=["the-name","our-enemies","pride","judgement-of-nations"], themes=["blasphemy","pride","war","retribution","corporate-judgment"]),

 dict(slug="shebna", name="Shebna the treasurer", era="Divided Kingdom",
  charge="Hewing himself a sepulchre on high; a shame to his lord's house", verdict="exile",
  summary="Over the house of the king in Hezekiah's day, Shebna cut himself a tomb in the rock as if Jerusalem were his to be buried in on high. Isaiah was sent to him with a sentence: the Lord would toss him like a ball into a large country and give his office to Eliakim.",
  offense="What hast thou here? and whom hast thou here, that thou hast hewed thee out a sepulchre here, as he that heweth him out a sepulchre on high, and that graveth an habitation for himself in a rock? A steward building for his own name out of the house he was set over.",
  judgment="Behold, the Lord will carry thee away with a mighty captivity, and will surely cover thee. He will surely violently turn and toss thee like a ball into a large country: there shalt thou die, and there the chariots of thy glory shall be the shame of thy lord's house. And I will drive thee from thy station, and from thy state shall he pull thee down. The key of the house of David was laid on the shoulder of Eliakim the son of Hilkiah instead. By the time Rabshakeh came, Shebna was already only the scribe.",
  refs=[R("Isaiah",22,"15-19"),R("Isaiah",22,"20-25"),R("2 Kings",18,"18"),R("Proverbs",16,"18"),R("Luke",12,"16-21")],
  laws=["17G","8A","21C"], topics=["pride","vainglory","kings-and-priests"], themes=["pride","leadership","retribution"]),

 dict(slug="amaziah-the-priest-of-bethel", name="Amaziah the priest of Bethel", era="Divided Kingdom",
  charge="Forbidding Amos to prophesy at the king's chapel; accusing him to Jeroboam of conspiracy", verdict="captivity",
  summary="A priest of the calf at Bethel sent word to Jeroboam that Amos had conspired against him, then told the prophet to go earn his bread in Judah. Amos answered that he was no prophet's son but a herdman the Lord had taken from the flock, and gave Amaziah a sentence for his wife, his children, his land and himself.",
  offense="Amaziah the priest of Bethel sent to Jeroboam king of Israel, saying, Amos hath conspired against thee in the midst of the house of Israel: the land is not able to bear all his words. Also Amaziah said unto Amos, O thou seer, go, flee thee away into the land of Judah, and there eat bread, and prophesy there: but prophesy not again any more at Bethel: for it is the king's chapel, and it is the king's court.",
  judgment="Thou sayest, Prophesy not against Israel. Therefore thus saith the Lord; Thy wife shall be an harlot in the city, and thy sons and thy daughters shall fall by the sword, and thy land shall be divided by line; and thou shalt die in a polluted land: and Israel shall surely go into captivity forth of his land.",
  refs=[R("Amos",7,"10-13"),R("Amos",7,"14-17"),R("Amos",2,"11-12"),R("1 Kings",12,"31-33"),R("2 Chronicles",36,"15-16")],
  laws=["20F","2D","3L"], topics=["false-prophets","prophets-are-israelites","persecution"], themes=["persecution","priesthood","false-prophets","captivity"]),

 dict(slug="jehoahaz-of-judah", name="Jehoahaz (Shallum) of Judah", era="Divided Kingdom",
  charge="Doing evil in the sight of the Lord according to all that his fathers had done", verdict="captivity",
  summary="Josiah's son reigned three months. Pharaoh-necho put him in bands at Riblah, laid tribute on the land, and carried him to Egypt, where he died. Jeremiah told the people to weep not for the dead Josiah but for the son who would never see his native country again.",
  offense="Jehoahaz was twenty and three years old when he began to reign; and he reigned three months in Jerusalem. And he did that which was evil in the sight of the Lord, according to all that his fathers had done. He had his father's throne and none of his father's tender heart.",
  judgment="Pharaoh-nechoh put him in bands at Riblah in the land of Hamath, that he might not reign in Jerusalem; and put the land to a tribute. Jeremiah: Weep ye not for the dead, neither bemoan him: but weep sore for him that goeth away: for he shall return no more, nor see his native country. He shall die in the place whither they have led him captive, and shall see this land no more. He is the first of the last four kings of Judah, and the first to die in exile.",
  refs=[R("2 Kings",23,"31-34"),R("Jeremiah",22,"10-12"),R("2 Chronicles",36,"1-4"),R("Ezekiel",19,"1-4"),R("Deuteronomy",28,"36")],
  laws=["2I","8A","2P"], topics=["kings-and-priests","captivity","egypt"], themes=["kingship","captivity","backsliding"]),

 dict(slug="jehoiachin", name="Jehoiachin (Coniah)", era="Divided Kingdom",
  charge="Doing evil as his father Jehoiakim had done; a signet plucked from the Lord's right hand", verdict="captivity",
  summary="Eighteen years old and three months on the throne when Nebuchadnezzar came. Jeremiah's word over him is one of the hardest in the book: though Coniah were the signet on my right hand, yet would I pluck thee thence; write ye this man childless, for no man of his seed shall prosper sitting upon the throne of David.",
  offense="Jehoiachin did that which was evil in the sight of the Lord, according to all that his father had done. He inherited Jehoiakim's throne and Jehoiakim's ways, and the wrath that had been laid up against the house.",
  judgment="I will give thee into the hand of them that seek thy life, and I will cast thee out, and thy mother that bare thee, into another country, where ye were not born; and there shall ye die. He went out to the king of Babylon with his mother, his servants, his princes and his officers, and was carried away with ten thousand captives and all the craftsmen and smiths. Thirty-seven years later Evil-merodach lifted up his head out of prison and set his throne above the kings that were with him in Babylon: a kindness, still in Babylon.",
  refs=[R("2 Kings",24,"8-16"),R("Jeremiah",22,"24-30"),R("2 Chronicles",36,"9-10"),R("2 Kings",25,"27-30"),R("Ezekiel",19,"5-9")],
  laws=["2I","8A","2P"], topics=["kings-and-priests","captivity"], themes=["kingship","captivity","corporate-judgment"]),

 dict(slug="shemaiah-the-nehelamite", name="Shemaiah the Nehelamite", era="Divided Kingdom",
  charge="Sending letters from Babylon to have Jeremiah put in prison and in the stocks; prophesying a lie", verdict="curse",
  summary="From the first captivity Shemaiah wrote to the priests in Jerusalem, naming Jeremiah a madman and asking why he had not been put in the stocks. Zephaniah the priest read the letter in Jeremiah's ears, and the answer came back to Babylon: Shemaiah would have no man to dwell among the people, and would not see the good the Lord would do.",
  offense="He sent letters in his own name to all the people at Jerusalem, and to Zephaniah the priest: The Lord hath made thee priest, that ye should be officers in the house of the Lord, for every man that is mad, and maketh himself a prophet, that thou shouldest put him in prison and in the stocks. Now therefore why hast thou not reproved Jeremiah of Anathoth? He had prophesied to the captives that the captivity would be long, and taught them to trust in a lie.",
  judgment="Because that Shemaiah hath prophesied unto you, and I sent him not, and he caused you to trust in a lie: therefore thus saith the Lord; Behold, I will punish Shemaiah the Nehelamite, and his seed: he shall not have a man to dwell among this people; neither shall he behold the good that I will do for my people, because he hath taught rebellion against the Lord.",
  refs=[R("Jeremiah",29,"24-29"),R("Jeremiah",29,"30-32"),R("Jeremiah",29,"8-9"),R("Jeremiah",20,"1-2"),R("Deuteronomy",13,"5")],
  laws=["20F","3E","3L"], topics=["false-prophets","persecution","lying"], themes=["false-prophets","persecution","deceit"]),

 dict(slug="ahab-and-zedekiah-in-babylon", name="Ahab the son of Kolaiah and Zedekiah the son of Maaseiah", era="Divided Kingdom",
  charge="Prophesying lies in the Lord's name to the captives; committing adultery with their neighbours' wives", verdict="death",
  summary="Two prophets among the exiles told the captives the exile would be short. The Lord's letter by Jeremiah named them, named their adultery, and named their end: roasted in the fire by the king of Babylon, and their names turned into a curse.",
  offense="They have committed villany in Israel, and have committed adultery with their neighbours' wives, and have spoken lying words in my name, which I have not commanded them; even I know, and am a witness, saith the Lord.",
  judgment="Thus saith the Lord of hosts, the God of Israel, of Ahab the son of Kolaiah, and of Zedekiah the son of Maaseiah, which prophesy a lie unto you in my name; Behold, I will deliver them into the hand of Nebuchadrezzar king of Babylon; and he shall slay them before your eyes; and of them shall be taken up a curse by all the captivity of Judah which are in Babylon, saying, The Lord make thee like Zedekiah and like Ahab, whom the king of Babylon roasted in the fire.",
  refs=[R("Jeremiah",29,"20-23"),R("Jeremiah",29,"8-9"),R("Jeremiah",23,"14"),R("Deuteronomy",18,"20"),R("Leviticus",20,"10")],
  laws=["20F","5D","3E"], topics=["false-prophets","adultery","lying"], themes=["false-prophets","sexual-immorality","deceit","retribution"]),

 dict(slug="ishmael-the-son-of-nethaniah", name="Ishmael the son of Nethaniah", era="Divided Kingdom",
  charge="Murder of Gedaliah the governor at his own table; slaughter of the Jews and Chaldeans with him, and of seventy pilgrims", verdict="unrecorded",
  summary="Of the seed royal, hired by the king of the Ammonites, Ishmael ate bread with Gedaliah at Mizpah and killed him, then killed the men with him, then killed seventy mourners on their way to the house of the Lord and threw them in a pit. He escaped to Ammon with eight men. Scripture records no sentence on him; it records what his deed cost the remnant.",
  offense="Johanan had warned Gedaliah that Baalis king of the Ammonites had sent Ishmael to slay him, and Gedaliah believed him not. Ishmael came with ten men and they did eat bread together in Mizpah, and there he smote Gedaliah with the sword, and slew him whom the king of Babylon had made governor. Fourscore men came from Shechem, Shiloh and Samaria with offerings; he went out weeping to meet them and slew them and cast them into the pit, sparing ten for their hidden treasures.",
  judgment="Johanan recovered the captives at the great waters of Gibeon, but Ishmael escaped from Johanan and went to the Ammonites. No court reached him and no plague is written. What the deed left behind was a remnant so afraid of the Chaldeans that they fled to Egypt against the word of the Lord, and died there. The law's sentence on the murderer stands written where he cannot flee it.",
  refs=[R("Jeremiah",40,"13-16"),R("Jeremiah",41,"1-3"),R("Jeremiah",41,"4-10"),R("Jeremiah",41,"11-18"),R("2 Kings",25,"25-26"),R("Genesis",9,"6")],
  laws=["10A","3J","15A"], topics=["murder","honest","strangers"], themes=["murder","deceit","rebellion","violence"]),

 dict(slug="the-remnant-that-went-down-to-egypt", name="Johanan and the remnant that went down to Egypt", era="Divided Kingdom",
  charge="Asking the word of the Lord, swearing to obey it, and refusing it; burning incense to the queen of heaven in Egypt", verdict="death",
  summary="The remnant asked Jeremiah to pray for direction and swore to obey whatever the Lord said. Ten days later the answer came: stay in the land and I will build you; go to Egypt and the sword you fear will overtake you there. They called the prophet a liar, took him with them to Egypt, and there openly returned to the queen of heaven.",
  offense="Ye dissembled in your hearts, when ye sent me unto the Lord your God, saying, Pray for us unto the Lord our God; and according unto all that the Lord our God shall say, so declare unto us, and we will do it. In Egypt the men who knew their wives burned incense to other gods answered Jeremiah: we will certainly do whatsoever thing goeth forth out of our own mouth, to burn incense unto the queen of heaven, as we did in the cities of Judah; for then had we plenty of victuals.",
  judgment="Then it shall come to pass, that the sword, which ye feared, shall overtake you there in the land of Egypt, and the famine, whereof ye were afraid, shall follow close after you there in Egypt; and there ye shall die. I will take the remnant of Judah, that have set their faces to go into the land of Egypt, and they shall all be consumed, and fall in the land of Egypt; none shall return but such as shall escape. The sign given was Pharaoh-hophra delivered into the hand of his enemies, as Zedekiah had been.",
  refs=[R("Jeremiah",42,"1-6"),R("Jeremiah",42,"13-22"),R("Jeremiah",43,"1-7"),R("Jeremiah",44,"15-19"),R("Jeremiah",44,"24-30"),R("Isaiah",30,"1-3")],
  laws=["2H","2D","4D","11C"], topics=["obedience","egypt","other-gods","agreement"], themes=["disobedience","idolatry","corporate-judgment","rebellion","deceit"]),

 dict(slug="moab-and-ammon", name="Moab and Ammon", era="Divided Kingdom",
  charge="Magnifying themselves against the Lord and against his people; rejoicing over the sanctuary when it was profaned", verdict="captivity",
  summary="Lot's two sons, neighbours to Israel from the wilderness on, are judged in Isaiah, Jeremiah, Ezekiel, Amos and Zephaniah for one long habit: pride against the Lord and gladness at Judah's ruin. Ammon ripped up the women with child of Gilead to enlarge its border; Moab said, Aha, against the house of Judah.",
  offense="We have heard of the pride of Moab; he is very proud: of his loftiness, and his arrogancy, and his pride, and the haughtiness of his heart. He shall be no more praised, because he hath magnified himself against the Lord. Of Ammon: because thou saidst, Aha, against my sanctuary, when it was profaned; and against the land of Israel, when it was desolate; and against the house of Judah, when they went into captivity. Amos: they have ripped up the women with child of Gilead, that they might enlarge their border.",
  judgment="Moab shall be destroyed from being a people, because he hath magnified himself against the Lord. Yet will I bring again the captivity of Moab in the latter days. Of Ammon: I will deliver thee to the men of the east for a possession, and Rabbah shall be a stable for camels; Zephaniah: Moab shall be as Sodom, and the children of Ammon as Gomorrah, even the breeding of nettles, and saltpits, and a perpetual desolation. Nebuchadnezzar came through both.",
  refs=[R("Jeremiah",48,"26-30"),R("Jeremiah",48,"42-47"),R("Ezekiel",25,"1-11"),R("Amos",1,"13-15"),R("Amos",2,"1-3"),R("Zephaniah",2,"8-11"),R("Isaiah",16,"6-7"),R("Deuteronomy",23,"3-4")],
  laws=["17G","11A","2K"], topics=["judgement-of-nations","pride","our-enemies"], themes=["pride","corporate-judgment","captivity","retribution"]),

 dict(slug="pharaoh-hophra-and-egypt", name="Pharaoh-hophra and Egypt", era="Divided Kingdom",
  charge="Saying, My river is mine own, and I have made it for myself; a staff of reed to the house of Israel", verdict="captivity",
  summary="Judah leaned on Egypt against Babylon, and Egypt broke under the hand like a reed and ran into it. Ezekiel's word against Pharaoh is against the boast of ownership: the river was his, he had made it. Forty years of desolation were decreed, and Egypt was to be the basest of kingdoms afterward.",
  offense="Behold, I am against thee, Pharaoh king of Egypt, the great dragon that lieth in the midst of his rivers, which hath said, My river is mine own, and I have made it for myself. Because they have been a staff of reed to the house of Israel: when they took hold of thee by thy hand, thou didst break, and rend all their shoulder; and when they leaned upon thee, thou brakest, and madest all their loins to be at a stand.",
  judgment="I will give Pharaoh-hophra king of Egypt into the hand of his enemies, and into the hand of them that seek his life; as I gave Zedekiah king of Judah into the hand of Nebuchadrezzar. The land of Egypt shall be desolate and waste forty years; I will scatter the Egyptians among the nations. At the end of forty years I will gather the Egyptians, and they shall be there a base kingdom; it shall be the basest of the kingdoms; neither shall it exalt itself any more above the nations.",
  refs=[R("Ezekiel",29,"1-7"),R("Ezekiel",29,"8-16"),R("Jeremiah",44,"30"),R("Jeremiah",46,"25-26"),R("Isaiah",31,"1-3"),R("Ezekiel",30,"20-26")],
  laws=["17G","11C","2K"], topics=["egypt","judgement-of-nations","pride","trust-god"], themes=["pride","corporate-judgment","captivity","war"]),

 dict(slug="babylon-the-lady-of-kingdoms", name="Babylon, the lady of kingdoms", era="Divided Kingdom",
  charge="Showing no mercy to the captives; saying, I am, and none else beside me; trusting in her sorceries", verdict="curse",
  summary="Babylon was the Lord's hammer against Judah, and was judged for how she swung it: without mercy, laying a heavy yoke on the ancient, and saying in her heart, I shall be a lady for ever. Isaiah and Jeremiah both name the end before the beginning: the Medes, the sudden fall, the perpetual desolation.",
  offense="I was wroth with my people, I have polluted mine inheritance, and given them into thine hand: thou didst shew them no mercy; upon the ancient hast thou very heavily laid thy yoke. And thou saidst, I shall be a lady for ever. Thou hast trusted in thy wickedness: thou hast said, None seeth me. Thy wisdom and thy knowledge, it hath perverted thee; and thou hast said in thine heart, I am, and none else beside me. Jeremiah adds the account: they have devoured Israel; the violence done to me and to my flesh be upon Babylon, shall the inhabitant of Zion say.",
  judgment="Therefore shall evil come upon thee; thou shalt not know from whence it riseth. Come down, and sit in the dust, O virgin daughter of Babylon. Behold, I will stir up the Medes against them. Babylon, the glory of kingdoms, the beauty of the Chaldees' excellency, shall be as when God overthrew Sodom and Gomorrah; it shall never be inhabited. Belshazzar saw the hand write it on the wall the night it came.",
  refs=[R("Isaiah",47,"5-11"),R("Isaiah",13,"17-22"),R("Isaiah",14,"4-15"),R("Jeremiah",50,"29-32"),R("Jeremiah",51,"24-26"),R("Jeremiah",51,"34-36"),R("Habakkuk",2,"6-8"),R("Revelation",18,"7-8")],
  laws=["17G","10D","3K","2K"], topics=["daughter-of-babylon","pride","judgement-of-nations","divination"], themes=["pride","corporate-judgment","oppression","occult","retribution"]),

 # ---------------- Exile and Return ----------------
 dict(slug="bigthan-and-teresh", name="Bigthan and Teresh", era="Exile and Return",
  charge="Conspiring to lay hands on king Ahasuerus", verdict="death",
  summary="Two chamberlains who kept the door were wroth and sought to lay hand on the king. Mordecai heard of it and told Esther, who told the king in Mordecai's name. They were hanged, and the thing was written in the chronicles, where a sleepless king found it years later on the night before Haman meant to hang Mordecai.",
  offense="In those days, while Mordecai sat in the king's gate, two of the king's chamberlains, Bigthan and Teresh, of those which kept the door, were wroth, and sought to lay hand on the king Ahasuerus.",
  judgment="The thing was known to Mordecai, who told it unto Esther the queen; and Esther certified the king thereof in Mordecai's name. And when inquisition was made of the matter, it was found out; therefore they were both hanged on a tree: and it was written in the book of the chronicles before the king. The record of their sentence became the instrument of Haman's.",
  refs=[R("Esther",2,"21-23"),R("Esther",6,"1-3"),R("Esther",6,"10-11"),R("Romans",13,"1-2"),R("Ecclesiastes",10,"20")],
  laws=["8D","10A","10G"], topics=["murder","submission","kings-and-priests"], themes=["murder","rebellion","kingship","retribution"]),

 dict(slug="the-adversaries-of-judah-and-benjamin", name="The adversaries of Judah and Benjamin", era="Exile and Return",
  charge="Weakening the hands of the people; hiring counsellors against them to frustrate the building of the house of God", verdict="unrecorded",
  summary="The people of the land offered to help build the temple and were refused, and turned to hindrance: hired counsellors, letters to Artaxerxes, and a stop-work order enforced by force and power. The work lay still until the second year of Darius, whose decree turned the tables: whoever altered it would be hanged on timber from his own house.",
  offense="The people of the land weakened the hands of the people of Judah, and troubled them in building, and hired counsellors against them, to frustrate their purpose, all the days of Cyrus king of Persia, even until the reign of Darius. Rehum and Shimshai wrote to Artaxerxes that Jerusalem was the rebellious and the bad city, and the king's answer was used to make them cease by force and power.",
  judgment="Scripture records no sentence on the adversaries themselves. What it records is Darius's decree: let the work of this house of God alone; whosoever shall alter this word, let timber be pulled down from his house, and being set up, let him be hanged thereon; and let his house be made a dunghill for this. Tatnai and his companions did speedily as the king sent, and the elders of the Jews builded and prospered through the prophesying of Haggai and Zechariah.",
  refs=[R("Ezra",4,"1-5"),R("Ezra",4,"11-16"),R("Ezra",4,"23-24"),R("Ezra",6,"6-12"),R("Ezra",6,"13-15"),R("Nehemiah",4,"1-6")],
  laws=["3F","3J","13D"], topics=["our-enemies","persecution","false-brethren"], themes=["persecution","deceit","oppression"]),

 # ---------------- Second Temple ----------------
 dict(slug="apollonius", name="Apollonius", era="Second Temple (Apocrypha)",
  charge="Falling upon Jerusalem on the Sabbath under a pretence of peace; slaying a great multitude; taking women and children captive", verdict="death",
  summary="Sent by Antiochus with twenty-two thousand men, Apollonius spoke peaceable words to Jerusalem, waited for the Sabbath when the people would not fight, and slew them going out to see the show. Judas Maccabeus met him in the field, killed him, and carried his sword for the rest of his life.",
  offense="He came to Jerusalem, and speaking peaceable words unto them, but all was deceit: for when they had given him credence, he fell suddenly upon the city, and smote it very sore, and destroyed much people of Israel. He took the spoils of the city, set it on fire, and pulled down the houses and walls round about. He commanded his men to arm themselves, and to slay all those that went out to see the holy Sabbath, and there were slain great multitudes.",
  judgment="Judas gathered those that were willing, and Apollonius gathered the Gentiles together, and a great host out of Samaria, to fight against Israel. Judas perceived it, and went forth to meet him, and so he smote him, and slew him: many also fell down slain, but the rest fled. Wherefore Judas took their spoils, and Apollonius' sword also, and therewith he fought all his life long.",
  refs=[R("1 Maccabees",1,"29-40"),R("2 Maccabees",5,"24-26"),R("1 Maccabees",3,"10-12"),R("Exodus",31,"14"),R("Psalms",55,"21")],
  laws=["10B","22A","3J","11A"], topics=["sabbath","our-enemies","persecution"], themes=["sabbath","persecution","deceit","war","retribution"]),

 dict(slug="timotheus", name="Timotheus", era="Second Temple (Apocrypha)",
  charge="Gathering the heathen to root out the Jews; a second campaign after being once spared", verdict="death",
  summary="Timotheus raised the Ammonites and Arabians against the returned Jews, was beaten at the river and shut up in Gazara, and was let go alive when he pleaded his hostages. He came again with a hundred and twenty thousand, and Judas's men found him hid in a pit and slew him.",
  offense="Timotheus, whom the Jews had overcome before, when he had gathered a great multitude of foreign forces, and horses out of Asia not a few, came as though he would take Jewry by force of arms. He had boasted over the Jews and blasphemed, and the Jews would not spare his men who had provoked them.",
  judgment="Judas and his company, calling upon the Lord, came to the Jews' ease: Timotheus and his host were overthrown at Raphon and thirty thousand slain. Timotheus fell into the hands of Dositheus and Sosipater, whom he besought with much craft to let him go with his life, and they let him go for the saving of their brethren. At last, in the second campaign, he fled to Gazara, and Judas's men, finding Timotheus hid in a certain pit, killed him and his brother Chereas, and Apollophanes.",
  refs=[R("2 Maccabees",10,"24-38"),R("2 Maccabees",12,"2"),R("2 Maccabees",12,"20-25"),R("1 Maccabees",5,"37-44"),R("Psalms",9,"15-16")],
  laws=["11A","22A","22D"], topics=["our-enemies","persecution","judgement-of-nations"], themes=["persecution","war","retribution"]),

 dict(slug="simon-the-governor-of-the-temple", name="Simon the governor of the temple", era="Second Temple (Apocrypha)",
  charge="Betraying the temple treasury to the king out of a private quarrel; slandering Onias the high priest", verdict="unrecorded",
  summary="Falling out with Onias over the market of the city, Simon of the tribe of Benjamin told the governor of Coelosyria that the treasury at Jerusalem was full of infinite sums and could be brought under the king's power. That report sent Heliodorus. When it failed, Simon slandered Onias as the author of the mischief and had a man of his party commit murders.",
  offense="Simon of the tribe of Benjamin, who was made governor of the temple, fell out with the high priest about disorder in the city. When he could not overcome Onias, he went to Apollonius the son of Thraseas and told him that the treasury in Jerusalem was full of infinite sums of money. Afterward he slandered Onias, as if he had terrified Heliodorus and been the worker of these evils, and so proceeded in his malice that murders were committed by one Apollonius, a furious man.",
  judgment="Onias went to the king, not to be an accuser of his countrymen, but seeking the good of all. Scripture does not record Simon's end; it records that his brother Menelaus bought the priesthood with the same appetite, and how that ended. The law's word on the man who takes a bribe against the innocent, and on the false accuser, stands over him unrecorded.",
  refs=[R("2 Maccabees",3,"4-8"),R("2 Maccabees",4,"1-6"),R("2 Maccabees",4,"23"),R("Exodus",23,"1"),R("Deuteronomy",27,"25")],
  laws=["4E","4C","12E","20F"], topics=["false-brethren","witnesses","money"], themes=["deceit","false-witness","priesthood","covetousness"]),

 dict(slug="tryphon", name="Tryphon", era="Second Temple (Apocrypha)",
  charge="Taking Jonathan the high priest by treachery under a covenant of friendship; slaying him and the young king Antiochus", verdict="unrecorded",
  summary="Tryphon set up a boy king to reach the crown himself, feared Jonathan would not suffer it, and took him at Ptolemais with fair words and a thousand men, killing the rest. He took Jonathan's sons as hostages, took a hundred talents for his release, kept both, and killed Jonathan on the way home. Then he killed the boy.",
  offense="Tryphon went forth to deceive Jonathan: he said, Why hast thou brought all this people to so much trouble? Send them home, and choose a few men to wait on thee, and come thou with me to Ptolemais. When Jonathan entered, they of Ptolemais shut the gates and took him, and all them that came with him they slew with the sword. Afterward he sought to slay Simon's men as well, and having deceived Simon of the hundred talents and the children, went and slew Jonathan at Bascama.",
  judgment="Tryphon dealt deceitfully with the young king Antiochus and slew him, and reigned in his stead, and brought a great calamity upon the land. Scripture records his crown, not his sentence: Antiochus the son of Demetrius came against him, the men of war forsook him, he fled by ship to Orthosias, and the book leaves him running. The law's sentence on the murderer and on the man who breaks a covenant of peace is written elsewhere and does not run out.",
  refs=[R("1 Maccabees",12,"39-48"),R("1 Maccabees",13,"12-24"),R("1 Maccabees",13,"31-32"),R("1 Maccabees",15,"10-14"),R("1 Maccabees",15,"37"),R("Psalms",55,"20-23")],
  laws=["10A","3J","4D","10G"], topics=["murder","honest","agreement"], themes=["murder","deceit","rebellion","kingship"]),

 dict(slug="ptolemy-the-son-of-abubus", name="Ptolemy the son of Abubus", era="Second Temple (Apocrypha)",
  charge="Murdering Simon the high priest and two of his sons at a banquet in his own castle", verdict="unrecorded",
  summary="Simon's son in law, captain of the plain of Jericho, wanted the country and the crown. He received Simon and his sons Mattathias and Judas in the castle of Docus, made them a great banquet, and killed them when they had drunk well. He sent men to kill John Hircanus too; John was told first and killed the messengers.",
  offense="Ptolemeus the son of Abubus, being made captain in the plain of Jericho, had abundance of silver and gold, for he was the high priest's son in law. Wherefore his heart being lifted up, he thought to get the country to himself, and thereupon consulted deceitfully against Simon and his sons to destroy them. When Simon and his sons had drunk largely, Ptolemee and his men rose up, and took their weapons, and came upon Simon into the banqueting place, and slew him and his two sons.",
  judgment="In which doing he committed a great treachery, and recompensed evil for good. He wrote to the king to send him an host and deliver him the country, and sent others to take Jerusalem. One ran before to Gazara and told John that his father and brethren were slain, and he laid hands on them that came to destroy him, and slew them. The first book of the Maccabees ends there; the murderer's sentence is not in it. Deuteronomy's is.",
  refs=[R("1 Maccabees",16,"11-17"),R("1 Maccabees",16,"18-22"),R("Deuteronomy",27,"24-25"),R("Proverbs",17,"13"),R("Psalms",41,"9")],
  laws=["10A","3J","15A","17C"], topics=["murder","honest","covet"], themes=["murder","deceit","covetousness","treason"]),

 # ---------------- Gospels ----------------
 dict(slug="zacharias-struck-dumb", name="Zacharias", era="Gospels",
  charge="Not believing the words of the angel Gabriel, and asking for a sign", verdict="temporal",
  summary="A righteous priest, walking in all the commandments blameless, was told at the altar of incense that his prayer was heard. He answered that he was old and his wife well stricken in years. He came out of the temple unable to speak, and stayed so until the day he wrote, His name is John.",
  offense="Zacharias said unto the angel, Whereby shall I know this? for I am an old man, and my wife well stricken in years. The angel answering said, I am Gabriel, that stand in the presence of God; and am sent to speak unto thee, and to shew thee these glad tidings.",
  judgment="And, behold, thou shalt be dumb, and not able to speak, until the day that these things shall be performed, because thou believest not my words, which shall be fulfilled in their season. The judgment was bounded exactly to the promise: when the child was circumcised and named, his mouth was opened immediately, and his tongue loosed, and he spake, and praised God.",
  refs=[R("Luke",1,"5-7"),R("Luke",1,"11-17"),R("Luke",1,"18-22"),R("Luke",1,"57-66"),R("Luke",1,"67-79"),R("Mark",11,"22-24")],
  laws=["2B","2P","20B"], topics=["believe","no-sign","prayer"], themes=["irreverence","reproof","mercy","priesthood"]),

 dict(slug="chorazin-bethsaida-and-capernaum", name="Chorazin, Bethsaida, and Capernaum", era="Gospels",
  charge="Not repenting after the mighty works done in them", verdict="curse",
  summary="Most of Christ's miracles were done in three towns on the north shore of Galilee, and they did not repent. He measured them against Tyre, Sidon and Sodom and found them worse off in the judgment, because more had been shown them. Capernaum, exalted unto heaven, was to be brought down to hell.",
  offense="Then began he to upbraid the cities wherein most of his mighty works were done, because they repented not. If the mighty works, which were done in you, had been done in Tyre and Sidon, they would have repented long ago in sackcloth and ashes. Capernaum had heard the sermon in the synagogue, seen the centurion's servant healed and the paralytic carried down through the roof, and stayed as it was.",
  judgment="Woe unto thee, Chorazin! woe unto thee, Bethsaida! It shall be more tolerable for Tyre and Sidon at the day of judgment, than for you. And thou, Capernaum, which art exalted unto heaven, shalt be brought down to hell: for if the mighty works, which have been done in thee, had been done in Sodom, it would have remained until this day. It shall be more tolerable for the land of Sodom in the day of judgment, than for thee.",
  refs=[R("Matthew",11,"20-24"),R("Luke",10,"13-16"),R("Matthew",4,"13-17"),R("John",15,"22-24"),R("Hebrews",2,"1-3")],
  laws=["2L","2B","2P"], topics=["repentance","christ-rejected","judgement"], themes=["corporate-judgment","repentance","irreverence","christ-rejected"]),

 dict(slug="nazareth", name="Nazareth, his own country", era="Gospels",
  charge="Being offended at him; seeking to cast him down the hill", verdict="temporal",
  summary="In the synagogue where he had been brought up he read Isaiah and said the scripture was fulfilled that day. They marvelled, then asked if this was not the carpenter's son, then were filled with wrath and led him to the brow of the hill. He did no mighty work there, and passed through the midst of them.",
  offense="Is not this the carpenter, the son of Mary? And they were offended at him. When he reminded them that Elijah was sent to a widow of Sidon and Elisha cleansed a Syrian, all they in the synagogue were filled with wrath, and rose up, and thrust him out of the city, and led him unto the brow of the hill whereon their city was built, that they might cast him down headlong.",
  judgment="A prophet is not without honour, save in his own country, and in his own house. And he did not many mighty works there because of their unbelief; he could there do no mighty work, save that he laid his hands upon a few sick folk, and healed them; and he marvelled because of their unbelief. He passing through the midst of them went his way, and Nazareth kept what it had chosen: a carpenter's son and no miracles.",
  refs=[R("Luke",4,"16-21"),R("Luke",4,"22-30"),R("Mark",6,"1-6"),R("Matthew",13,"53-58"),R("John",1,"11"),R("John",7,"5")],
  laws=["2B","2K","2H"], topics=["believe","christ-rejected","honour"], themes=["irreverence","christ-rejected","corporate-judgment","violence"]),

 dict(slug="the-scribes-and-pharisees", name="The scribes and Pharisees", era="Gospels",
  charge="Shutting up the kingdom against men; devouring widows' houses; tithing mint and omitting judgment, mercy and faith; whited sepulchres", verdict="curse",
  summary="They sat in Moses' seat and were to be heard; their works were not to be followed. Eight woes in Matthew 23 name the crimes, and the sentence at the end gathers all the righteous blood from Abel to Zacharias on that generation: your house is left unto you desolate.",
  offense="They bind heavy burdens and grievous to be borne, and lay them on men's shoulders; but they themselves will not move them with one of their fingers. Ye shut up the kingdom of heaven against men. Ye devour widows' houses, and for a pretence make long prayer. Ye pay tithe of mint and anise and cummin, and have omitted the weightier matters of the law, judgment, mercy, and faith. Ye are like unto whited sepulchres, which indeed appear beautiful outward, but are within full of dead men's bones. Ye are the children of them which killed the prophets.",
  judgment="Ye serpents, ye generation of vipers, how can ye escape the damnation of hell? Behold, I send unto you prophets, and wise men, and scribes: and some of them ye shall kill and crucify; that upon you may come all the righteous blood shed upon the earth, from the blood of righteous Abel unto the blood of Zacharias. Verily I say unto you, All these things shall come upon this generation. Behold, your house is left unto you desolate. Forty years later the house was.",
  refs=[R("Matthew",23,"1-4"),R("Matthew",23,"13-15"),R("Matthew",23,"23-28"),R("Matthew",23,"29-36"),R("Matthew",23,"37-39"),R("Luke",11,"39-52"),R("Isaiah",29,"13-14")],
  laws=["17K","15C","20A","4F","19B"], topics=["whitewashing","traditions-of-men","kings-and-priests","tithes-are-not-money","justice"], themes=["priesthood","pride","oppression","persecution","corporate-judgment","hypocrisy"]),

 dict(slug="the-samaritan-village-and-the-sons-of-thunder", name="The Samaritan village, and the sons of thunder", era="Gospels",
  charge="Refusing to receive him because his face was toward Jerusalem; James and John asking for fire from heaven", verdict="spared",
  summary="A village of Samaria would not take him in, and James and John asked leave to call down fire as Elias did. He rebuked them, not the village: ye know not what manner of spirit ye are of; the Son of man is not come to destroy men's lives, but to save them. They went to another village.",
  offense="They did not receive him, because his face was as though he would go to Jerusalem. And when his disciples James and John saw this, they said, Lord, wilt thou that we command fire to come down from heaven, and consume them, even as Elias did?",
  judgment="He turned, and rebuked them, and said, Ye know not what manner of spirit ye are of. For the Son of man is not come to destroy men's lives, but to save them. And they went to another village. The village was spared a sentence, and the disciples were taught the difference between Elijah's day and theirs; one of those two sons of thunder later went down to Samaria with Peter to lay hands on believers there.",
  refs=[R("Luke",9,"51-56"),R("2 Kings",1,"9-12"),R("John",3,"17"),R("Acts",8,"14-17"),R("Matthew",10,"14-15")],
  laws=["15A","3K","17A","22D"], topics=["strangers","mercy","anger"], themes=["mercy","reproof","hatred"]),

 # ---------------- Apostolic ----------------
 dict(slug="ananias-the-high-priest", name="Ananias the high priest", era="Apostolic",
  charge="Commanding Paul to be smitten on the mouth, contrary to the law, while sitting to judge him by the law", verdict="curse",
  summary="Paul had said one sentence to the council when the high priest ordered him struck. Paul answered as a prophet answers: God shall smite thee, thou whited wall; for sittest thou to judge me after the law, and commandest me to be smitten contrary to the law? Then he withdrew the words toward the office, not the man.",
  offense="Paul, earnestly beholding the council, said, Men and brethren, I have lived in all good conscience before God until this day. And the high priest Ananias commanded them that stood by him to smite him on the mouth. The law forbids condemning a man before he is heard, and forbids the judge to strike the accused; Ananias did both from the judgment seat.",
  judgment="Then said Paul unto him, God shall smite thee, thou whited wall. Told it was the high priest, he answered, I wist not, brethren, that he was the high priest: for it is written, Thou shalt not speak evil of the ruler of thy people. Scripture records the word spoken and not its performance; the office was honoured, the man was named, and the sentence was left with God.",
  refs=[R("Acts",23,"1-5"),R("Acts",24,"1"),R("Deuteronomy",25,"1-2"),R("John",7,"51"),R("Exodus",22,"28"),R("Ezekiel",13,"10-15")],
  laws=["19A","4F","8D","17K"], topics=["justice","judging","kings-and-priests"], themes=["priesthood","partiality","hypocrisy","persecution"]),

 dict(slug="alexander-the-coppersmith", name="Alexander the coppersmith", era="Apostolic",
  charge="Doing Paul much evil; greatly withstanding his words", verdict="curse",
  summary="Named in Paul's last letter as a man to beware of. Whether he is the Alexander delivered to Satan with Hymenaeus for blasphemy, or the Alexander the Jews put forward in the Ephesian theatre, the sentence Paul leaves is the law's own: the Lord reward him according to his works.",
  offense="Alexander the coppersmith did me much evil: of whom be thou ware also; for he hath greatly withstood our words. In the first letter to Timothy, Hymenaeus and Alexander had put away faith and a good conscience and made shipwreck, and were delivered unto Satan that they might learn not to blaspheme.",
  judgment="The Lord reward him according to his works. Paul does not curse him in his own name; he cites the judgment already written for every man, and leaves Alexander under it. Timothy was told to beware of him, which is the church's share of the sentence: a man marked and avoided.",
  refs=[R("2 Timothy",4,"14-15"),R("1 Timothy",1,"18-20"),R("Acts",19,"33-34"),R("Psalms",62,"12"),R("Romans",12,"19"),R("Romans",16,"17")],
  laws=["3F","3I","20F"], topics=["persecution","false-brethren","our-enemies"], themes=["persecution","retribution","false-brethren"]),

 dict(slug="demas", name="Demas", era="Apostolic",
  charge="Forsaking Paul, having loved this present world", verdict="unrecorded",
  summary="Three times Demas appears in Paul's letters: a fellowlabourer sending greetings from Rome, then a name without a word, then a name with a verdict. Demas hath forsaken me, having loved this present world, and is departed unto Thessalonica. Scripture says nothing more of him.",
  offense="He had stood with Paul in the first imprisonment, named with Luke among the fellowlabourers. In the second, with Paul's death near, he loved this present world and went to Thessalonica. The love of the world is named by John as the thing that cannot share a heart with the love of the Father.",
  judgment="No sentence is written; the departure is the record. The law's word on the man who puts his hand to the plough and looks back, and the apostle's on the friendship of the world, stand over the empty place where his name had been. Whether he came back is not told.",
  refs=[R("2 Timothy",4,"9-10"),R("Colossians",4,"14"),R("Philemon",1,"23-24"),R("1 John",2,"15-17"),R("James",4,"4"),R("Luke",9,"62")],
  laws=["2I","2E","17H"], topics=["compromise","affections","world"], themes=["backsliding","covetousness","negligence"]),

 dict(slug="ephesus-sardis-and-laodicea", name="The churches of Ephesus, Sardis, and Laodicea", era="Apostolic",
  charge="Leaving the first love; a name to live while dead; lukewarm, and saying, I am rich", verdict="reprieve",
  summary="Three of the seven letters in the Revelation carry a sentence with a condition. Ephesus, sound in doctrine and patient, had left her first love and would lose her candlestick. Sardis had a name that it lived and was dead. Laodicea was neither cold nor hot, and was about to be spued out. Each was told what to do, and given time.",
  offense="Ephesus: I have somewhat against thee, because thou hast left thy first love. Sardis: thou hast a name that thou livest, and art dead; I have not found thy works perfect before God. Laodicea: thou art lukewarm, and neither cold nor hot; thou sayest, I am rich, and increased with goods, and have need of nothing; and knowest not that thou art wretched, and miserable, and poor, and blind, and naked.",
  judgment="Remember therefore from whence thou art fallen, and repent, and do the first works; or else I will come unto thee quickly, and will remove thy candlestick out of his place, except thou repent. If therefore thou shalt not watch, I will come on thee as a thief. I will spue thee out of my mouth. As many as I love, I rebuke and chasten: be zealous therefore, and repent. Behold, I stand at the door, and knock. The sentence is written in full and stayed on the condition.",
  refs=[R("Revelation",2,"1-7"),R("Revelation",3,"1-6"),R("Revelation",3,"14-22"),R("Jeremiah",2,"2-5"),R("Hebrews",12,"5-11")],
  laws=["2E","2I","2L","17D"], topics=["repentance","love","compromise","vainglory"], themes=["backsliding","repentance","reproof","pride","mercy"]),
]
