from cases_lib import R

CASES = [
 {
  "slug": "herod-the-great",
  "name": "Herod the Great and the children of Bethlehem",
  "era": "Gospels",
  "charge": "Slaying all the male children of Bethlehem from two years old and under",
  "verdict": "unrecorded",
  "summary": "Mocked by the wise men who did not return to report the child, Herod was exceeding wroth and sent and slew all the children in Bethlehem and its coasts from two years old and under, according to the time he had inquired of them. Matthew hears Rachel weeping in Ramah.",
  "offense": "Innocent blood on a scale of a town, from a king's fear for his throne. The children's only crime was their age and their address.",
  "judgment": "Matthew records only that Herod died and Joseph brought the child back from Egypt. Scripture pronounces no sentence on him; secular history records a hideous death. The law's word on innocent blood stands over the case regardless.",
  "refs": R("Matthew 2:13", "Matthew 2:16-18", "Matthew 2:19-20", "Jeremiah 31:15", "Deuteronomy 27:25", "Proverbs 6:16-17"),
  "laws": ["10A.2", "10A.4", "8A.6", "8A.24"],
  "topics": ["murder", "persecution", "christ"],
  "themes": ["murder", "persecution", "kingship"],
 },
 {
  "slug": "herod-antipas",
  "name": "Herod Antipas and Herodias",
  "era": "Gospels",
  "charge": "Taking his brother's wife; beheading John for saying so",
  "verdict": "unrecorded",
  "summary": "Herod the tetrarch married Herodias, his brother Philip's wife, and John told him it was not lawful. Herodias wanted John dead; Herod feared him and heard him gladly, but at his birthday feast swore to give her dancing daughter whatever she asked. She asked for John's head on a charger.",
  "offense": "Leviticus twice: thou shalt not uncover the nakedness of thy brother's wife. Then a rash oath kept at the cost of a prophet's life, for the sake of them which sat with him. Christ called him that fox and would not answer him at his trial.",
  "judgment": "Scripture records no sentence on Herod or Herodias; the gospels leave them at Christ's trial, mocking him. History records Antipas exiled by Caligula at his wife's ambition. The record here is the crime and the statute.",
  "refs": R("Mark 6:17-28", "Matthew 14:3-11", "Luke 3:19-20", "Luke 13:31-32", "Luke 23:8-12", "Leviticus 18:16", "Leviticus 20:21"),
  "laws": ["5G.8", "10A.2", "4D.16", "4D.14", "8A.24", "10A.7"],
  "topics": ["marriage", "persecution", "agreement", "peer-pressure"],
  "themes": ["sexual-immorality", "murder", "vows", "persecution"],
 },
 {
  "slug": "the-traders-in-the-temple",
  "name": "The traders in the temple",
  "era": "Gospels",
  "charge": "Making the house of prayer a den of thieves",
  "verdict": "temporal",
  "summary": "Twice Christ found the temple court full of those that sold oxen, sheep, and doves, and the changers of money sitting. He made a scourge of small cords, drove them out, poured out the changers' money, overthrew the tables, and would not suffer any man to carry a vessel through the temple.",
  "offense": "Isaiah had called it a house of prayer for all people; Jeremiah had asked, is this house become a den of robbers in your eyes? The trade occupied the court of the Gentiles, the only place the nations could pray, and did it, on the gospel's account, for profit under the priests' patronage.",
  "judgment": "Driven out with a whip. The chief priests sought how they might destroy him for it. Zechariah's last verse hangs over the scene: in that day there shall be no more the Canaanite, the trafficker, in the house of the Lord of hosts.",
  "refs": R("John 2:13-17", "Matthew 21:12-13", "Mark 11:15-18", "Isaiah 56:7", "Jeremiah 7:11", "Zechariah 14:21", "Psalms 69:9"),
  "laws": ["2J.7", "16D", "20A.15", "17C.5", "20E.9"],
  "topics": ["money", "church", "prayer"],
  "themes": ["covetousness", "irreverence", "priesthood"],
 },
 {
  "slug": "judas-iscariot",
  "name": "Judas Iscariot",
  "era": "Gospels",
  "charge": "Theft from the common purse; betraying innocent blood for thirty pieces of silver",
  "verdict": "death",
  "summary": "One of the twelve, keeper of the bag, and a thief who took what was put in it. He went to the chief priests and asked what they would give him; they weighed thirty pieces of silver. He delivered Christ with a kiss. In the morning he brought the silver back: I have sinned in that I have betrayed the innocent blood.",
  "offense": "Covetousness ripened into treachery. Zechariah had priced the shepherd at thirty pieces of silver, the price of a gored slave. His own confession names the statute: cursed be he that taketh reward to slay an innocent person. Christ: good were it for that man if he had never been born.",
  "judgment": "The priests would not take the money back; he cast it down in the temple, went and hanged himself, and the silver bought the potter's field. Acts adds that he fell headlong and burst asunder. Peter, citing the Psalms, says he went to his own place, and his bishoprick passed to another.",
  "refs": R("John 12:4-6", "John 13:2", "Luke 22:3-6", "Matthew 26:14-16", "Matthew 26:47-50", "Matthew 26:24", "Matthew 27:3-10", "Acts 1:16-20", "Acts 1:25", "Zechariah 11:12-13", "Psalms 41:9", "Psalms 109:8", "Deuteronomy 27:25"),
  "laws": ["4C.1", "4C.6", "18B.1", "3J.6", "10A.2", "10A.7", "17C.16"],
  "topics": ["suicide", "money", "covet", "false-brethren", "christ-rejected"],
  "themes": ["betrayal", "covetousness", "suicide", "theft"],
 },
 {
  "slug": "the-council",
  "name": "Caiaphas and the council",
  "era": "Gospels",
  "charge": "Seeking false witness against Christ; condemning him by night; delivering him to the Gentiles; forbidding the apostles; stoning Stephen",
  "verdict": "temporal",
  "summary": "Caiaphas had already ruled that it was expedient one man die for the people. The council sought false witness to put Jesus to death and found none that agreed; then the high priest adjured him and condemned him for his answer. They delivered him to Pilate, chose Barabbas, and afterward beat and forbade his apostles, and gnashed on Stephen and stoned him.",
  "offense": "Every rule of the court broken in one night: witnesses suborned, testimony not agreeing, a capital sentence at night by the accusers themselves, and the prisoner condemned by his own compelled confession. Stephen's charge to them: ye stiffnecked, which of the prophets have not your fathers persecuted? and ye have been now the betrayers and murderers of the Just One.",
  "judgment": "Christ told them the kingdom would be taken from them and their house left desolate; Paul says the wrath is come upon them to the uttermost. Peter to their faces: the stone which was set at nought of you builders. Within the generation the temple in which they sat was rubble.",
  "refs": R("John 11:47-53", "Matthew 26:3-4", "Matthew 26:59-66", "Mark 14:55-59", "Luke 23:1-2", "Acts 3:13-15", "Acts 4:5-11", "Acts 5:27-28", "Acts 5:40", "Acts 7:51-60", "Deuteronomy 19:15-19", "Exodus 23:1-2", "Exodus 23:7", "Matthew 21:43", "Matthew 23:38", "1 Thessalonians 2:14-16"),
  "laws": ["4E.1", "4E.4", "4E.9", "4E.10", "4F.13", "4F.6", "8C.9", "10A.2", "17K.5"],
  "topics": ["witnesses", "christ-rejected", "persecution", "stiff-necked", "justice"],
  "themes": ["false-witness", "murder", "persecution", "priesthood", "leadership"],
 },
 {
  "slug": "pilate",
  "name": "Pontius Pilate",
  "era": "Gospels",
  "charge": "Condemning a man he had three times pronounced innocent",
  "verdict": "unrecorded",
  "summary": "Pilate found no fault in him, said so three times, was warned by his wife's dream, and offered the crowd Barabbas instead. When they threatened that he was not Caesar's friend, he washed his hands, said, I am innocent of the blood of this just person, and delivered Jesus to be crucified.",
  "offense": "The judge who justifies the wicked and condemns the just is an abomination; the judge who follows a multitude to do evil is forbidden by name. He knew, he said so, and he signed. Water does not answer for a sentence.",
  "judgment": "Scripture pronounces nothing on Pilate personally; Acts names him with Herod and the Gentiles and the people of Israel as gathered together against the Lord's holy child, to do whatsoever thy hand and thy counsel determined before to be done. Paul cites his court as the place where Christ witnessed a good confession.",
  "refs": R("Luke 23:4", "Luke 23:13-16", "Luke 23:20-25", "Matthew 27:19", "Matthew 27:22-26", "John 18:38", "John 19:4", "John 19:12-16", "Acts 4:27-28", "1 Timothy 6:13", "Exodus 23:2", "Exodus 23:7", "Proverbs 17:15"),
  "laws": ["4F.13", "4F.1", "4E.9", "8C.9", "8C.2", "8A.6", "4F.3"],
  "topics": ["justice", "respect-of-persons", "peer-pressure", "christ-rejected"],
  "themes": ["injustice", "cowardice", "leadership"],
 },
 {
  "slug": "barabbas",
  "name": "Barabbas",
  "era": "Gospels",
  "charge": "Insurrection and murder",
  "verdict": "spared",
  "summary": "A notable prisoner, lying bound with them that had made insurrection and had committed murder in the insurrection. Pilate offered the crowd a choice between him and Jesus; the chief priests moved them to ask for Barabbas. He was released and Jesus was crucified.",
  "offense": "Rebellion against the government and murder, both capital under the law of Moses and of Rome. Peter states the exchange to the men of Israel: ye denied the Holy One and the Just, and desired a murderer to be granted unto you.",
  "judgment": "Released, by the custom of the feast and the demand of the crowd. The guilty man walked free because the innocent was condemned in his place; the gospels leave the figure there and say no more of him.",
  "refs": R("Mark 15:6-15", "Luke 23:18-19", "Luke 23:25", "Matthew 27:15-21", "John 18:39-40", "Acts 3:14", "Proverbs 17:15"),
  "laws": ["10A.4", "10G.3", "4F.13", "8C.9"],
  "topics": ["murder", "rebellious", "justice", "christ-rejected"],
  "themes": ["murder", "rebellion", "injustice", "substitution"],
 },
 {
  "slug": "jerusalem",
  "name": "Jerusalem, that killeth the prophets",
  "era": "Gospels",
  "charge": "Killing the prophets and stoning them that are sent; not knowing the time of her visitation",
  "verdict": "captivity",
  "summary": "Christ wept over the city and told it what was coming: thine enemies shall cast a trench about thee, and lay thee even with the ground, and thy children within thee, because thou knewest not the time of thy visitation. He said not one stone of the temple would be left on another, and that this generation would see it.",
  "offense": "The blood of all the prophets shed from the foundation of the world, from Abel to Zacharias, required of this generation; and the rejection of the one who would have gathered her children as a hen her chickens. Daniel had said the people of the prince that shall come would destroy the city and the sanctuary.",
  "judgment": "There shall be great distress in the land, and wrath upon this people. And they shall fall by the edge of the sword, and shall be led away captive into all nations: and Jerusalem shall be trodden down of the Gentiles, until the times of the Gentiles be fulfilled. Deuteronomy 28 had described the siege in detail.",
  "refs": R("Matthew 23:29-38", "Matthew 24:1-2", "Luke 13:34-35", "Luke 19:41-44", "Luke 21:20-24", "Luke 23:28-31", "Daniel 9:26", "Deuteronomy 28:49-53", "Deuteronomy 28:64"),
  "laws": ["10A.2", "2H.3", "2I.9", "20F.4", "2P.9"],
  "topics": ["scattered", "dispersed", "christ-rejected", "prophetic-warnings", "captivity"],
  "themes": ["persecution", "captivity", "corporate-judgment"],
 },
 {
  "slug": "peters-denial",
  "name": "Peter's denial",
  "era": "Gospels",
  "charge": "Denying Christ three times with cursing and swearing",
  "verdict": "reprieve",
  "summary": "Though I should die with thee, yet will I not deny thee. Before the cock crew twice he had denied him three times, the last with oaths and curses, to a maid and to bystanders in the high priest's courtyard. The Lord turned and looked upon Peter, and he went out and wept bitterly.",
  "offense": "Whosoever shall deny me before men, him will I also deny before my Father. Peter did it three times and sealed it with a false oath. The sin was foretold, and so was the mercy: I have prayed for thee, that thy faith fail not.",
  "judgment": "No sentence but the look and the tears. After the resurrection Christ asked him three times, lovest thou me? and three times restored him: feed my sheep. Peter's godly sorrow worked repentance; Judas' sorrow worked death.",
  "refs": R("Matthew 26:33-35", "Matthew 26:69-75", "Luke 22:31-34", "Luke 22:60-62", "John 21:15-17", "Matthew 10:33", "2 Corinthians 7:10", "Mark 14:66-72"),
  "laws": ["3E.1", "4D.3", "4D.14", "2B", "2L.7"],
  "topics": ["repentance", "godly-sorrow", "forgiveness", "fear"],
  "themes": ["denial", "repentance", "forgiveness"],
 },
 {
  "slug": "the-woman-taken-in-adultery",
  "name": "The woman taken in adultery",
  "era": "Gospels",
  "charge": "Adultery, in the very act",
  "verdict": "spared",
  "summary": "The scribes and Pharisees brought a woman taken in adultery and set her in the midst: Moses commanded that such should be stoned; what sayest thou? They said it to tempt him. He wrote on the ground, and then: he that is without sin among you, let him first cast a stone at her.",
  "offense": "Hers was capital under Leviticus 20 and Deuteronomy 22, and the accusers were right about the statute. But the same statute requires the man, absent here, and Deuteronomy 17 requires the witnesses to cast the first stones on their own testimony. Christ put the witnesses to the test the law itself imposes.",
  "judgment": "Convicted by their own conscience, they went out one by one, beginning at the eldest. With no witness remaining there was no case: hath no man condemned thee? Neither do I condemn thee: go, and sin no more. Spared, and commanded.",
  "refs": R("John 8:3-11", "Leviticus 20:10", "Deuteronomy 22:22-24", "Deuteronomy 17:6-7", "Deuteronomy 19:15"),
  "laws": ["10J.1", "4E.10", "4E.3", "19E", "2L.14"],
  "topics": ["adultery", "witnesses", "mercy", "stop-sinning"],
  "themes": ["adultery", "mercy", "witnesses"],
 },
 {
  "slug": "zacchaeus",
  "name": "Zacchaeus",
  "era": "Gospels",
  "charge": "Extortion as chief of the publicans",
  "verdict": "restitution",
  "summary": "A rich chief tax-collector of Jericho climbed a sycamore to see Jesus and was called down by name. Standing in his house he said: the half of my goods I give to the poor; and if I have taken any thing from any man by false accusation, I restore him fourfold.",
  "offense": "The publican's trade as commonly practiced: assessment by false accusation and extortion, which Leviticus 6 classes with theft and fraud. Fourfold was the law's rate for a stolen sheep, the highest ordinary restitution, and Zacchaeus chose it for himself.",
  "judgment": "This day is salvation come to this house, forsomuch as he also is a son of Abraham. The restitution was not the price of the salvation but its evidence: fruits meet for repentance, the very thing John had told the publicans to bring.",
  "refs": R("Luke 19:1-10", "Exodus 22:1", "Leviticus 6:1-5", "Numbers 5:6-7", "2 Samuel 12:6", "Luke 3:12-13", "Luke 3:8"),
  "laws": ["19C.2", "19C.15", "19C.19", "19C.20", "16E", "2L.7"],
  "topics": ["repentance", "money", "stealing", "poor"],
  "themes": ["restitution", "repentance", "theft"],
 },
 {
  "slug": "the-penitent-thief",
  "name": "The penitent thief",
  "era": "Gospels",
  "charge": "Robbery, under sentence of crucifixion",
  "verdict": "death",
  "summary": "Two malefactors were crucified with Christ. One railed on him; the other rebuked his fellow: we indeed justly, for we receive the due reward of our deeds, but this man hath done nothing amiss. Then: Lord, remember me when thou comest into thy kingdom.",
  "offense": "Matthew calls them thieves, Luke malefactors; the man's own confession is that the sentence was just. He owned the law's verdict on himself in the hour of its execution.",
  "judgment": "The sentence of the state was carried out; he died on the cross that day. The sentence of heaven was reversed in the same hour: verily I say unto thee, to day shalt thou be with me in paradise. Isaiah had said the servant would be numbered with the transgressors.",
  "refs": R("Luke 23:32-33", "Luke 23:39-43", "Matthew 27:38", "Matthew 27:44", "Isaiah 53:12", "Mark 15:27-28"),
  "laws": ["18B.3", "19D", "2L.5", "2L.14", "2P.10"],
  "topics": ["repentance", "salvation", "grace", "stealing"],
  "themes": ["theft", "repentance", "mercy"],
 },
 {
  "slug": "saul-of-tarsus",
  "name": "Saul of Tarsus",
  "era": "Apostolic",
  "charge": "Persecuting the church; consenting to Stephen's death; compelling the saints to blaspheme",
  "verdict": "spared",
  "summary": "The young man at whose feet Stephen's killers laid their clothes made havock of the church, entering every house and haling men and women to prison, and set out for Damascus with letters to bind any he found of that way. A light from heaven and a voice met him on the road: why persecutest thou me?",
  "offense": "By his own later account: I persecuted this way unto the death; I punished them oft in every synagogue and compelled them to blaspheme; being exceedingly mad against them, I persecuted them even unto strange cities. He was a blasphemer, a persecutor, and injurious.",
  "judgment": "Three days blind and fasting in Damascus, then sight, baptism, and a commission. I obtained mercy, because I did it ignorantly in unbelief. He calls himself the chief of sinners and the pattern of the longsuffering shown to them which should hereafter believe. Ananias was told he would be shown how great things he must suffer.",
  "refs": R("Acts 7:58", "Acts 8:1-3", "Acts 9:1-9", "Acts 9:15-18", "Acts 22:4-5", "Acts 26:9-11", "1 Corinthians 15:9", "Galatians 1:13", "1 Timothy 1:12-16"),
  "laws": ["10A.2", "3F", "2K.2", "2K.3", "2P.10", "2L.5"],
  "topics": ["persecution", "mercy", "ignorance", "convert"],
  "themes": ["persecution", "mercy", "repentance"],
 },
 {
  "slug": "simon-magus",
  "name": "Simon Magus",
  "era": "Apostolic",
  "charge": "Offering money for the gift of the Holy Ghost",
  "verdict": "reprieve",
  "summary": "A sorcerer of Samaria who had long bewitched the people and given out that he was some great one, Simon believed and was baptized under Philip. When he saw that the Spirit was given through the apostles' hands he offered them money for the same power.",
  "offense": "Thy money perish with thee, because thou hast thought that the gift of God may be purchased with money. Peter names the state behind the offer: thy heart is not right in the sight of God; thou art in the gall of bitterness and in the bond of iniquity. A sorcerer's instinct, to buy power.",
  "judgment": "Repent therefore of this thy wickedness, and pray God, if perhaps the thought of thine heart may be forgiven thee. Simon asked Peter to pray for him that none of these things come upon him, and the record ends there. His name became the word for buying office in the church.",
  "refs": R("Acts 8:9-13", "Acts 8:18-24", "Deuteronomy 18:10-11", "Isaiah 55:1", "2 Kings 5:15-16", "Micah 3:11"),
  "laws": ["20E.5", "2G.3", "17C.16", "20A.12", "2L.14"],
  "topics": ["money", "divination", "holy-ghost"],
  "themes": ["occult", "covetousness", "reproof"],
 },
 {
  "slug": "elymas",
  "name": "Elymas the sorcerer",
  "era": "Apostolic",
  "charge": "Withstanding the apostles; seeking to turn the deputy from the faith",
  "verdict": "temporal",
  "summary": "At Paphos the proconsul Sergius Paulus sent for Barnabas and Saul to hear the word. Bar-jesus, a Jewish sorcerer and false prophet attached to his court, withstood them, seeking to turn away the deputy from the faith. Paul, filled with the Holy Ghost, set his eyes on him.",
  "offense": "O full of all subtilty and all mischief, thou child of the devil, thou enemy of all righteousness, wilt thou not cease to pervert the right ways of the Lord? A sorcerer, forbidden by the law outright, using his influence to keep a ruler from the truth.",
  "judgment": "The hand of the Lord is upon thee, and thou shalt be blind, not seeing the sun for a season. Immediately there fell on him a mist and a darkness, and he went about seeking some to lead him by the hand. The deputy, seeing it, believed.",
  "refs": R("Acts 13:6-12", "Deuteronomy 18:10-12", "Deuteronomy 13:6-8", "Exodus 22:18"),
  "laws": ["2G.3", "2G.5", "10F.4", "20F.1", "3J.14", "10D"],
  "topics": ["divination", "false-prophets", "blindness"],
  "themes": ["occult", "false-prophets", "enticement"],
 },
 {
  "slug": "the-sons-of-sceva",
  "name": "The seven sons of Sceva",
  "era": "Apostolic",
  "charge": "Exorcising in the name of Jesus whom Paul preacheth",
  "verdict": "temporal",
  "summary": "Vagabond Jewish exorcists at Ephesus, seven sons of a chief priest, took up the name of the Lord Jesus as a formula over those that had evil spirits. The spirit answered, Jesus I know, and Paul I know; but who are ye?",
  "offense": "The Name used as a spell by men who did not belong to it, in a city given to curious arts. Taking the name in vain in its most literal form.",
  "judgment": "The man in whom the evil spirit was leaped on them, overcame them, and prevailed against them, so that they fled out of that house naked and wounded. Fear fell on the city, the name was magnified, and the practitioners of curious arts burned their books, fifty thousand pieces of silver worth.",
  "refs": R("Acts 19:13-20", "Exodus 20:7", "Deuteronomy 18:10-11", "Leviticus 19:31", "Matthew 7:22-23"),
  "laws": ["2K.1", "2G.3", "2G.4", "2K.9"],
  "topics": ["the-name", "divination", "exposed"],
  "themes": ["occult", "irreverence"],
 },
 {
  "slug": "the-corinthian-fornicator",
  "name": "The Corinthian who had his father's wife",
  "era": "Apostolic",
  "charge": "Fornication not so much as named among the Gentiles: a man with his father's wife",
  "verdict": "exile",
  "summary": "Paul heard that a member of the Corinthian church was living with his father's wife and that the church, instead of mourning, was puffed up. He judged the case in absence: deliver such an one unto Satan for the destruction of the flesh, that the spirit may be saved in the day of the Lord Jesus.",
  "offense": "Leviticus 18 and 20 and Deuteronomy 27 all name it, the last with a curse and the middle with death. Paul's rule follows the statute's shape: put away from among yourselves that wicked person. The church's tolerance was a second offense: a little leaven leaveneth the whole lump.",
  "judgment": "Excommunicated by the assembly. The second letter shows the outcome: the punishment inflicted of many was sufficient, the man was overwhelmed with sorrow, and Paul urged them to forgive and comfort him and confirm their love toward him, lest Satan get an advantage. Banishment, then restoration on repentance.",
  "refs": R("1 Corinthians 5:1-5", "1 Corinthians 5:6-8", "1 Corinthians 5:11-13", "Leviticus 18:8", "Leviticus 20:11", "Deuteronomy 27:20", "2 Corinthians 2:5-11", "2 Corinthians 7:8-12"),
  "laws": ["10J.2", "5G", "5E.10", "19D.9", "3L.5", "3L.2"],
  "topics": ["sexual-lust", "correction", "discipline", "forgiveness"],
  "themes": ["sexual-immorality", "church-discipline", "restoration"],
 },
 {
  "slug": "the-corinthian-supper",
  "name": "The Corinthians at the Lord's supper",
  "era": "Apostolic",
  "charge": "Eating and drinking unworthily; shaming them that have not",
  "verdict": "plague",
  "summary": "When the Corinthians came together it was not to eat the Lord's supper: every one took his own supper before another, one was hungry and another drunken, and the poor were shamed in the assembly of the church. Paul: what, have ye not houses to eat and to drink in?",
  "offense": "Contempt for the assembly and for the brethren who had nothing, in the very meal that proclaimed the Lord's death. Whosoever shall eat this bread and drink this cup unworthily shall be guilty of the body and blood of the Lord.",
  "judgment": "For this cause many are weak and sickly among you, and many sleep. Paul frames it as chastening: when we are judged, we are chastened of the Lord, that we should not be condemned with the world. The remedy: let a man examine himself, and tarry one for another.",
  "refs": R("1 Corinthians 11:17-22", "1 Corinthians 11:27-34", "Hebrews 12:5-6", "Proverbs 3:11-12"),
  "laws": ["20D.9", "9B.6", "12G.5", "15A.2", "2P.5", "2P.18"],
  "topics": ["fellowship", "sickness", "poor", "chastisement"],
  "themes": ["irreverence", "church-discipline", "corporate-judgment"],
 },
 {
  "slug": "hymenaeus-and-alexander",
  "name": "Hymenaeus, Alexander, and Philetus",
  "era": "Apostolic",
  "charge": "Making shipwreck of the faith; blasphemy; teaching that the resurrection is past already",
  "verdict": "exile",
  "summary": "Paul names Hymenaeus and Alexander as men who put away faith and a good conscience and made shipwreck, whom I have delivered unto Satan, that they may learn not to blaspheme. Hymenaeus and Philetus erred concerning the truth, saying the resurrection is past already, and overthrew the faith of some. Alexander the coppersmith did him much evil.",
  "offense": "Heresy that eats as doth a canker, spread inside the church by teachers. Titus gives the procedure: a man that is an heretick after the first and second admonition reject, knowing that he is subverted and sinneth, being condemned of himself.",
  "judgment": "Delivered unto Satan, the apostolic form of putting out, with the stated aim of correction. Of Alexander Paul adds only: the Lord reward him according to his works.",
  "refs": R("1 Timothy 1:19-20", "2 Timothy 2:16-18", "2 Timothy 4:14-15", "Titus 3:10-11", "1 Corinthians 5:5"),
  "laws": ["2K.3", "20F.7", "3J.14", "3L.13", "19D.9"],
  "topics": ["heresy", "false-brethren", "good-doctrine"],
  "themes": ["heresy", "church-discipline"],
 },
 {
  "slug": "peter-at-antioch",
  "name": "Peter at Antioch",
  "era": "Apostolic",
  "charge": "Dissembling: withdrawing from the Gentiles for fear of them of the circumcision",
  "verdict": "reprieve",
  "summary": "At Antioch Peter had eaten with the Gentiles until certain came from James; then he withdrew and separated himself, fearing them which were of the circumcision, and the other Jews and even Barnabas were carried away with his dissimulation. Paul withstood him to the face, because he was to be blamed.",
  "offense": "Hypocrisy in a pillar of the church, contradicting the vision God had given him at Joppa and the judgment he himself had argued at Jerusalem. Paul's charge: they walked not uprightly according to the truth of the gospel, and by the example compelled the Gentiles to live as do the Jews.",
  "judgment": "A public rebuke before them all, and no more; the epistle records the correction and leaves the reconciliation to be inferred. Peter later commends Paul's letters as scripture. The case stands as the law's own rule for reproof: a trespass taken openly to the transgressor.",
  "refs": R("Galatians 2:11-14", "Acts 10:28", "Acts 10:34-35", "Acts 11:2-3", "Acts 15:7-9", "2 Peter 3:15-16", "Leviticus 19:17"),
  "laws": ["17K.1", "17K.5", "4F.3", "3L.2", "3L.20", "3L.16"],
  "topics": ["respect-of-persons", "correction", "peer-pressure", "whitewashing"],
  "themes": ["hypocrisy", "partiality", "reproof"],
 },
 {
  "slug": "jezebel-of-thyatira",
  "name": "Jezebel of Thyatira",
  "era": "Apostolic",
  "charge": "Calling herself a prophetess; teaching the servants of God to commit fornication and eat things sacrificed to idols",
  "verdict": "death",
  "summary": "Christ's word to the angel of the church in Thyatira: thou sufferest that woman Jezebel, which calleth herself a prophetess, to teach and to seduce my servants. He had given her space to repent of her fornication, and she repented not.",
  "offense": "The two things the apostles' council had bound on the Gentiles, abstinence from idol meats and from fornication, taught as liberty by a self-appointed prophetess, under a name that carried Ahab's queen with it. The church's toleration is charged against the church.",
  "judgment": "Behold, I will cast her into a bed, and them that commit adultery with her into great tribulation, except they repent of their deeds. And I will kill her children with death; and all the churches shall know that I am he which searcheth the reins and hearts.",
  "refs": R("Revelation 2:20-23", "Acts 15:28-29", "1 Corinthians 10:19-21", "1 Kings 16:31", "Numbers 25:1-2", "Numbers 31:16"),
  "laws": ["10F.4", "5E.1", "2G.2", "20F.1", "20D.6", "20D.10", "2I.2"],
  "topics": ["false-prophets", "women-in-order", "spiritual-fornication", "idolatry"],
  "themes": ["false-prophets", "sexual-immorality", "idolatry", "enticement"],
 },
 {
  "slug": "diotrephes",
  "name": "Diotrephes",
  "era": "Apostolic",
  "charge": "Loving the preeminence; prating against the apostle with malicious words; casting the brethren out of the church",
  "verdict": "unrecorded",
  "summary": "John wrote to the church, but Diotrephes, who loveth to have the preeminence among them, received him not. He spoke against the apostle with malicious words, refused to receive the traveling brethren himself, forbade those who would, and cast them out of the church.",
  "offense": "Pride in office, slander of an apostle, refusal of hospitality to the brethren, and excommunication used as a weapon. The law's word on the slanderer and on hospitality to strangers both apply; so does Christ's on those who would be greatest.",
  "judgment": "Wherefore, if I come, I will remember his deeds which he doeth. The epistle records the charge and the intention; the sentence is not recorded. Beloved, follow not that which is evil, but that which is good.",
  "refs": R("3 John 1:9-11", "Matthew 20:25-27", "Matthew 23:11-12", "Proverbs 16:18", "Hebrews 13:2"),
  "laws": ["17G.13", "12E.16", "15A.9", "20B.6", "12E.2"],
  "topics": ["pride", "talebearer", "meddler", "fellowship"],
  "themes": ["pride", "slander", "leadership", "inhospitality"],
 },
]
