from cases_lib import R

CASES = [
 {
  "slug": "asking-for-a-king",
  "name": "Israel asking for a king",
  "era": "United Monarchy",
  "charge": "Rejecting the Lord's rule to be like the nations",
  "verdict": "reprieve",
  "summary": "The elders came to Samuel and demanded a king to judge them like all the nations. The Lord told Samuel: they have not rejected thee, but they have rejected me. Warned what a king would take from them, they said, nay, but we will have a king over us.",
  "offense": "Deuteronomy allowed a king on God's terms; Israel wanted one on the nations' terms, to go out before them and fight their battles, as if the Lord had not. Samuel later named it: your wickedness is great, which ye have done in the sight of the Lord, in asking you a king. Hosea: I gave thee a king in mine anger.",
  "judgment": "The Lord granted the request and sent thunder and rain in wheat harvest as a sign of his displeasure. The people feared and confessed, and Samuel answered, fear not; ye have done all this wickedness, yet turn not aside from following the Lord. They got Saul.",
  "refs": R("1 Samuel 8:4-9", "1 Samuel 8:11-20", "1 Samuel 10:19", "1 Samuel 12:12-13", "1 Samuel 12:17-20", "Hosea 13:11", "Deuteronomy 17:14-15"),
  "laws": ["8B.6", "8B.1", "8A.5", "2H", "11C.3"],
  "topics": ["trust-god", "other-nations", "kings-and-priests"],
  "themes": ["kingship", "distrust", "leadership"],
 },
 {
  "slug": "doeg-and-the-priests-of-nob",
  "name": "Saul and Doeg at Nob",
  "era": "United Monarchy",
  "charge": "Slaughter of the priests of the Lord on an informer's report",
  "verdict": "curse",
  "summary": "Doeg the Edomite, Saul's chief herdsman, told the king that Ahimelech had given David bread and Goliath's sword. Saul summoned the priests, condemned them unheard, and when his own guard refused to strike them, Doeg killed eighty-five men in linen ephods and then the whole city of Nob.",
  "offense": "For Saul, judicial murder of the priesthood on a suspicion; Ahimelech's defense was true and ignored. For Doeg, a report shaped to kill and a hand willing to do what Israelites would not. Psalm 52 is David's indictment of him: thy tongue deviseth mischiefs, like a sharp razor.",
  "judgment": "Psalm 52 pronounces it: God shall likewise destroy thee for ever, he shall take thee away, and pluck thee out of thy dwelling place. Saul's own end came at Gilboa. Abiathar alone escaped Nob and carried the ephod to David.",
  "refs": R("1 Samuel 21:7", "1 Samuel 22:9-10", "1 Samuel 22:13-19", "1 Samuel 22:20-23", "Psalms 52:1-5", "Exodus 23:7"),
  "laws": ["10A.2", "8A.14", "8A.19", "12E.2", "4F.13", "20A"],
  "topics": ["murder", "talebearer", "persecution"],
  "themes": ["murder", "persecution", "priesthood", "kingship"],
 },
 {
  "slug": "nabal",
  "name": "Nabal",
  "era": "United Monarchy",
  "charge": "Churlish refusal of hospitality; railing on the Lord's anointed",
  "verdict": "death",
  "summary": "David's men had guarded Nabal's shepherds all season. At sheep-shearing David asked for provision; Nabal, churlish and evil in his doings, answered, who is David? and sent them away. Abigail's wisdom stopped David's sword. The Lord did not stop his own.",
  "offense": "Ingratitude and contempt where the law commands open hands, delivered by a man drunk at his own feast. His wife's verdict: as his name is, so is he; Nabal is his name, and folly is with him.",
  "judgment": "Ten days after his heart died within him and became as a stone, the Lord smote Nabal, that he died. David blessed the Lord who had pleaded his cause and kept him from avenging himself.",
  "refs": R("1 Samuel 25:2-3", "1 Samuel 25:10-11", "1 Samuel 25:14-17", "1 Samuel 25:25", "1 Samuel 25:36-39", "Deuteronomy 15:7-8"),
  "laws": ["15A.15", "15A.7", "15B.4", "12G.5", "12F.1", "17M.3"],
  "topics": ["honour", "drinking", "avenge"],
  "themes": ["inhospitality", "drunkenness", "vengeance"],
 },
 {
  "slug": "the-amalekite-messenger",
  "name": "The Amalekite who claimed to kill Saul",
  "era": "United Monarchy",
  "charge": "Claiming to have slain the Lord's anointed",
  "verdict": "death",
  "summary": "A young Amalekite came to David at Ziklag with Saul's crown and bracelet and said he had killed the wounded king at his own request. The earlier chapter says Saul fell on his own sword. Either way, his mouth condemned him.",
  "offense": "He expected reward for the death of Saul. David judged him on his own testimony: how wast thou not afraid to stretch forth thine hand to destroy the Lord's anointed? Whether he lied for gain or did the deed, the charge stood.",
  "judgment": "Thy blood be upon thy head; for thy mouth hath testified against thee. David had him executed on the spot.",
  "refs": R("2 Samuel 1:2-10", "2 Samuel 1:13-16", "1 Samuel 31:3-5", "1 Samuel 24:6", "1 Samuel 26:9-11"),
  "laws": ["10A.4", "8D.1", "4E.1", "3E.5"],
  "topics": ["murder", "lying", "honour"],
  "themes": ["murder", "kingship", "deceit"],
 },
 {
  "slug": "baanah-and-rechab",
  "name": "Baanah and Rechab",
  "era": "United Monarchy",
  "charge": "Murder of Ish-bosheth in his bed",
  "verdict": "death",
  "summary": "Two captains of Saul's son entered his house at noon under pretense of fetching wheat, killed him as he lay on his bed, cut off his head, and carried it all night to David at Hebron expecting a reward.",
  "offense": "Murder of a righteous person in his own house upon his bed, as David put it, done with guile for gain. They dressed it as service to the Lord's cause and David's.",
  "judgment": "David commanded his young men to slay them; their hands and feet were cut off and hung over the pool in Hebron. Ish-bosheth's head was buried in Abner's grave.",
  "refs": R("2 Samuel 4:5-12", "Exodus 21:14", "Deuteronomy 27:24"),
  "laws": ["10A.5", "10A.7", "8A.14", "19D.7"],
  "topics": ["murder", "treasure"],
  "themes": ["murder", "kingship"],
 },
 {
  "slug": "joab",
  "name": "Joab",
  "era": "United Monarchy",
  "charge": "Murder of Abner and Amasa in time of peace",
  "verdict": "death",
  "summary": "David's general killed Abner in the gate of Hebron under cover of a private word, avenging Asahel's death in battle, and years later killed Amasa with a kiss and a hidden sword. David laid both on Solomon's charge.",
  "offense": "Two captains of the host, both under the king's protection, both killed by treachery outside any battle. David's sentence in life: the Lord shall reward the doer of evil according to his wickedness. His charge at death: he shed the blood of war in peace.",
  "judgment": "Joab fled to the horns of the altar. Solomon cited the statute that the altar is no refuge for a murderer and sent Benaiah to kill him there, that the innocent blood be taken away from David's house. He was buried in his own house in the wilderness.",
  "refs": R("2 Samuel 3:26-30", "2 Samuel 3:38-39", "2 Samuel 20:8-10", "1 Kings 2:5-6", "1 Kings 2:28-34", "Exodus 21:14", "Deuteronomy 19:11-13"),
  "laws": ["10A.5", "10A.6", "10I.3", "10A.3", "17M.1"],
  "topics": ["murder", "avenge"],
  "themes": ["murder", "vengeance", "kingship"],
 },
 {
  "slug": "amnon",
  "name": "Amnon",
  "era": "United Monarchy",
  "charge": "Rape of his sister Tamar",
  "verdict": "death",
  "summary": "David's firstborn feigned sickness to get his half-sister alone, and when she pleaded that such a thing should not be done in Israel, forced her, then hated her more than he had loved her and had her thrown out. David was very wroth and did nothing.",
  "offense": "Incest and rape together, both capital under the law he was heir to. Tamar had named the law and offered him the lawful way of asking the king; he would not hearken to her voice. Then he added public shame to the crime.",
  "judgment": "Two years later Absalom had him killed at the sheep-shearing feast when his heart was merry with wine. Nathan's sentence on David's house, the sword shall never depart, began its work here.",
  "refs": R("2 Samuel 13:1-2", "2 Samuel 13:6-14", "2 Samuel 13:15-19", "2 Samuel 13:21-22", "2 Samuel 13:28-29", "Leviticus 18:9", "Leviticus 20:17", "Deuteronomy 22:25"),
  "laws": ["10J.9", "10J.2", "5G.2", "17H.5", "6A.4"],
  "topics": ["sexual-lust", "defile", "family-trials"],
  "themes": ["sexual-immorality", "violence", "negligence", "kingship"],
 },
 {
  "slug": "absalom",
  "name": "Absalom",
  "era": "United Monarchy",
  "charge": "Murder of Amnon; conspiracy and rebellion against the king his father; lying with his father's concubines",
  "verdict": "death",
  "summary": "David's son killed his brother, fled, was restored, then stole the hearts of Israel at the gate with flattery, raised a rebellion from Hebron, drove his father from Jerusalem, and lay with David's concubines on the roof before all Israel by Ahithophel's counsel.",
  "offense": "The stubborn and rebellious son of Deuteronomy 21 on a national scale: murder, treason, and the uncovering of his father's bed as a political act. The rebellion was fueled by a daily lie at the gate: see, thy matters are good, but there is no man deputed of the king to hear thee.",
  "judgment": "Caught by his hair in an oak as his mule went from under him, he was run through by Joab and ten armor-bearers, cast into a pit, and covered with a great heap of stones. He had raised a pillar for his own name; the stones were his monument instead.",
  "refs": R("2 Samuel 13:28-29", "2 Samuel 15:1-6", "2 Samuel 15:10-14", "2 Samuel 16:21-22", "2 Samuel 18:9-15", "2 Samuel 18:17-18", "Deuteronomy 21:18-21", "Leviticus 18:8"),
  "laws": ["10A.5", "10G.3", "6C.1", "6C.2", "10J.2", "3H", "17G.19"],
  "topics": ["rebellious", "murder", "pride"],
  "themes": ["rebellion", "murder", "dishonor-of-parents", "kingship"],
 },
 {
  "slug": "ahithophel",
  "name": "Ahithophel",
  "era": "United Monarchy",
  "charge": "Treason against David; counsel of incest; suicide",
  "verdict": "death",
  "summary": "David's counselor, whose word was as if a man had inquired at the oracle of God, joined Absalom, advised him to take his father's concubines publicly, and asked for twelve thousand men to kill David that night. When Hushai's counsel was preferred, he went home, set his house in order, and hanged himself.",
  "offense": "Betrayal of the king he served, compounded by counsel that made the rebellion irreversible. Psalm 41 and Psalm 55 are read as David's lament over him: mine own familiar friend, in whom I trusted, which did eat of my bread. Peter cites the psalm of Judas.",
  "judgment": "The Lord had appointed to defeat the good counsel of Ahithophel, to the intent that the Lord might bring evil upon Absalom. He was buried in the sepulchre of his father, a self-executed sentence.",
  "refs": R("2 Samuel 15:12", "2 Samuel 15:31", "2 Samuel 16:20-23", "2 Samuel 17:1-4", "2 Samuel 17:14", "2 Samuel 17:23", "Psalms 41:9", "Psalms 55:12-14"),
  "laws": ["10G.3", "3J.6", "8A.14", "10A.8"],
  "topics": ["suicide", "false-brethren", "seek-counsel"],
  "themes": ["treason", "betrayal", "suicide"],
 },
 {
  "slug": "shimei",
  "name": "Shimei son of Gera",
  "era": "United Monarchy",
  "charge": "Cursing the king and casting stones at him",
  "verdict": "death",
  "summary": "As David fled Jerusalem, Shimei of Saul's house came out cursing and throwing stones and dust: come out, thou bloody man, thou man of Belial. David forbade Abishai to kill him and later swore he would not put him to death. Solomon inherited the case.",
  "offense": "Thou shalt not revile the gods, nor curse the ruler of thy people. He did it in the king's face, in his hour of weakness, with the king's own guard at hand. His later apology at the Jordan was accepted for David's lifetime only.",
  "judgment": "Solomon confined him to Jerusalem on pain of death. Three years later Shimei went to Gath after runaway servants, and Solomon had Benaiah kill him: the Lord shall return thy wickedness upon thine own head.",
  "refs": R("2 Samuel 16:5-13", "2 Samuel 19:18-23", "1 Kings 2:8-9", "1 Kings 2:36-46", "Exodus 22:28", "Ecclesiastes 10:20"),
  "laws": ["8D.8", "8D.4", "4D.6", "12E.10"],
  "topics": ["honour", "submission"],
  "themes": ["contempt-for-authority", "kingship"],
 },
 {
  "slug": "sheba",
  "name": "Sheba son of Bichri",
  "era": "United Monarchy",
  "charge": "Insurrection: we have no part in David",
  "verdict": "death",
  "summary": "On the heels of Absalom's rebellion, Sheba the Benjamite blew a trumpet and cried, every man to his tents, O Israel, and all Israel went up after him. David judged him more dangerous than Absalom. He was besieged in Abel of Beth-maachah.",
  "offense": "Rebellion against the established government, immediately after the last one had been crushed at the cost of twenty thousand men. A man of Belial, the text calls him.",
  "judgment": "A wise woman of the city asked Joab why he would destroy a mother in Israel for one man; the people cut off Sheba's head and threw it over the wall, and Joab blew the trumpet and went home.",
  "refs": R("2 Samuel 20:1-2", "2 Samuel 20:6", "2 Samuel 20:14-22", "Deuteronomy 17:12"),
  "laws": ["10G.3", "10G.1", "8D.7", "19D.6"],
  "topics": ["rebellious", "split-kingdom"],
  "themes": ["rebellion", "kingship"],
 },
 {
  "slug": "davids-census",
  "name": "David's numbering of the people",
  "era": "United Monarchy",
  "charge": "Numbering Israel in pride; a plague on the nation",
  "verdict": "plague",
  "summary": "David commanded Joab to number Israel and Judah. Joab objected; the king's word prevailed. When the count came in, David's heart smote him: I have sinned greatly. Gad offered three judgments, and David chose to fall into the hand of the Lord.",
  "offense": "The narratives lay the provocation to God's anger against Israel and to Satan; the act is David's, and he owns it. A king measuring his strength in men, as if the Lord had not multiplied them and would not fight for them. Exodus required a ransom for every soul numbered, lest there be a plague among them.",
  "judgment": "Pestilence: seventy thousand men died from Dan to Beersheba in three days. The angel stood at Araunah's threshingfloor with drawn sword when the Lord said, it is enough. David bought the floor and built an altar; it became the temple site.",
  "refs": R("2 Samuel 24:1-4", "2 Samuel 24:10-15", "2 Samuel 24:17", "1 Chronicles 21:1-8", "1 Chronicles 21:14-17", "1 Chronicles 21:24-26", "Exodus 30:12", "1 Chronicles 27:23-24"),
  "laws": ["17G.13", "17D.7", "2P.18", "22B"],
  "topics": ["pride", "trust-god", "sickness"],
  "themes": ["pride", "distrust", "corporate-judgment", "kingship"],
 },
 {
  "slug": "michal",
  "name": "Michal",
  "era": "United Monarchy",
  "charge": "Despising the king in her heart for dancing before the ark",
  "verdict": "curse",
  "summary": "As the ark came into the city of David with shouting and trumpets, Michal, Saul's daughter, watched from a window and despised David in her heart for leaping and dancing. She met him with contempt: how glorious was the king of Israel to day.",
  "offense": "Contempt for worship, delivered as contempt for a husband. David answered that it was before the Lord, who chose him over her father's house, and that he would be yet more vile than thus.",
  "judgment": "Therefore Michal the daughter of Saul had no child unto the day of her death. In Israel that was the end of a line; the house of Saul ended in her.",
  "refs": R("2 Samuel 6:14-16", "2 Samuel 6:20-23", "1 Chronicles 15:29", "Psalms 150:4"),
  "laws": ["5C.12", "5C.11", "2J.18", "12E.10"],
  "topics": ["wife", "honour", "women-in-order"],
  "themes": ["contempt-for-worship", "marriage"],
 },
 {
  "slug": "adonijah",
  "name": "Adonijah",
  "era": "United Monarchy",
  "charge": "Exalting himself to be king; asking for the king's concubine",
  "verdict": "death",
  "summary": "David's fourth son exalted himself, saying, I will be king, and gathered chariots, horsemen, Joab, and Abiathar for a coronation feast at En-rogel while David lay dying. Solomon was anointed the same day. Pardoned once, Adonijah then asked for Abishag the Shunammite.",
  "offense": "The narrator notes that his father had never displeased him at any time in saying, why hast thou done so. He usurped a throne the Lord had assigned to Solomon by name. The request for Abishag was, as Solomon read it, a second bid for the kingdom through the king's woman.",
  "judgment": "Solomon had spared him on condition of worthiness. The second offense was the end of it: Benaiah fell upon him and he died. Abiathar was banished and Joab executed in the same purge.",
  "refs": R("1 Kings 1:5-7", "1 Kings 1:50-53", "1 Kings 2:13-25", "1 Chronicles 22:9-10", "1 Chronicles 28:5", "2 Samuel 16:21-22"),
  "laws": ["10G.3", "17G.13", "6A.4", "6E.6", "8B.1"],
  "topics": ["pride", "rebellious", "david-as-king"],
  "themes": ["usurpation", "pride", "kingship", "negligence"],
 },
 {
  "slug": "sauls-house-and-the-gibeonites",
  "name": "Saul's house and the Gibeonites",
  "era": "United Monarchy",
  "charge": "Breaking Israel's sworn covenant by slaying the Gibeonites",
  "verdict": "death",
  "summary": "Three years of famine in David's reign were traced by inquiry of the Lord to Saul and his bloody house, because he slew the Gibeonites in his zeal for Israel, against the oath Joshua had sworn. David asked the Gibeonites what atonement they required.",
  "offense": "Joshua's oath had been sworn by the Lord God of Israel four centuries before. Saul's breach of it was blood-guilt on the land, and the land, as Numbers says, cannot be cleansed of blood but by the blood of him that shed it.",
  "judgment": "Seven of Saul's sons and grandsons were hanged before the Lord at Gibeah, sparing Mephibosheth for David's own oath to Jonathan. Rizpah kept the bodies from the birds until the rain came. Then David buried Saul's bones, and God was intreated for the land.",
  "refs": R("2 Samuel 21:1-9", "2 Samuel 21:10-14", "Joshua 9:15", "Joshua 9:19-20", "Numbers 35:33", "Deuteronomy 24:16", "Ezekiel 18:20"),
  "laws": ["4D.2", "4D.15", "10A.3", "11C.4", "2P.1"],
  "topics": ["agreement", "murder", "strangers"],
  "themes": ["covenant", "bloodshed", "corporate-judgment"],
 },
 {
  "slug": "solomon",
  "name": "King Solomon",
  "era": "United Monarchy",
  "charge": "Multiplying foreign wives; building high places to their gods",
  "verdict": "temporal",
  "summary": "The wisest king loved many strange women, seven hundred wives and three hundred concubines, from the very nations the Lord had said, ye shall not go in to them. When he was old they turned his heart, and he built high places for Chemosh and Molech in the hill before Jerusalem.",
  "offense": "Deuteronomy 17 forbade the king to multiply wives, horses, or silver, and named the reason: that his heart turn not away. Solomon did all three. Nehemiah cites him as the proof that even the beloved of God was made to sin by outlandish women. Sirach: thou didst stain thine honour and pollute thy seed.",
  "judgment": "The Lord was angry, and told him the kingdom would be rent from his son and given to his servant, leaving one tribe for David's sake. Adversaries were raised up in his own lifetime; Jeroboam received the ten tribes at his death. So the kingdom was divided.",
  "refs": R("1 Kings 11:1-13", "1 Kings 11:31-33", "Deuteronomy 17:16-17", "Nehemiah 13:26", "1 Kings 3:1", "Sirach 47:19-21"),
  "laws": ["5G.12", "5G.13", "2D.3", "2D.6", "8B.6", "2I.6"],
  "topics": ["multiple-wives", "intermarrying", "split-kingdom", "idolatry"],
  "themes": ["intermarriage", "idolatry", "kingship", "backsliding"],
 },
]
