from cases_lib import R

CASES = [
 {
  "slug": "lamech",
  "name": "Lamech",
  "era": "Primeval",
  "charge": "Killing a man and boasting of it; claiming seventy-sevenfold vengeance",
  "verdict": "unrecorded",
  "summary": "Cain's descendant Lamech, first recorded polygamist, told his two wives he had killed a man for wounding him and a young man for bruising him, and claimed that if Cain were avenged sevenfold, Lamech would be seventy-sevenfold.",
  "offense": "A killing far out of proportion to the injury, then a song to celebrate it. Lamech takes the protection God extended to Cain and twists it into a license for private vengeance without limit.",
  "judgment": "Scripture records no sentence on Lamech. His line is not heard from after the Flood account opens; the whole world of Cain's descendants ends in Genesis 7.",
  "refs": R("Genesis 4:19", "Genesis 4:23-24", "Genesis 4:15", "Deuteronomy 32:35", "Romans 12:19"),
  "laws": ["10A.1", "17M.3", "17D.13", "19C.1"],
  "topics": ["murder", "avenge", "vainglory"],
  "themes": ["murder", "bloodshed", "pride", "vengeance"],
 },
 {
  "slug": "sons-of-god",
  "name": "The sons of God and the giants",
  "era": "Primeval",
  "charge": "Leaving their proper estate; taking wives of the daughters of men",
  "verdict": "captivity",
  "summary": "Before the Flood the sons of God took wives of whomever they chose among the daughters of men, and giants were in the earth in those days. The New Testament and the Apocrypha both treat this as a transgression that was judged.",
  "offense": "Jude names it: angels who kept not their first estate but left their own habitation. Second Peter calls them the angels that sinned. Sirach calls the giants themselves the old giants who fell away in the strength of their foolishness, and the Wisdom of Solomon says the proud giants perished.",
  "judgment": "The angels are reserved in everlasting chains under darkness unto the judgment of the great day. The giants and the world they filled with violence went under the Flood; Noah alone was carried through.",
  "refs": R("Genesis 6:1-4", "Jude 1:6", "2 Peter 2:4-5", "Sirach 16:7", "Wisdom of Solomon 14:6", "Baruch 3:26-28"),
  "laws": ["2H.1", "17G.13", "2P.3"],
  "topics": ["giants", "pride"],
  "themes": ["pride", "corporate-judgment", "the-fall"],
 },
 {
  "slug": "ham",
  "name": "Ham and the curse on Canaan",
  "era": "Primeval",
  "charge": "Uncovering and publishing his father's nakedness",
  "verdict": "curse",
  "summary": "Noah drank of his vineyard and lay uncovered in his tent. Ham saw his father's nakedness and told his two brothers outside, who walked in backward with a garment and covered him without looking.",
  "offense": "Dishonor of a father, in the very thing the law later forbids: the nakedness of thy father thou shalt not uncover. Shem and Japheth showed what honor looks like; Ham showed the opposite and made it public.",
  "judgment": "When Noah awoke and knew what his younger son had done to him, he cursed Canaan, Ham's son: a servant of servants shall he be unto his brethren. Shem and Japheth were blessed in the same breath.",
  "refs": R("Genesis 9:20-27", "Leviticus 18:7", "Exodus 20:12", "Deuteronomy 27:16", "Sirach 3:10-11"),
  "laws": ["1A.5", "6C.2", "6C.7", "12D.8"],
  "topics": ["honour", "naked"],
  "themes": ["dishonor-of-parents", "curse"],
 },
 {
  "slug": "babel",
  "name": "The builders of Babel",
  "era": "Primeval",
  "charge": "Building a tower to make themselves a name and resist being scattered",
  "verdict": "exile",
  "summary": "With one language and one purpose, the whole earth settled in Shinar and built a city and a tower whose top would reach to heaven, to make themselves a name and not be scattered abroad. The Lord came down to see it.",
  "offense": "Direct defiance of the command to replenish the earth, in the form of a monument to human self-sufficiency. The stated aim was a name for themselves, not for God.",
  "judgment": "The Lord confounded their language so they could not understand one another and scattered them over the face of all the earth. The building stopped, and the place was named Babel, confusion.",
  "refs": R("Genesis 11:1-9", "Genesis 9:1", "Wisdom of Solomon 10:5", "Psalms 2:1-4"),
  "laws": ["17G.13", "17D.18", "2H.1"],
  "topics": ["pride", "scattered", "vainglory"],
  "themes": ["pride", "corporate-judgment"],
 },
 {
  "slug": "lots-wife",
  "name": "Lot's wife",
  "era": "Patriarchal",
  "charge": "Looking back toward Sodom against the angel's command",
  "verdict": "death",
  "summary": "The angels told Lot's household to escape for their lives and not look behind them. His wife looked back from behind him and became a pillar of salt. Christ made her a proverb in three words.",
  "offense": "A plain instruction, given for her own life, disregarded. The look back is treated in scripture as a turning of the heart toward what God was destroying.",
  "judgment": "She became a pillar of salt on the plain, and the Wisdom of Solomon says the standing pillar remained as a monument of an unbelieving soul. Remember Lot's wife.",
  "refs": R("Genesis 19:17", "Genesis 19:26", "Luke 17:31-33", "Wisdom of Solomon 10:7"),
  "laws": ["2H.1", "2J.15", "2I.6"],
  "topics": ["obedience", "disconnected"],
  "themes": ["disobedience", "backsliding"],
 },
 {
  "slug": "esau",
  "name": "Esau",
  "era": "Patriarchal",
  "charge": "Despising his birthright; marrying Hittite wives; purposing to kill his brother",
  "verdict": "curse",
  "summary": "The firstborn of Isaac sold his birthright for a single meal, took wives of the Canaanites to his parents' grief, and when the blessing went to Jacob resolved to kill him. The prophets and apostles treat him as the pattern of the profane man.",
  "offense": "Hebrews names it: a fornicator or profane person, as Esau, who for one morsel of meat sold his birthright. His marriages were a grief of mind to Isaac and Rebekah. His hatred of Jacob was murder in the heart.",
  "judgment": "He found no place of repentance, though he sought the blessing with tears. Malachi: I hated Esau, and laid his mountains and his heritage waste. Obadiah sentences his house for its violence against Jacob: the house of Esau shall be for stubble.",
  "refs": R("Genesis 25:29-34", "Genesis 26:34-35", "Genesis 27:41", "Hebrews 12:16-17", "Malachi 1:2-4", "Obadiah 1:10", "Obadiah 1:18", "Romans 9:13"),
  "laws": ["6E.4", "6E.13", "5G.12", "3F", "17H"],
  "topics": ["esau-rejected", "end-of-esau", "intermarrying", "hatred"],
  "themes": ["birthright", "hatred", "intermarriage", "edom"],
 },
 {
  "slug": "shechem",
  "name": "Shechem son of Hamor",
  "era": "Patriarchal",
  "charge": "Defiling Dinah, daughter of Jacob",
  "verdict": "death",
  "summary": "Shechem, prince of the country, saw Dinah, took her, and lay with her and defiled her. He then asked for her in marriage and agreed to circumcision to get her. Her brothers answered with the sword.",
  "offense": "He had wrought folly in Israel in lying with Jacob's daughter, which thing ought not to be done. The law would later require the seducer of an unbetrothed virgin to endow her and the rapist to die.",
  "judgment": "On the third day, while the men of the city were sore, Simeon and Levi killed every male, Hamor and Shechem among them, and took Dinah out of his house. Jacob condemned the manner of it; the brothers answered, should he deal with our sister as with an harlot?",
  "refs": R("Genesis 34:1-2", "Genesis 34:7", "Genesis 34:25-26", "Genesis 34:31", "Deuteronomy 22:28-29", "Exodus 22:16-17"),
  "laws": ["10J.9", "5E.3", "5E.1"],
  "topics": ["sexual-lust", "defile"],
  "themes": ["sexual-immorality", "violence"],
 },
 {
  "slug": "simeon-and-levi",
  "name": "Simeon and Levi at Shechem",
  "era": "Patriarchal",
  "charge": "Deceitful covenant; slaughter of a city for one man's crime",
  "verdict": "curse",
  "summary": "To avenge Dinah, the brothers proposed circumcision to the men of Shechem as a condition of peace, then killed the whole city while it was disabled and plundered it. Jacob never forgot it.",
  "offense": "They answered Shechem and Hamor deceitfully. A covenant made in bad faith, used as a weapon; collective slaughter for an individual's offense; and spoil taken from the dead. Vengeance that belonged to God taken into their own hands.",
  "judgment": "On his deathbed Jacob passed sentence: instruments of cruelty are in their habitations; cursed be their anger, for it was fierce. I will divide them in Jacob and scatter them in Israel. Simeon was absorbed into Judah; Levi had no tribal land.",
  "refs": R("Genesis 34:13", "Genesis 34:25-30", "Genesis 49:5-7", "Joshua 19:1", "Joshua 19:9", "Judith 9:2-4"),
  "laws": ["4D.2", "17M.1", "17A.6", "10A.1", "3J.6"],
  "topics": ["avenge", "anger", "scattered"],
  "themes": ["vengeance", "deceit", "violence"],
 },
 {
  "slug": "reuben",
  "name": "Reuben",
  "era": "Patriarchal",
  "charge": "Lying with Bilhah, his father's concubine",
  "verdict": "curse",
  "summary": "Jacob's firstborn went up to his father's bed and lay with Bilhah, and Israel heard of it. Nothing more is said until the deathbed, where it cost Reuben the birthright.",
  "offense": "The nakedness of thy father's wife shalt thou not uncover, later a capital offense in the law. Chronicles states the consequence plainly: because he defiled his father's bed, his birthright was given to the sons of Joseph.",
  "judgment": "Unstable as water, thou shalt not excel. The double portion went to Joseph, the rule to Judah. Reuben's tribe never produced a judge, prophet, or king.",
  "refs": R("Genesis 35:22", "Genesis 49:3-4", "1 Chronicles 5:1-2", "Leviticus 18:8", "Leviticus 20:11", "Deuteronomy 27:20"),
  "laws": ["6E.13", "10J.2", "5G", "6C.2"],
  "topics": ["firstborn", "sexual-lust"],
  "themes": ["birthright", "sexual-immorality", "dishonor-of-parents"],
 },
 {
  "slug": "er-and-onan",
  "name": "Er and Onan",
  "era": "Patriarchal",
  "charge": "Wickedness before the Lord; refusing to raise up seed to a dead brother",
  "verdict": "death",
  "summary": "Judah's firstborn Er was wicked in the sight of the Lord and the Lord slew him. His brother Onan, told to raise up seed to Er by Tamar, deliberately spilled his seed rather than give his brother an heir, and the Lord slew him also.",
  "offense": "Er's sin is unnamed; the verdict is not. Onan's is precise: he knew the seed would not be his, and each time he went in to Tamar he prevented conception. He took the wife but refused the duty, cheating the dead and the widow.",
  "judgment": "Both died at the Lord's hand, not by any court. The duty Onan refused was later written into the law of the kinsman: the firstborn she bears shall succeed in the name of his brother that is dead.",
  "refs": R("Genesis 38:6-10", "Deuteronomy 25:5-10", "Ruth 4:5-6", "Matthew 22:24"),
  "laws": ["5D.7", "6E.14", "3J.6", "17L"],
  "topics": ["marriage", "wife", "sin"],
  "themes": ["marriage", "selfishness"],
 },
 {
  "slug": "josephs-brothers",
  "name": "Joseph's brothers",
  "era": "Patriarchal",
  "charge": "Conspiracy to murder; selling a brother; deceiving their father with a bloodied coat",
  "verdict": "spared",
  "summary": "Ten brothers plotted to kill Joseph out of envy, then sold him to the Ishmaelites for twenty pieces of silver and dipped his coat in goat's blood so Jacob would think him dead. Twenty years later they stood before him in Egypt.",
  "offense": "Envy became conspiracy; conspiracy became man-stealing, which the law makes capital; and the cover-up was a lie that broke their father's heart for two decades. In Egypt they confessed among themselves: we are verily guilty concerning our brother.",
  "judgment": "The famine and Joseph's testing brought the guilt to the surface. Joseph forgave them: ye thought evil against me, but God meant it unto good. They were spared, and the reconciliation is the founding story of the twelve tribes.",
  "refs": R("Genesis 37:18-28", "Genesis 37:31-35", "Genesis 42:21-22", "Genesis 45:4-8", "Genesis 50:15-21", "Exodus 21:16", "Deuteronomy 24:7", "Acts 7:9-10"),
  "laws": ["10C.1", "17B.6", "3E.1", "3J.6", "3B"],
  "topics": ["envy", "lying", "forgiveness"],
  "themes": ["envy", "deceit", "forgiveness"],
 },
 {
  "slug": "pharaoh",
  "name": "Pharaoh of the Exodus",
  "era": "Egypt",
  "charge": "Oppressing Israel; drowning their sons; refusing the Lord's command",
  "verdict": "plague",
  "summary": "The king who did not know Joseph enslaved Israel, ordered their male infants thrown into the river, and when Moses came in the Lord's name answered, Who is the Lord? He hardened his heart through ten plagues and drowned in the sea he pursued Israel into.",
  "offense": "Forced labor with rigor, infanticide by decree, contempt for the Name, and repeated broken promises: each time the plague lifted he hardened his heart and would not let the people go. Paul says he was raised up for this, that God's name might be declared in all the earth.",
  "judgment": "Ten plagues on Egypt ending in the death of every firstborn, Pharaoh's included. Then his army in the Red Sea: the waters returned and covered the chariots and horsemen; there remained not so much as one of them. Wisdom says a strange death.",
  "refs": R("Exodus 1:8-14", "Exodus 1:22", "Exodus 5:2", "Exodus 7:13", "Exodus 9:12", "Exodus 12:29-30", "Exodus 14:27-28", "Romans 9:17", "Wisdom of Solomon 19:1-5", "Wisdom of Solomon 18:5"),
  "laws": ["10A.2", "21B.16", "8A.24", "2K.2", "17G.13", "17F"],
  "topics": ["egypt", "ramses", "pride", "stiff-necked"],
  "themes": ["pride", "oppression", "corporate-judgment", "egypt"],
 },
 {
  "slug": "moses-uncircumcised-son",
  "name": "Moses and the uncircumcised son",
  "era": "Egypt",
  "charge": "Neglecting the sign of the covenant in his own house",
  "verdict": "reprieve",
  "summary": "On the road to Egypt to deliver Israel, the Lord met Moses at the inn and sought to kill him. Zipporah took a sharp stone, circumcised her son, and cast the foreskin at his feet. So he let him go.",
  "offense": "The covenant with Abraham required every male circumcised on the eighth day; the uncircumcised man-child was to be cut off from his people. The deliverer of Israel had not kept it in his own household, and it had to be set right before he could speak for God to Pharaoh.",
  "judgment": "The death sentence was stayed the moment the neglect was remedied. The narrative gives no further comment; the priority is the comment.",
  "refs": R("Exodus 4:24-26", "Genesis 17:10-14", "Joshua 5:2-5"),
  "laws": ["14F.9", "2H.1", "6A.5"],
  "topics": ["circumcision", "obedience", "family-order"],
  "themes": ["covenant", "leadership", "disobedience"],
 },
 {
  "slug": "amalek",
  "name": "Amalek",
  "era": "Egypt",
  "charge": "Attacking Israel's stragglers on the way out of Egypt",
  "verdict": "curse",
  "summary": "Amalek came out against Israel at Rephidim and, as Deuteronomy records, smote the hindmost, the feeble and faint and weary, and feared not God. Israel prevailed while Moses' hands were held up.",
  "offense": "An unprovoked attack on a nation just out of bondage, aimed at those least able to defend themselves. No fear of God, no cause of war.",
  "judgment": "The Lord swore war with Amalek from generation to generation and commanded that his remembrance be blotted out from under heaven. Saul was sent to execute it and failed; the sentence passed to David and was finished under Hezekiah.",
  "refs": R("Exodus 17:8-16", "Deuteronomy 25:17-19", "1 Samuel 15:2-3", "1 Samuel 30:17-18", "1 Chronicles 4:42-43", "Numbers 24:20"),
  "laws": ["22A.19", "22E.4", "15D", "22D.8"],
  "topics": ["our-enemies", "perpetual-enmity", "judgement-of-nations"],
  "themes": ["war", "oppression", "corporate-judgment"],
 },
]
