from cases_lib import R

CASES = [
 {
  "slug": "nebuchadnezzar",
  "name": "Nebuchadnezzar",
  "era": "Exile and Return",
  "charge": "Pride: is not this great Babylon, that I have built?",
  "verdict": "temporal",
  "summary": "Warned by Daniel's interpretation of the tree dream to break off his sins by righteousness and his iniquities by showing mercy to the poor, the king walked on his palace roof twelve months later and took the credit for the empire. While the word was in his mouth a voice fell from heaven.",
  "offense": "The beginning of pride is when one departeth from God, says Sirach; Nebuchadnezzar's was the claim of the builder over the Builder. He had already burned three men for refusing his image and been told whose hand had given him the kingdom.",
  "judgment": "Driven from men, he ate grass as oxen, his body wet with dew, his hair grown like eagles' feathers and his nails like birds' claws, until seven times passed and he lifted up his eyes to heaven. His reason returned; his kingdom was restored; and he wrote the confession himself: those that walk in pride he is able to abase.",
  "refs": R("Daniel 4:27-33", "Daniel 4:34-37", "Daniel 5:18-21", "Daniel 3:15", "Jeremiah 27:6-7", "Sirach 10:12-13"),
  "laws": ["17G.13", "17G.19", "2M", "15B.11", "17D.17"],
  "topics": ["pride", "humility", "power-over-nations"],
  "themes": ["pride", "kingship", "repentance"],
 },
 {
  "slug": "belshazzar",
  "name": "Belshazzar",
  "era": "Exile and Return",
  "charge": "Drinking from the temple vessels and praising the gods of gold and silver",
  "verdict": "death",
  "summary": "At a feast for a thousand lords, Belshazzar called for the gold and silver vessels Nebuchadnezzar had taken from the house of God in Jerusalem, drank wine from them with his wives and concubines, and praised the gods of gold, silver, brass, iron, wood, and stone. Fingers of a man's hand wrote on the plaster.",
  "offense": "Daniel's indictment: thou hast lifted up thyself against the Lord of heaven, and the God in whose hand thy breath is, and whose are all thy ways, hast thou not glorified. He knew what had happened to his father and humbled not his heart.",
  "judgment": "Mene, mene, tekel, upharsin: numbered, weighed and found wanting, divided. In that night was Belshazzar the king of the Chaldeans slain, and Darius the Median took the kingdom.",
  "refs": R("Daniel 5:1-4", "Daniel 5:22-24", "Daniel 5:25-31", "Ezra 1:7", "Isaiah 47:5-11", "Jeremiah 51:39"),
  "laws": ["2D.3", "2D.10", "17G.13", "2M", "12G.12"],
  "topics": ["idolatry", "wood-and-stone", "pride", "drinking"],
  "themes": ["idolatry", "pride", "irreverence", "kingship"],
 },
 {
  "slug": "daniels-accusers",
  "name": "Daniel's accusers",
  "era": "Exile and Return",
  "charge": "Conspiring by law against an innocent man",
  "verdict": "death",
  "summary": "Finding no fault in Daniel except concerning the law of his God, the presidents and princes flattered Darius into signing a decree that no one might petition any god or man for thirty days, then caught Daniel praying. The king labored till sunset to deliver him and could not.",
  "offense": "A snare built from the machinery of law itself: a statute designed to make righteousness a crime, and a king manipulated into executing it. Deuteronomy's rule for a false witness is that what he thought to do to his brother be done to him.",
  "judgment": "Daniel came out of the den without a mark because he believed in his God. The king commanded those who had accused him, with their children and wives, cast into the den; the lions broke all their bones before they reached the bottom.",
  "refs": R("Daniel 6:4-9", "Daniel 6:10-17", "Daniel 6:21-24", "Deuteronomy 19:16-19", "Psalms 7:15-16", "Proverbs 26:27"),
  "laws": ["4E.4", "4E.13", "4F.13", "3J.12", "3H", "2P.2"],
  "topics": ["witnesses", "persecution", "justice"],
  "themes": ["false-witness", "persecution", "retribution"],
 },
 {
  "slug": "haman",
  "name": "Haman the Agagite",
  "era": "Exile and Return",
  "charge": "Plotting the destruction of all the Jews; building a gallows for Mordecai",
  "verdict": "death",
  "summary": "Because one Jew would not bow to him, Haman sought to destroy all the Jews in the empire, bought the decree with ten thousand talents, cast lots for the day, and built a gallows fifty cubits high for Mordecai. Esther exposed him at her second banquet.",
  "offense": "Genocide from wounded pride, purchased by bribe on a false report to the king: their laws are diverse from all people, neither keep they the king's laws. The Agagite's name recalls Amalek, whose remembrance Israel was commanded to blot out.",
  "judgment": "So they hanged Haman on the gallows that he had prepared for Mordecai; his ten sons followed. Whoso diggeth a pit shall fall therein. The feast of Purim keeps the memory of the lot that turned.",
  "refs": R("Esther 3:1-2", "Esther 3:5-6", "Esther 3:8-9", "Esther 5:14", "Esther 7:6-10", "Esther 9:10", "Esther 9:24-26", "Psalms 7:15-16", "Deuteronomy 25:19", "Esther (Greek) 16:10-14"),
  "laws": ["10A.2", "17G.13", "4E.1", "4C.2", "17M.7", "19D.4", "2P.2"],
  "topics": ["purim", "pride", "hatred", "our-enemies"],
  "themes": ["pride", "hatred", "persecution", "retribution"],
 },
 {
  "slug": "jobs-friends",
  "name": "Job's three friends",
  "era": "Patriarchal",
  "charge": "Speaking of God the thing that is not right; condemning the righteous",
  "verdict": "restitution",
  "summary": "Eliphaz, Bildad, and Zophar came to comfort Job and spent thirty chapters insisting his suffering proved hidden sin. Eliphaz went so far as to invent the sins: thou hast taken a pledge from thy brother for nought, and stripped the naked of their clothing. When the Lord answered out of the whirlwind, he answered them too.",
  "offense": "Job had asked them earlier: will ye speak wickedly for God? and talk deceitfully for him? They had judged a man on suspicion, condemned the just, and defended God with false accusations against his servant. Job's cause was right; their theology was not.",
  "judgment": "My wrath is kindled against thee and against thy two friends, for ye have not spoken of me the thing that is right, as my servant Job hath. They were ordered to bring seven bullocks and seven rams to Job and have him pray for them, lest I deal with you after your folly. He did, and the Lord accepted Job.",
  "refs": R("Job 42:7-9", "Job 13:7-10", "Job 22:5-10", "Job 4:7-8", "Job 8:5-6", "Job 11:6"),
  "laws": ["4F.13", "12E.7", "3E.1", "3K", "4E.6", "3L.6"],
  "topics": ["judging", "comfort", "respect-of-persons", "suffering"],
  "themes": ["false-witness", "partiality", "restitution"],
 },
 {
  "slug": "jonah",
  "name": "Jonah",
  "era": "Divided Kingdom",
  "charge": "Fleeing from the presence of the Lord to avoid his commission; anger at God's mercy",
  "verdict": "reprieve",
  "summary": "Told to go east to Nineveh, Jonah bought passage west to Tarshish. A storm, a lot, and a fish brought him back. He preached, the city repented, and he was angry enough to die because God spared it. A gourd, a worm, and a wind finished the lesson.",
  "offense": "Refusal of a prophet's commission, with the reason given afterward in his own words: I knew that thou art a gracious God, and merciful. He would rather drown than see Nineveh forgiven. Then anger without cause, twice, at the mercy he himself had received.",
  "judgment": "Three days and nights in the belly of the fish, out of which he prayed and was vomited on dry land, and the word of the Lord came the second time. The book ends on God's question, unanswered: should not I spare Nineveh? Christ made his three days the sign of the resurrection.",
  "refs": R("Jonah 1:1-4", "Jonah 1:12", "Jonah 1:15-17", "Jonah 2:1", "Jonah 2:10", "Jonah 3:1-3", "Jonah 4:1-4", "Jonah 4:9-11", "Matthew 12:40", "Tobit 14:4"),
  "laws": ["2H.1", "13D", "17A.3", "17A.9", "3K"],
  "topics": ["obedience", "mercy", "anger", "repentance"],
  "themes": ["disobedience", "mercy", "anger", "leadership"],
 },
 {
  "slug": "nineveh-repents",
  "name": "Nineveh under Jonah",
  "era": "Divided Kingdom",
  "charge": "Wickedness come up before the Lord",
  "verdict": "spared",
  "summary": "Yet forty days, and Nineveh shall be overthrown. The people believed God, proclaimed a fast, and put on sackcloth from the greatest to the least; the king rose from his throne, sat in ashes, and decreed that man and beast cry mightily unto God and turn from the violence in their hands.",
  "offense": "The charge is given in one line, their wickedness is come up before me, and Nahum a century later spells out what Assyria's wickedness was: a bloody city, full of lies and robbery, whose prey departeth not.",
  "judgment": "God saw their works, that they turned from their evil way, and repented of the evil that he had said he would do unto them. Jeremiah states the rule: if that nation turn from their evil, I will repent of the evil I thought to do. Christ: the men of Nineveh shall rise in judgment with this generation and condemn it.",
  "refs": R("Jonah 1:2", "Jonah 3:4-10", "Jonah 4:11", "Jeremiah 18:7-8", "Matthew 12:41", "Luke 11:32"),
  "laws": ["2L.1", "2L.5", "2L.12", "14E.6", "14E.7", "2P.10"],
  "topics": ["repentance", "fasting", "mercy", "judgement-of-nations"],
  "themes": ["repentance", "mercy", "corporate-judgment"],
 },
 {
  "slug": "nineveh-destroyed",
  "name": "Nineveh under Nahum",
  "era": "Divided Kingdom",
  "charge": "A bloody city, full of lies and robbery, mistress of witchcrafts",
  "verdict": "death",
  "summary": "The repentance of Jonah's day did not last. Nahum's burden against Nineveh charges the city with blood, plunder, harlotries, and witchcrafts by which she sold nations; the Lord is slow to anger, and will not at all acquit the wicked.",
  "offense": "Assyria had been the rod of God's anger against Israel and then gloried in its own hand. Zephaniah names the heart of it: this is the rejoicing city that dwelt carelessly, that said in her heart, I am, and there is none beside me.",
  "judgment": "The gates of the rivers shall be opened, and the palace dissolved. Nineveh is laid waste; who will bemoan her? There is no healing of thy bruise. Tobit records hearing of its destruction by Nebuchadnezzar and Ahasuerus before he died, and rejoicing over it.",
  "refs": R("Nahum 1:1-3", "Nahum 1:14", "Nahum 2:6-10", "Nahum 3:1-7", "Nahum 3:19", "Zephaniah 2:13-15", "Tobit 14:15", "Isaiah 10:5-12"),
  "laws": ["10A.2", "3J.12", "2G.3", "17G.13", "18B.1", "2P.3"],
  "topics": ["judgement-of-nations", "the-wicked", "pride"],
  "themes": ["corporate-judgment", "pride", "bloodshed"],
 },
 {
  "slug": "edom",
  "name": "Edom, in the day of his brother",
  "era": "Divided Kingdom",
  "charge": "Standing on the other side when strangers carried Jacob away; rejoicing over Judah's fall; cutting off those that escaped",
  "verdict": "curse",
  "summary": "When Babylon took Jerusalem, Esau's descendants looked on, entered the gate in the day of calamity, laid hands on the substance, stood in the crossway to cut off the fugitives, and delivered up those that remained. Psalm 137 remembers them shouting, rase it, rase it, even to the foundation.",
  "offense": "Obadiah: for thy violence against thy brother Jacob shame shall cover thee. Amos: he did pursue his brother with the sword, and did cast off all pity, and his anger did tear perpetually. The law had forbidden Israel to abhor an Edomite, for he is thy brother; Edom kept no such law.",
  "judgment": "As thou hast done, it shall be done unto thee: thy reward shall return upon thine own head. The house of Jacob shall be a fire, and the house of Joseph a flame, and the house of Esau for stubble; there shall not be any remaining of the house of Esau. Malachi: they shall build, but I will throw down.",
  "refs": R("Obadiah 1:10-15", "Obadiah 1:18", "Ezekiel 25:12-14", "Ezekiel 35:5-9", "Amos 1:11-12", "Psalms 137:7", "Malachi 1:2-4", "Deuteronomy 23:7", "Lamentations 4:21-22"),
  "laws": ["3F", "17M.7", "22A.13", "3K", "2P.2", "15B.6"],
  "topics": ["enemy-brother", "end-of-esau", "esau-rejected", "judgement-of-nations"],
  "themes": ["edom", "hatred", "corporate-judgment"],
 },
 {
  "slug": "the-prince-of-tyre",
  "name": "The prince of Tyre",
  "era": "Divided Kingdom",
  "charge": "Saying, I am a God, I sit in the seat of God",
  "verdict": "death",
  "summary": "Ezekiel's word to the ruler of the merchant city: because thine heart is lifted up, and thou hast said, I am a God, in the midst of the seas; yet thou art a man, and not God. Wiser than Daniel, richer by his traffick, and undone by both.",
  "offense": "Self-deification on the strength of trade. By the multitude of thy merchandise they have filled the midst of thee with violence, and thou hast sinned. Tyre had also rejoiced at Jerusalem's fall: aha, she is broken, I shall be replenished.",
  "judgment": "They shall bring thee down to the pit, and thou shalt die the deaths of them that are slain in the midst of the seas. Wilt thou yet say before him that slayeth thee, I am God? Nebuchadnezzar besieged the mainland city; Alexander finished the island.",
  "refs": R("Ezekiel 28:2-10", "Ezekiel 28:16-19", "Ezekiel 26:2-4", "Amos 1:9-10", "Isaiah 23:8-9", "Zechariah 9:3-4"),
  "laws": ["17G.13", "17G.19", "2D.1", "16D", "3J.15", "17D.6"],
  "topics": ["pride", "vainglory", "judgement-of-nations", "money"],
  "themes": ["pride", "corporate-judgment"],
 },
 {
  "slug": "the-strange-wives",
  "name": "The returned exiles who married strange wives",
  "era": "Exile and Return",
  "charge": "Mingling the holy seed with the peoples of the lands",
  "verdict": "restitution",
  "summary": "Ezra was told that the people, priests, and Levites had taken wives of the Canaanites, Hittites, Ammonites, Moabites, and Egyptians, and that the princes and rulers had been chief in the trespass. He rent his garment and sat astonished until the evening sacrifice. A generation later Nehemiah found children who could not speak the Jews' language.",
  "offense": "Deuteronomy 7 was the statute: neither shalt thou make marriages with them, for they will turn away thy son from following me. Ezra's prayer cites it and names the reason it cut deeper after the exile: after all that is come upon us for our evil deeds, should we again break thy commandments? Nehemiah pointed at Solomon.",
  "judgment": "The people confessed, and by covenant separated themselves from the strange wives and from such as were born of them, case by case before the elders and judges of every city, over three months. First Esdras preserves the same proceedings. Nehemiah contended with the later offenders, smote certain of them, and chased away the priest who had married Sanballat's daughter.",
  "refs": R("Ezra 9:1-3", "Ezra 9:10-14", "Ezra 10:2-5", "Ezra 10:10-12", "Ezra 10:16-19", "Nehemiah 13:23-28", "1 Esdras 8:69-71", "1 Esdras 9:7-10", "Deuteronomy 7:3-4", "Malachi 2:11-12"),
  "laws": ["5G.12", "5G.13", "5G.14", "2L.6", "2L.12", "20B.14"],
  "topics": ["intermarrying", "holy-seed", "separate", "mixed-multitudes"],
  "themes": ["intermarriage", "restitution", "repentance"],
 },
 {
  "slug": "the-usurers-of-nehemiah",
  "name": "The nobles who exacted usury of their brethren",
  "era": "Exile and Return",
  "charge": "Lending on interest; taking brethren's lands and children for debt",
  "verdict": "restitution",
  "summary": "During the rebuilding of the wall, the poor cried out that they had mortgaged their fields and vineyards and sold their sons and daughters into bondage to pay the king's tribute and the nobles' interest. Nehemiah was very angry and set a great assembly against the nobles and rulers.",
  "offense": "Ye exact usury, every one of his brother. The law forbids taking usury from a poor brother or holding him as a bondservant; Nehemiah adds that they were buying back Jews sold to the heathen while their own class was selling them again.",
  "judgment": "Restore, I pray you, to them, even this day, their lands, their vineyards, their oliveyards, and their houses, also the hundredth part of the money. They said, we will restore them, and swore before the priests. Nehemiah shook his lap: so God shake out every man that performeth not this promise.",
  "refs": R("Nehemiah 5:1-13", "Exodus 22:25", "Leviticus 25:35-37", "Leviticus 25:39-43", "Deuteronomy 23:19-20", "Ezekiel 18:8"),
  "laws": ["16C.1", "16C.5", "16C.4", "15B.6", "21B.4", "19C.20"],
  "topics": ["money", "poor", "our-servants"],
  "themes": ["usury", "oppression", "restitution"],
 },
 {
  "slug": "the-sabbath-traders",
  "name": "The Sabbath traders of Jerusalem and Tyre",
  "era": "Exile and Return",
  "charge": "Treading winepresses, bringing in sheaves, and selling fish and wares on the Sabbath",
  "verdict": "reprieve",
  "summary": "Nehemiah saw men of Judah treading winepresses and loading asses on the Sabbath, and Tyrian merchants selling fish in Jerusalem on the holy day. He testified against the nobles, shut the gates at dusk, set his own servants to guard them, and threatened to lay hands on the merchants who camped outside.",
  "offense": "Did not your fathers thus, and did not our God bring all this evil upon us, and upon this city? Yet ye bring more wrath upon Israel by profaning the sabbath. Jeremiah had named Sabbath burdens through those very gates as a cause of the city's burning.",
  "judgment": "The merchants lodged outside the wall once or twice; Nehemiah warned them, and from that time forth came they no more on the sabbath. He commanded the Levites to cleanse themselves and keep the gates. Remember me, O my God, concerning this also.",
  "refs": R("Nehemiah 13:15-22", "Jeremiah 17:21-23", "Jeremiah 17:27", "Amos 8:4-6", "Exodus 20:8-10", "Isaiah 58:13"),
  "laws": ["9C.6", "9C.8", "9C.2", "10B", "9C.12"],
  "topics": ["sabbath", "seventh-day", "money"],
  "themes": ["sabbath", "reproof"],
 },
 {
  "slug": "tobiah-and-eliashib",
  "name": "Eliashib and Tobiah the Ammonite",
  "era": "Exile and Return",
  "charge": "Lodging an Ammonite enemy in a chamber of the house of God; a priest's house allied to Sanballat",
  "verdict": "exile",
  "summary": "While Nehemiah was away, Eliashib the priest, allied to Tobiah by marriage, cleared out a storechamber of the temple that had held the tithe and the vessels and gave it to the Ammonite who had mocked and opposed the wall. Nehemiah returned and threw Tobiah's household stuff out.",
  "offense": "Deuteronomy had barred the Ammonite from the congregation of the Lord for ever, and this one was an active enemy. The law also required the priests to keep the charge of the sanctuary and the Levites to be supplied from it; instead the tithe was displaced to house him. The high priest's grandson had married Sanballat's daughter.",
  "judgment": "It grieved me sore: therefore I cast forth all the household stuff of Tobiah out of the chamber, and commanded the chambers cleansed and the vessels and the tithe brought back. The son-in-law of Sanballat he chased from him. Remember them, O my God, because they have defiled the priesthood.",
  "refs": R("Nehemiah 13:4-9", "Nehemiah 13:28-29", "Nehemiah 6:17-19", "Nehemiah 2:19-20", "Nehemiah 4:3", "Deuteronomy 23:3-4", "Nehemiah 13:1-3"),
  "laws": ["20D.4", "11C.1", "20B.14", "20A.15", "2G.6", "20E.2"],
  "topics": ["separate", "strangers", "trust-no-enemy", "our-enemies"],
  "themes": ["priesthood", "foreign-alliance", "reproof"],
 },
]
