from cases_lib import R

CASES = [
 {
  "slug": "manna-hoarders",
  "name": "The manna hoarders",
  "era": "Wilderness",
  "charge": "Keeping manna overnight; going out to gather on the Sabbath",
  "verdict": "temporal",
  "summary": "Told to gather only a day's portion, some kept manna until morning and it bred worms and stank. Told there would be none on the seventh day, some went out to gather anyway and found nothing.",
  "offense": "Distrust dressed as prudence. The first was hoarding against a promise of daily provision; the second was Sabbath-breaking against a double portion already given. Moses was angry at the one, and the Lord at the other: how long refuse ye to keep my commandments?",
  "judgment": "The hoarded bread rotted. The Sabbath gatherers went out and found nothing, and were rebuked. Small, exact, and recorded so the next test would be understood.",
  "refs": R("Exodus 16:16-20", "Exodus 16:22-30", "Matthew 6:11", "Matthew 6:34"),
  "laws": ["9C.11", "9C.3", "2H.1", "17C.2"],
  "topics": ["sabbath", "trust-god", "obedience"],
  "themes": ["sabbath", "distrust", "disobedience"],
 },
 {
  "slug": "taberah-and-kibroth-hattaavah",
  "name": "The complainers at Taberah and the lusters at Kibroth-hattaavah",
  "era": "Wilderness",
  "charge": "Murmuring against the Lord; lusting after flesh and despising the manna",
  "verdict": "plague",
  "summary": "The people complained and the fire of the Lord burned in the outskirts of the camp. Days later the mixed multitude fell to lusting and Israel wept for the meat of Egypt. Quail came, and with the quail a plague.",
  "offense": "Contempt for God's provision. They said the manna had dried up their souls and named the fish and cucumbers of Egypt as what they missed, forgetting the brick-kilns. Psalm 78 calls it tempting God in their heart and speaking against him.",
  "judgment": "Fire consumed the complainers at Taberah until Moses prayed. At Kibroth-hattaavah, while the flesh was yet between their teeth, the Lord smote the people with a very great plague; the place is named for the graves of the lusters. Paul: these things were our examples.",
  "refs": R("Numbers 11:1-3", "Numbers 11:4-6", "Numbers 11:31-34", "Psalms 78:26-31", "Psalms 106:14-15", "1 Corinthians 10:6"),
  "laws": ["12C.6", "2O", "17C.2", "14D.11"],
  "topics": ["murmuring", "gluttony", "mixed-multitudes"],
  "themes": ["murmuring", "lust", "corporate-judgment"],
 },
 {
  "slug": "the-ten-spies",
  "name": "The ten spies",
  "era": "Wilderness",
  "charge": "Bringing an evil report; making the congregation to murmur",
  "verdict": "plague",
  "summary": "Twelve men searched Canaan forty days. Ten came back and told the people the land eats its inhabitants and the giants made them as grasshoppers. Caleb and Joshua said the Lord would bring them in. The people believed the ten.",
  "offense": "They did not deny the land was good; they denied that God could give it. Their report turned a nation from faith to fear in one night and had the people ready to choose a captain back to Egypt and stone the two who believed.",
  "judgment": "The men that brought up the evil report died by the plague before the Lord. Caleb and Joshua lived, and forty-five years later Caleb took his mountain.",
  "refs": R("Numbers 13:27-33", "Numbers 14:1-4", "Numbers 14:6-10", "Numbers 14:36-38", "Deuteronomy 1:26-28", "Joshua 14:6-12", "1 Maccabees 2:55-56"),
  "laws": ["4E.1", "2B", "22D.1", "12E.2"],
  "topics": ["believe", "fear", "giants", "murmuring"],
  "themes": ["unbelief", "false-witness", "murmuring"],
 },
 {
  "slug": "the-wilderness-generation",
  "name": "The generation that died in the wilderness",
  "era": "Wilderness",
  "charge": "Ten provocations; unbelief at Kadesh-barnea",
  "verdict": "death",
  "summary": "Those numbered from twenty years old who had seen the signs in Egypt and at the sea, and had tempted the Lord ten times, were sentenced at Kadesh to wander until every one of them had fallen in the wilderness. Only Caleb and Joshua of that generation entered the land.",
  "offense": "Not one act but a pattern: at the sea, at Marah, over the manna, at Rephidim, at the calf, at Taberah, at Kibroth-hattaavah, and finally refusing the land God had sworn to give. Hebrews names the root: they could not enter in because of unbelief. Then, told the sentence, they presumed to go up anyway and were beaten back.",
  "judgment": "Forty years, a year for each day of the search. Your carcases shall fall in this wilderness. Sirach counts them: the six hundred thousand footmen gathered together in the hardness of their hearts, whom he pitied not.",
  "refs": R("Numbers 14:22-23", "Numbers 14:28-35", "Numbers 14:40-45", "Deuteronomy 1:34-36", "Psalms 95:8-11", "Hebrews 3:16-19", "1 Corinthians 10:5", "Jude 1:5", "Sirach 16:10"),
  "laws": ["2B", "2H.1", "17F", "2I.4", "2H.3"],
  "topics": ["tempt-god", "believe", "stiff-necked", "wilderness"],
  "themes": ["unbelief", "corporate-judgment", "murmuring"],
 },
 {
  "slug": "the-fiery-serpents",
  "name": "Israel and the fiery serpents",
  "era": "Wilderness",
  "charge": "Speaking against God and against Moses; loathing the bread from heaven",
  "verdict": "plague",
  "summary": "Discouraged on the way around Edom, the people spoke against God and Moses: there is no bread, no water, and our soul loatheth this light bread. The Lord sent fiery serpents, and much people of Israel died.",
  "offense": "Contempt for the provision and the deliverer in a single complaint. Paul cites it: neither let us tempt Christ, as some of them also tempted, and were destroyed of serpents.",
  "judgment": "The serpents bit and many died. When the people confessed, Moses made a serpent of brass on a pole; whoever looked, lived. The Wisdom of Solomon says they were troubled for a small season to be admonished, saved not by the thing they saw but by God. Christ took it as the figure of his own lifting up.",
  "refs": R("Numbers 21:4-9", "1 Corinthians 10:9", "John 3:14-15", "Wisdom of Solomon 16:5-7", "2 Kings 18:4"),
  "laws": ["2O", "2K.2", "2H.1", "2P.18"],
  "topics": ["murmuring", "serpent-lifted", "tempt-god"],
  "themes": ["murmuring", "corporate-judgment", "repentance"],
 },
 {
  "slug": "balaam",
  "name": "Balaam",
  "era": "Wilderness",
  "charge": "Divination for hire; counseling Moab to seduce Israel into idolatry",
  "verdict": "death",
  "summary": "Hired by Balak to curse Israel, Balaam could only bless. So he taught Balak a surer way: draw Israel into fornication and the feasts of Baal-peor and let their own God judge them. It worked, and it killed him.",
  "offense": "A prophet who loved the wages of unrighteousness, pressed God for permission he had already been refused, and when he could not curse the people, arranged their sin. Christ names the doctrine of Balaam as still at work in the churches.",
  "judgment": "Balaam the son of Beor they slew with the sword when Israel went against Midian, together with the kings of Midian. Jude: they ran greedily after the error of Balaam for reward, and perished.",
  "refs": R("Numbers 22:5-7", "Numbers 22:12", "Numbers 22:20-22", "Numbers 31:8", "Numbers 31:16", "Deuteronomy 23:4-5", "Joshua 13:22", "2 Peter 2:15-16", "Jude 1:11", "Revelation 2:14", "Micah 6:5"),
  "laws": ["2G.4", "4C.1", "2I.2", "10F.4", "20F.1", "20D.10"],
  "topics": ["divination", "bribe", "false-prophets", "spiritual-fornication"],
  "themes": ["false-prophets", "occult", "covetousness", "enticement"],
 },
 {
  "slug": "baal-peor",
  "name": "Israel at Baal-peor",
  "era": "Wilderness",
  "charge": "Fornication with the daughters of Moab; sacrificing to their gods",
  "verdict": "plague",
  "summary": "In Shittim the people began to commit whoredom with the daughters of Moab, who called them to the sacrifices of their gods. Israel ate, bowed down, and joined himself unto Baal-peor. The plague took twenty-four thousand.",
  "offense": "Balaam's counsel executed: sexual sin as the door to idol worship. Hosea says they went to Baal-peor and separated themselves unto that shame, and their abominations were according as they loved. Psalm 106 adds that they ate the sacrifices of the dead.",
  "judgment": "The Lord commanded the heads of the offenders hanged up before the sun, and the judges to slay every man his men that were joined to Baal-peor. A plague ran through the camp until Phinehas stayed it. Paul: fell in one day three and twenty thousand.",
  "refs": R("Numbers 25:1-5", "Numbers 25:9", "Numbers 31:16", "Deuteronomy 4:3", "Psalms 106:28-29", "Hosea 9:10", "1 Corinthians 10:8"),
  "laws": ["10F.1", "5E.1", "2G.6", "5G.12", "2D.12", "20D.10"],
  "topics": ["idolatry", "spiritual-fornication", "intermarrying", "compromise"],
  "themes": ["idolatry", "sexual-immorality", "corporate-judgment", "enticement"],
 },
 {
  "slug": "zimri-and-cozbi",
  "name": "Zimri and Cozbi",
  "era": "Wilderness",
  "charge": "Bringing a Midianite woman into the camp in the sight of the congregation",
  "verdict": "death",
  "summary": "While the congregation wept at the tabernacle door over the plague, Zimri, a prince of Simeon, walked a Midianite princess past them into his tent. Phinehas followed with a javelin and thrust them both through.",
  "offense": "Open defiance of the judgment in progress: not hidden sin but sin paraded before Moses and the mourning assembly, by a leader, with the daughter of a chief of Midian. The offense was against the whole camp's standing before God.",
  "judgment": "Both died on the javelin, and the plague was stayed. God gave Phinehas a covenant of everlasting priesthood because he was zealous for his God and made an atonement. Sirach ranks him third in glory; the Maccabees claim him as father.",
  "refs": R("Numbers 25:6-8", "Numbers 25:10-15", "Psalms 106:30-31", "Sirach 45:23-24", "1 Maccabees 2:54"),
  "laws": ["5G.12", "10F.1", "5E.1", "19E", "8A.24"],
  "topics": ["intermarrying", "idolatry", "exposed"],
  "themes": ["sexual-immorality", "intermarriage", "leadership"],
 },
 {
  "slug": "the-gibeonites",
  "name": "The Gibeonites, and Israel's oath",
  "era": "Conquest",
  "charge": "Obtaining a covenant by fraud; Israel making it without asking counsel of the Lord",
  "verdict": "curse",
  "summary": "The Gibeonites came to Joshua in old clothes with moldy bread claiming to be from a far country, and Israel made peace with them. Three days later the fraud was found out. The oath stood anyway.",
  "offense": "On the Gibeonite side, a treaty by deception. On Israel's side, the text is explicit: the men took of their victuals, and asked not counsel at the mouth of the Lord. The covenant forbidden with the inhabitants of the land was made through negligence.",
  "judgment": "Because the princes had sworn by the Lord, the Gibeonites could not be killed, but were made hewers of wood and drawers of water for the congregation and the altar. Centuries later, when Saul broke that oath, God sent famine on Israel for it.",
  "refs": R("Joshua 9:3-6", "Joshua 9:14-15", "Joshua 9:18-21", "Joshua 9:22-27", "Deuteronomy 20:10-18", "Exodus 23:32", "2 Samuel 21:1-2"),
  "laws": ["11C.1", "22A.7", "4D.5", "4D.2", "3J.6"],
  "topics": ["seek-counsel", "agreement", "strangers"],
  "themes": ["deceit", "covenant", "negligence"],
 },
 {
  "slug": "adoni-bezek",
  "name": "Adoni-bezek",
  "era": "Conquest",
  "charge": "Mutilating seventy kings",
  "verdict": "temporal",
  "summary": "Judah defeated the Canaanite king Adoni-bezek and cut off his thumbs and great toes. He said it himself: seventy kings with thumbs and toes cut off had gathered their meat under my table; as I have done, so God hath requited me.",
  "offense": "Systematic cruelty to defeated enemies, which he counted as his glory. The law of Israel limits punishment to measure, eye for eye and no more; he had exceeded all measure on seventy men.",
  "judgment": "The same mutilation, once. He was brought to Jerusalem and died there. A pagan king pronouncing the lex talionis on himself is the point of the record.",
  "refs": R("Judges 1:5-7", "Leviticus 24:19-20", "Exodus 21:23-25", "Matthew 7:2"),
  "laws": ["19C.1", "19C.7", "19D.7", "2P.2"],
  "topics": ["judgement", "sevenfold"],
  "themes": ["retribution", "cruelty"],
 },
 {
  "slug": "israel-in-the-judges",
  "name": "Israel in the days of the Judges",
  "era": "Judges",
  "charge": "Serving Baalim and Ashtaroth; intermarrying with the Canaanites; every man doing right in his own eyes",
  "verdict": "captivity",
  "summary": "After Joshua's generation died a generation arose that knew not the Lord. They forsook him for the gods of the peoples round about, took their daughters as wives, and were sold into the hands of Mesopotamia, Moab, Canaan, Midian, Ammon, and the Philistines in turn.",
  "offense": "The cycle the book itself describes: the children of Israel did evil in the sight of the Lord, served Baalim, forsook the God of their fathers. Judges 3 records the intermarriage that drove it; Psalm 106 says they were mingled among the heathen and learned their works.",
  "judgment": "The anger of the Lord was hot against Israel, and he delivered them into the hands of spoilers. Each time they cried out he raised a judge; each time the judge died they returned and corrupted themselves more than their fathers. The book ends with no king and every man right in his own eyes.",
  "refs": R("Judges 2:10-19", "Judges 3:5-8", "Judges 17:6", "Judges 21:25", "Psalms 106:34-43", "Nehemiah 9:26-28", "Deuteronomy 7:3-4"),
  "laws": ["2D.15", "2H.3", "2I.9", "5G.12", "2G.1"],
  "topics": ["heathen-israel", "other-gods", "intermarrying", "captivity"],
  "themes": ["idolatry", "intermarriage", "captivity", "backsliding"],
 },
 {
  "slug": "gideons-ephod",
  "name": "Gideon's ephod",
  "era": "Judges",
  "charge": "Making an ephod from the spoil; Israel whoring after it",
  "verdict": "temporal",
  "summary": "Gideon refused the crown and said the Lord should rule, then asked for the golden earrings of the spoil and made an ephod of them and put it in Ophrah. All Israel went a whoring after it there, and it became a snare to Gideon and his house.",
  "offense": "The man who had thrown down his father's altar of Baal built a new object of worship out of victory. The text does not say he meant idolatry; it says what it became. The gold of Midian was the same material as the calf.",
  "judgment": "A snare unto Gideon and to his house. As soon as he died, Israel turned to Baal-berith, and his seventy sons were murdered by the son he had by a concubine in Shechem.",
  "refs": R("Judges 8:22-27", "Judges 8:33-35", "Judges 6:25-27", "Judges 9:5", "Exodus 20:23"),
  "laws": ["2D.7", "2D.8", "2D.14", "20A.5"],
  "topics": ["graven-images", "spiritual-fornication", "false-worship"],
  "themes": ["idolatry", "leadership", "snare"],
 },
 {
  "slug": "abimelech",
  "name": "Abimelech son of Gideon",
  "era": "Judges",
  "charge": "Murder of seventy brothers on one stone; usurping a crown",
  "verdict": "death",
  "summary": "Gideon's son by a Shechemite concubine hired vain and light persons with silver from the house of Baal-berith, killed his seventy brothers on one stone, and had himself made king at Shechem. Only Jotham escaped, and his parable from Mount Gerizim pronounced the sentence.",
  "offense": "Fratricide financed by an idol's treasury, in pursuit of a kingship God had not given and Gideon had refused. Jotham: if ye have dealt truly, rejoice in Abimelech; if not, let fire come out from Abimelech and devour the men of Shechem, and fire from Shechem devour Abimelech.",
  "judgment": "God sent an evil spirit between Abimelech and Shechem; he destroyed the city and sowed it with salt, and at Thebez a woman dropped a millstone on his head. He had his armor-bearer finish him so it would not be said a woman slew him. Thus God rendered the wickedness of Abimelech.",
  "refs": R("Judges 9:1-6", "Judges 9:16-20", "Judges 9:22-24", "Judges 9:45", "Judges 9:52-57", "2 Samuel 11:21"),
  "laws": ["10A.5", "10A.7", "8A.14", "8B.6", "2P.2"],
  "topics": ["murder", "pride", "judgement"],
  "themes": ["murder", "usurpation", "kingship"],
 },
 {
  "slug": "jephthah",
  "name": "Jephthah's vow",
  "era": "Judges",
  "charge": "A rash vow, and its performance on his daughter",
  "verdict": "temporal",
  "summary": "Before battle with Ammon, Jephthah vowed that whatever came out of his doors to meet him on his return would be the Lord's and offered as a burnt offering. His only child came out with timbrels. He did with her according to his vow.",
  "offense": "The vow itself was the sin: sworn thoughtlessly with the lips, as Leviticus describes, binding himself to a thing God never asked and, on the plain reading, forbade. Ecclesiastes: suffer not thy mouth to cause thy flesh to sin. The text records that she bewailed her virginity and knew no man; readers have long divided over whether the sacrifice was literal or a life devoted, and the text does not settle it.",
  "judgment": "He lost his only child and his line ended with him. The daughters of Israel kept a yearly lament for her. Jephthah is nonetheless counted among the faithful in Hebrews 11, which is the record's own tension.",
  "refs": R("Judges 11:30-31", "Judges 11:34-40", "Leviticus 5:4-6", "Numbers 30:2", "Ecclesiastes 5:2-6", "Deuteronomy 12:31", "Hebrews 11:32"),
  "laws": ["4D.16", "4D.7", "4D.14", "10H.3", "17A.2"],
  "topics": ["agreement", "self-control", "family-trials"],
  "themes": ["vows", "rashness", "leadership"],
 },
 {
  "slug": "samson",
  "name": "Samson",
  "era": "Judges",
  "charge": "Marrying a Philistine; going in to a harlot; betraying his Nazarite vow to Delilah",
  "verdict": "death",
  "summary": "A Nazarite from the womb who repeatedly went down to the Philistines for women: a wife at Timnath against his parents' counsel, a harlot at Gaza, and Delilah in Sorek, to whom he told all his heart. He woke from her lap shaven, and the Lord had departed from him.",
  "offense": "Get her for me, for she pleaseth me well: the whole pattern in one sentence. Marriage with the uncircumcised, fornication, and the surrender of the sign of his consecration, each time with eyes that saw what they wanted. Hebrews still lists him among those who through faith waxed valiant.",
  "judgment": "The Philistines put out his eyes, bound him with fetters of brass, and set him grinding in the prison house. In the temple of Dagon he prayed once more, and the dead which he slew at his death were more than they which he slew in his life. He died with them.",
  "refs": R("Judges 13:5", "Judges 14:1-3", "Judges 16:1", "Judges 16:4", "Judges 16:16-21", "Judges 16:28-30", "Numbers 6:2-5", "Deuteronomy 7:3", "Hebrews 11:32-34"),
  "laws": ["5G.12", "5G.13", "5E.1", "4D.5", "17H.5"],
  "topics": ["intermarrying", "sexual-lust", "whoremonger", "peer-pressure"],
  "themes": ["intermarriage", "sexual-immorality", "vows", "leadership"],
 },
 {
  "slug": "micah-and-the-danites",
  "name": "Micah's idols and the tribe of Dan",
  "era": "Judges",
  "charge": "A house of gods, a hired Levite, and a tribe that stole both",
  "verdict": "captivity",
  "summary": "Micah of Ephraim stole silver from his mother, returned it, and she had it made into a graven and molten image. He set up a house of gods, consecrated his own son, then hired a wandering Levite as priest. The Danites, migrating north, took the priest and the idols for themselves.",
  "offense": "Every layer breaks a law: theft from a parent, images made from the stolen silver, a shrine that was not the chosen place, a priest who was not of Aaron, and then armed robbery of the whole apparatus by a tribe that founded its northern city on it. The narrator's refrain: every man did that which was right in his own eyes.",
  "judgment": "The Danites set up the graven image and Jonathan son of Gershom and his sons were priests to the tribe of Dan until the day of the captivity of the land. Dan's idolatry ran unbroken from this to Jeroboam's calf at the same city.",
  "refs": R("Judges 17:1-6", "Judges 17:10-13", "Judges 18:14-20", "Judges 18:27-31", "Judges 21:25", "Deuteronomy 12:8", "1 Kings 12:29-30"),
  "laws": ["2D.7", "2D.8", "18B.1", "6C.5", "20B.14", "20B.15"],
  "topics": ["graven-images", "stealing", "false-worship", "captivity"],
  "themes": ["idolatry", "theft", "priesthood", "captivity"],
 },
 {
  "slug": "gibeah",
  "name": "The men of Gibeah, and Benjamin",
  "era": "Judges",
  "charge": "Sodomy, gang rape and murder of a stranger's concubine; a tribe that shielded the guilty",
  "verdict": "death",
  "summary": "The men of Gibeah surrounded the house where a Levite lodged, demanding him; they were given his concubine and abused her all night until she died on the threshold. He cut her into twelve pieces and sent them through Israel. Benjamin refused to surrender the guilty, and Israel went to war.",
  "offense": "The crime of Sodom repeated in Israel, then compounded by the tribe: they would not hearken to the voice of their brethren to put away evil from Israel. Hosea names it twice as the depth of the nation's corruption: they have deeply corrupted themselves, as in the days of Gibeah.",
  "judgment": "After two defeats Israel destroyed Benjamin, the city, the cattle, and all that came to hand; six hundred men survived at the rock Rimmon, and the tribe was rebuilt from them. Israel wept at Bethel that a tribe was lacking.",
  "refs": R("Judges 19:22-30", "Judges 20:4-7", "Judges 20:12-13", "Judges 20:35", "Judges 20:46-48", "Judges 21:2-3", "Hosea 9:9", "Hosea 10:9", "Genesis 19:4-5"),
  "laws": ["10J.3", "10J.9", "10A.1", "15A.7", "4F.4", "19A"],
  "topics": ["sodomy", "murder", "strangers"],
  "themes": ["sexual-immorality", "violence", "corporate-judgment"],
 },
 {
  "slug": "beth-shemesh",
  "name": "The men of Beth-shemesh",
  "era": "Judges",
  "charge": "Looking into the ark of the Lord",
  "verdict": "death",
  "summary": "When the Philistines returned the ark on a cart, the men of Beth-shemesh rejoiced, offered the kine, and looked into the ark. The Lord smote them with a great slaughter, and they asked, who is able to stand before this holy Lord God?",
  "offense": "Even the Kohathites who carried the ark were forbidden to go in and see when the holy things were covered, lest they die. Farmers at harvest opened it for curiosity. The Levites of a priestly city should have known.",
  "judgment": "The text gives the number as fifty thousand and threescore and ten men, a figure long debated; the sentence is not. They sent the ark on to Kirjath-jearim and it stayed there twenty years.",
  "refs": R("1 Samuel 6:13-15", "1 Samuel 6:19-21", "1 Samuel 7:1-2", "Numbers 4:15", "Numbers 4:20"),
  "laws": ["20A.19", "2J.19", "2C"],
  "topics": ["ark-of-covenant", "fear-god", "holiness"],
  "themes": ["irreverence", "holy-things"],
 },
]
