from cases_lib import R

CASES = [
 {
  "slug": "rehoboam",
  "name": "Rehoboam",
  "era": "Divided Kingdom",
  "charge": "Forsaking the counsel of the old men; forsaking the law of the Lord",
  "verdict": "temporal",
  "summary": "Solomon's son rejected the elders' advice to serve the people and took his young companions' line: my little finger shall be thicker than my father's loins. Ten tribes left him that day. Later, when the kingdom was established, he forsook the law of the Lord and all Israel with him.",
  "offense": "Pride in the first instance, apostasy in the second. Chronicles: he did evil, because he prepared not his heart to seek the Lord. Sirach calls him the foolishness of the people, one that had no understanding.",
  "judgment": "Shishak of Egypt came up with twelve hundred chariots and took the treasures of the house of the Lord and the shields of gold. When the princes humbled themselves the Lord granted some deliverance, that they might know the difference between serving him and serving the kingdoms of the countries.",
  "refs": R("1 Kings 12:6-16", "2 Chronicles 12:1-2", "2 Chronicles 12:5-9", "2 Chronicles 12:14", "1 Kings 14:21-26", "Sirach 47:23"),
  "laws": ["8A.1", "8A.17", "17G.13", "2I.4", "17D.21"],
  "topics": ["seek-counsel", "pride", "split-kingdom"],
  "themes": ["pride", "kingship", "backsliding"],
 },
 {
  "slug": "jeroboam",
  "name": "Jeroboam son of Nebat",
  "era": "Divided Kingdom",
  "charge": "Two golden calves; priests of the lowest of the people; a feast devised of his own heart",
  "verdict": "curse",
  "summary": "Given ten tribes by the Lord, Jeroboam feared the people would return to Jerusalem to worship, so he set calves in Bethel and Dan, saying, behold thy gods, O Israel, made priests of any who were not Levites, and moved the feast to a month of his own choosing. Every king of Israel after him is measured by his sin.",
  "offense": "State idolatry engineered for political security, borrowing the words of Aaron's calf. He was warned at the altar itself by a man of God from Judah, saw his hand wither, and after all this returned not from his evil way.",
  "judgment": "The Lord promised to cut off from Jeroboam every male, and to take away the remnant of his house as a man takes away dung. Baasha killed his son Nadab and all his house. Israel's captivity two centuries later is charged to the sins of Jeroboam, which he made Israel to sin.",
  "refs": R("1 Kings 12:26-33", "1 Kings 13:1-6", "1 Kings 13:33-34", "1 Kings 14:7-11", "1 Kings 14:16", "1 Kings 15:29-30", "2 Kings 17:21-23", "Sirach 47:24"),
  "laws": ["2D.7", "2D.3", "2D.15", "20B.14", "9A", "10F.3", "2I.2"],
  "topics": ["idolatry", "graven-images", "false-worship", "kings-and-priests"],
  "themes": ["idolatry", "kingship", "priesthood", "enticement"],
 },
 {
  "slug": "the-man-of-god-from-judah",
  "name": "The man of God from Judah",
  "era": "Divided Kingdom",
  "charge": "Turning back to eat and drink at Bethel against the word of the Lord",
  "verdict": "death",
  "summary": "Sent to cry against Jeroboam's altar, the prophet was charged to eat no bread, drink no water, and not return the way he came. An old prophet of Bethel lied to him, claiming an angel had said otherwise; he went back and ate. A lion met him on the road.",
  "offense": "He had refused the king's table and reward; he accepted a colleague's word over God's own. Test the spirits: another prophet's claim did not cancel a command he had received himself. The old prophet's lie is recorded without excuse.",
  "judgment": "The word of the Lord came through the very man who had deceived him: thy carcase shall not come unto the sepulchre of thy fathers. The lion killed him and stood by the body without eating it or the ass; the old prophet buried him in his own grave.",
  "refs": R("1 Kings 13:7-10", "1 Kings 13:14-19", "1 Kings 13:20-26", "1 Kings 13:29-32", "Galatians 1:8", "1 John 4:1"),
  "laws": ["2H.1", "20F.10", "3E.1", "3J.14"],
  "topics": ["obedience", "false-prophets", "lying"],
  "themes": ["disobedience", "false-prophets", "deceit"],
 },
 {
  "slug": "ahab",
  "name": "Ahab",
  "era": "Divided Kingdom",
  "charge": "Marrying Jezebel; serving Baal; sparing Ben-hadad whom the Lord appointed to destruction",
  "verdict": "death",
  "summary": "Ahab did more to provoke the Lord than all the kings before him: he married a Zidonian, built Baal a house in Samaria, and made a grove. He spared the king of Syria for a trade deal after the Lord gave him the victory, and sold himself to work wickedness in Naboth's vineyard.",
  "offense": "Idolatry, intermarriage, and the release of an enemy God had devoted, on top of the judicial murder his wife arranged for him. Elijah's word: thou hast sold thyself to work evil in the sight of the Lord.",
  "judgment": "Because he humbled himself at Elijah's sentence, the evil on his house was deferred to his son's days. His own end was not: an arrow at a venture found the joints of his harness at Ramoth-gilead, and dogs licked his blood at the pool of Samaria as the Lord had said.",
  "refs": R("1 Kings 16:30-33", "1 Kings 18:17-18", "1 Kings 20:31-34", "1 Kings 20:42", "1 Kings 21:25-29", "1 Kings 22:34-38", "Deuteronomy 7:2-4"),
  "laws": ["2D.3", "2D.6", "5G.12", "22D.7", "22D.8", "8A.24"],
  "topics": ["idolatry", "intermarrying", "other-gods", "our-enemies"],
  "themes": ["idolatry", "intermarriage", "kingship", "murder"],
 },
 {
  "slug": "jezebel",
  "name": "Jezebel",
  "era": "Divided Kingdom",
  "charge": "Killing the prophets of the Lord; promoting Baal; witchcrafts",
  "verdict": "death",
  "summary": "Ahab's Zidonian queen cut off the prophets of the Lord, fed four hundred and fifty prophets of Baal at her table, swore to kill Elijah, and stirred up her husband to every evil. Jehu named her whoredoms and witchcrafts as the reason there could be no peace.",
  "offense": "A foreign woman ruling a king of Israel into apostasy, with the machinery of state turned against the Lord's prophets. Revelation makes her name the type of the woman who calls herself a prophetess and teaches the servants of God to commit fornication and eat things sacrificed to idols.",
  "judgment": "Elijah pronounced it: the dogs shall eat Jezebel by the wall of Jezreel. Jehu had her eunuchs throw her from the window; horses trod her underfoot, and when they went to bury her they found no more than the skull, the feet, and the palms of her hands.",
  "refs": R("1 Kings 16:31", "1 Kings 18:4", "1 Kings 18:13", "1 Kings 19:1-2", "1 Kings 21:25", "2 Kings 9:7", "2 Kings 9:22", "2 Kings 9:30-37", "Revelation 2:20"),
  "laws": ["10A.2", "10F.4", "2G.3", "8A.12", "20F.4", "2I.2"],
  "topics": ["persecution", "false-worship", "the-woman", "false-prophets"],
  "themes": ["persecution", "idolatry", "murder", "enticement"],
 },
 {
  "slug": "the-prophets-of-baal",
  "name": "The prophets of Baal at Carmel",
  "era": "Divided Kingdom",
  "charge": "Prophesying in the name of other gods",
  "verdict": "death",
  "summary": "Four hundred and fifty prophets of Baal cried from morning to noon and cut themselves with knives until the blood gushed out, and there was neither voice nor any to answer. Elijah's bullock, drenched three times, was consumed by fire from heaven with the water and the stones.",
  "offense": "Deuteronomy 13 and 18 are the statutes: the prophet who speaks in the name of other gods shall die, and the one who says, let us go after other gods, shall be put to death. They had done it in front of all Israel for years at the queen's table.",
  "judgment": "When the people fell on their faces and said, the Lord, he is the God, Elijah had the prophets taken down to the brook Kishon and slain there. Then the rain came.",
  "refs": R("1 Kings 18:19", "1 Kings 18:22", "1 Kings 18:26-29", "1 Kings 18:38-40", "Deuteronomy 13:1-5", "Deuteronomy 18:20", "Leviticus 19:28"),
  "laws": ["10F.3", "10F.4", "10F.1", "20F.1"],
  "topics": ["false-prophets", "false-worship", "other-gods"],
  "themes": ["false-prophets", "idolatry"],
 },
 {
  "slug": "ahaziah-of-israel",
  "name": "Ahaziah of Israel",
  "era": "Divided Kingdom",
  "charge": "Inquiring of Baal-zebub the god of Ekron",
  "verdict": "death",
  "summary": "Ahab's son fell through a lattice in Samaria and sent messengers to ask Baal-zebub whether he would recover. Elijah met them on the road: is it not because there is not a God in Israel that ye go to inquire of Baal-zebub? Two captains of fifty sent to arrest the prophet were consumed by fire.",
  "offense": "A king of Israel treating a Philistine idol as his oracle, and then sending soldiers against the man who told him so. The law forbids the ruler to consult mediums and spiritists, and forbids the people to listen to them.",
  "judgment": "Thou shalt not come down from that bed on which thou art gone up, but shalt surely die. So he died according to the word of the Lord which Elijah had spoken, and having no son, his brother reigned.",
  "refs": R("2 Kings 1:2-4", "2 Kings 1:6", "2 Kings 1:9-12", "2 Kings 1:15-17", "Leviticus 19:31", "Isaiah 8:19"),
  "laws": ["2G.4", "2G.5", "8A.20", "10D.1"],
  "topics": ["divination", "other-gods", "sickness"],
  "themes": ["occult", "kingship", "idolatry"],
 },
 {
  "slug": "the-mockers-of-bethel",
  "name": "The young mockers of Bethel",
  "era": "Divided Kingdom",
  "charge": "Mocking the prophet of the Lord",
  "verdict": "death",
  "summary": "As Elisha went up to Bethel, the seat of Jeroboam's calf, a company came out of the city mocking him: go up, thou bald head. He cursed them in the name of the Lord, and two she-bears came out of the wood and tore forty-two of them.",
  "offense": "Contempt for the office, in the city that had made contempt for the Lord its religion. Go up mocks Elijah's ascent, which the sons of the prophets had just witnessed. The Hebrew word covers youths, not infants; forty-two of them were a crowd, not a prank.",
  "judgment": "Leviticus warned that if Israel walked contrary to him, the Lord would send wild beasts among them which should rob them of their children. Forty-two were torn. Elisha went on to Carmel.",
  "refs": R("2 Kings 2:23-25", "Leviticus 26:21-22", "Exodus 22:28", "Leviticus 19:32", "2 Chronicles 36:16"),
  "laws": ["12E.10", "20F", "2P.15", "2C"],
  "topics": ["honour", "scoffer", "persecution"],
  "themes": ["contempt-for-authority", "irreverence"],
 },
 {
  "slug": "jehu",
  "name": "Jehu",
  "era": "Divided Kingdom",
  "charge": "Executing the house of Ahab, then keeping the calves of Jeroboam",
  "verdict": "temporal",
  "summary": "Anointed to cut off the house of Ahab, Jehu killed Joram, Ahaziah, Jezebel, seventy sons of Ahab, and every worshipper of Baal in Samaria, and destroyed Baal out of Israel. But from the golden calves at Bethel and Dan Jehu departed not.",
  "offense": "Zeal for the Lord that stopped exactly where it became inconvenient to the throne. He took no heed to walk in the law of the Lord God of Israel with all his heart. Hosea adds that the blood of Jezreel would be visited on his house, judging the manner of his executions even where the sentence was God's.",
  "judgment": "Because he had done well in executing what was right, his sons sat on Israel's throne to the fourth generation. Because of the calves, the Lord began in those days to cut Israel short: Hazael smote them in all their coasts. His dynasty ended with Zechariah, murdered after six months.",
  "refs": R("2 Kings 9:6-10", "2 Kings 10:11", "2 Kings 10:28-33", "Hosea 1:4", "2 Kings 15:8-12"),
  "laws": ["2D.3", "2H.4", "2F", "8A.10", "17K.1"],
  "topics": ["idolatry", "keep-the-commandments", "compromise"],
  "themes": ["idolatry", "kingship", "partial-obedience"],
 },
 {
  "slug": "athaliah",
  "name": "Athaliah",
  "era": "Divided Kingdom",
  "charge": "Destroying the seed royal of Judah; usurping the throne",
  "verdict": "death",
  "summary": "Ahab's daughter, married into Judah's line, saw her son Ahaziah dead at Jehu's hand and murdered all the seed royal to reign herself. One infant, Joash, was hidden in the house of the Lord for six years. In the seventh, Jehoiada the priest brought him out.",
  "offense": "Mass murder of her own grandchildren for a crown, and six years of Baal worship in Jerusalem: her sons had broken up the house of God and given its dedicated things to Baalim.",
  "judgment": "She heard the trumpets, rent her clothes, and cried, treason. Jehoiada would not have her killed in the house of the Lord; they took her out by the horse gate and slew her there. Then the people tore down Baal's house and killed Mattan his priest.",
  "refs": R("2 Kings 11:1-3", "2 Kings 11:13-16", "2 Chronicles 22:10-12", "2 Chronicles 23:12-15", "2 Chronicles 24:7", "2 Kings 8:26-27"),
  "laws": ["10A.2", "8A.12", "8A.14", "10G.3", "2D.3"],
  "topics": ["murder", "the-woman", "idolatry"],
  "themes": ["murder", "usurpation", "kingship", "idolatry"],
 },
 {
  "slug": "joash-of-judah",
  "name": "Joash of Judah",
  "era": "Divided Kingdom",
  "charge": "Forsaking the Lord after Jehoiada's death; stoning Zechariah in the temple court",
  "verdict": "death",
  "summary": "The boy king saved by the priest Jehoiada did right all the days of Jehoiada. When the priest died, the princes of Judah came and Joash hearkened to them, left the house of the Lord, and served groves and idols. Jehoiada's son Zechariah rebuked him by the Spirit; the king had him stoned in the court of the temple.",
  "offense": "Apostasy the moment his mentor's restraint was gone, then the murder of that mentor's son for prophesying against it. Thus Joash the king remembered not the kindness which Jehoiada his father had done to him. Christ counts Zechariah's blood among the prophets' blood required of that generation.",
  "judgment": "Zechariah's dying word, the Lord look upon it and require it, was answered within the year: a small Syrian company defeated a very great host, and his own servants conspired against him for the blood of the sons of Jehoiada and slew him on his bed. He was not buried in the sepulchres of the kings.",
  "refs": R("2 Chronicles 24:2", "2 Chronicles 24:17-22", "2 Chronicles 24:23-25", "2 Kings 12:2", "Matthew 23:35", "Luke 11:51"),
  "laws": ["10A.2", "2I.7", "20F", "3A", "2D.3"],
  "topics": ["murder", "persecution", "peer-pressure", "idolatry"],
  "themes": ["murder", "persecution", "backsliding", "kingship"],
 },
 {
  "slug": "amaziah",
  "name": "Amaziah",
  "era": "Divided Kingdom",
  "charge": "Bringing home the gods of Seir and bowing to them",
  "verdict": "death",
  "summary": "Having beaten Edom with the Lord's help, Amaziah brought back the gods of the children of Seir, set them up as his gods, and burned incense to them. A prophet asked why he sought gods that could not deliver their own people; the king told him to stop before he was smitten.",
  "offense": "Worship of the defeated enemy's idols, which the law says are to be burned, not carried home. Then, lifted up in pride, he provoked a war with Israel he was warned against and lost.",
  "judgment": "The prophet's parting word: I know that God hath determined to destroy thee, because thou hast done this. Israel broke down Jerusalem's wall and plundered the temple; after that Amaziah's own people conspired against him at Lachish and killed him there.",
  "refs": R("2 Chronicles 25:14-16", "2 Chronicles 25:17-20", "2 Chronicles 25:23-24", "2 Chronicles 25:27", "2 Kings 14:3", "Deuteronomy 7:25-26"),
  "laws": ["2D.3", "2D.9", "22A.11", "17G.13", "3L.16"],
  "topics": ["idolatry", "other-gods", "pride"],
  "themes": ["idolatry", "pride", "kingship"],
 },
 {
  "slug": "uzziah",
  "name": "Uzziah",
  "era": "Divided Kingdom",
  "charge": "Entering the temple to burn incense, which belonged to the priests",
  "verdict": "temporal",
  "summary": "A strong and prosperous king who sought God in the days of Zechariah. When he was strong his heart was lifted up, and he went into the temple with a censer. Eighty priests withstood him; while he raged at them, leprosy rose in his forehead.",
  "offense": "Usurping an office God had assigned to the sons of Aaron. The stranger that cometh nigh shall be put to death was the statute; Korah had died for the same claim. Azariah said it plainly: it appertaineth not unto thee, Uzziah.",
  "judgment": "A leper to the day of his death, cut off from the house of the Lord, dwelling in a several house while his son judged the people. He was buried in a field near the kings' sepulchres, not among them, for they said, he is a leper.",
  "refs": R("2 Chronicles 26:4-5", "2 Chronicles 26:16-21", "2 Chronicles 26:23", "Numbers 16:40", "Numbers 18:7", "2 Kings 15:5"),
  "laws": ["20B.15", "20A.3", "17G.13", "17G.19", "3L.16"],
  "topics": ["pride", "kings-and-priests", "in-order"],
  "themes": ["pride", "priesthood", "kingship"],
 },
 {
  "slug": "ahaz",
  "name": "Ahaz",
  "era": "Divided Kingdom",
  "charge": "Burning his children in the fire; copying the altar of Damascus; sacrificing to the gods that smote him",
  "verdict": "temporal",
  "summary": "Ahaz walked in the ways of the kings of Israel, made molten images for Baalim, burnt his children in the fire after the abominations of the heathen, and hired Assyria against Syria with the temple's silver. Defeated, he sacrificed to the gods of Damascus because they had helped his enemies.",
  "offense": "Child sacrifice, the sin the Canaanites were destroyed for; a pagan altar pattern installed in the Lord's house; shutting up the temple doors; and the logic of a lost man, worship whoever is winning. Wisdom describes the Canaanites he imitated as merciless murderers of children.",
  "judgment": "The Lord delivered him into the hand of Syria and of Israel, who slew a hundred and twenty thousand in one day, and Assyria distressed him instead of strengthening him. In the time of his distress did he trespass yet more against the Lord: this is that king Ahaz. He was buried outside the kings' sepulchres.",
  "refs": R("2 Chronicles 28:1-5", "2 Chronicles 28:16", "2 Chronicles 28:19-25", "2 Chronicles 28:27", "2 Kings 16:2-4", "2 Kings 16:10-16", "Wisdom of Solomon 12:3-6"),
  "laws": ["10H.3", "10H.1", "2D.3", "2G.1", "11B.3", "2J.8"],
  "topics": ["other-gods", "idolatry", "assimilation"],
  "themes": ["idolatry", "child-sacrifice", "kingship", "foreign-alliance"],
 },
 {
  "slug": "hezekiahs-pride",
  "name": "Hezekiah and the ambassadors of Babylon",
  "era": "Divided Kingdom",
  "charge": "Showing all his treasures to Babylon in the pride of his heart",
  "verdict": "reprieve",
  "summary": "Healed of a mortal sickness and given fifteen years, Hezekiah received envoys from Babylon and showed them the house of his precious things, the silver, the gold, the armor, everything. Isaiah asked what they had seen. Nothing hidden, said the king.",
  "offense": "Chronicles: Hezekiah rendered not again according to the benefit done unto him, for his heart was lifted up. God left him, to try him, that he might know all that was in his heart. A king glorying in his riches before the empire that would carry them away.",
  "judgment": "All that is in thine house shall be carried into Babylon, and of thy sons shall they take away, and they shall be eunuchs in the palace of the king of Babylon. Hezekiah humbled himself, and the wrath came not in his days: is it not good, if peace and truth be in my days?",
  "refs": R("2 Kings 20:12-19", "2 Chronicles 32:24-26", "2 Chronicles 32:31", "Isaiah 39:1-8", "Daniel 1:1-4"),
  "laws": ["17G.13", "17D.6", "2O", "11B.3"],
  "topics": ["pride", "humility", "captivity"],
  "themes": ["pride", "kingship", "captivity"],
 },
 {
  "slug": "manasseh",
  "name": "Manasseh",
  "era": "Divided Kingdom",
  "charge": "Rebuilding the high places; altars to the host of heaven in the temple; passing his sons through the fire; witchcraft; filling Jerusalem with innocent blood",
  "verdict": "captivity",
  "summary": "Hezekiah's son undid everything his father had done and more: altars for Baal, a grove, worship of all the host of heaven in both courts of the Lord's house, his children through the fire, observing times, enchantments, familiar spirits, wizards. He shed innocent blood until Jerusalem was filled from one end to another.",
  "offense": "The record says he seduced Judah to do more evil than the nations the Lord destroyed before them. Every capital offense against God in the handbook's tenth part appears in his reign. Judah's captivity, decades later, is charged to him by name.",
  "judgment": "The Lord brought the captains of the host of Assyria, who took Manasseh among the thorns, bound him with fetters, and carried him to Babylon. There he humbled himself greatly and prayed; the Prayer of Manasseh preserves the tradition of it. God brought him back to his kingdom and he took away the strange gods. But the sentence on Judah for his sins stood: the Lord would not pardon.",
  "refs": R("2 Kings 21:1-9", "2 Kings 21:10-16", "2 Chronicles 33:1-13", "2 Kings 23:26", "2 Kings 24:3-4", "Jeremiah 15:4", "Prayer of Manasseh 1:9-13"),
  "laws": ["2D.3", "2D.6", "10H.3", "10D.1", "2G.4", "10A.2", "2L.5"],
  "topics": ["idolatry", "divination", "captivity", "repentance"],
  "themes": ["idolatry", "child-sacrifice", "occult", "murder", "repentance", "captivity"],
 },
 {
  "slug": "amon",
  "name": "Amon",
  "era": "Divided Kingdom",
  "charge": "Serving his father's idols and refusing his father's repentance",
  "verdict": "death",
  "summary": "Manasseh's son reigned two years, sacrificed to all the carved images his father had made, and humbled not himself before the Lord as Manasseh had humbled himself, but trespassed more and more.",
  "offense": "He had both examples in one man, the apostasy and the repentance, and chose the first. He forsook the Lord God of his fathers and walked not in the way of the Lord.",
  "judgment": "His own servants conspired against him and slew him in his house. The people of the land killed the conspirators and made Josiah, eight years old, king in his stead.",
  "refs": R("2 Kings 21:19-24", "2 Chronicles 33:21-25"),
  "laws": ["2D.3", "2I.4", "17I", "2L.14"],
  "topics": ["idolatry", "stiff-necked"],
  "themes": ["idolatry", "kingship"],
 },
 {
  "slug": "josiah-at-megiddo",
  "name": "Josiah at Megiddo",
  "era": "Divided Kingdom",
  "charge": "Going to battle against Necho without inquiring of the Lord",
  "verdict": "death",
  "summary": "The reformer king, promised he would be gathered to his grave in peace, went out against Pharaoh Necho, who was marching to Carchemish and had no quarrel with Judah. Necho sent word that God had commanded him to make haste and that Josiah should not meddle with God, who was with him. Josiah disguised himself and fought anyway.",
  "offense": "Chronicles is unusually direct: he hearkened not unto the words of Necho from the mouth of God. A war without cause, without inquiry, against a warning the narrator credits as divine. The best king since David died of a battle that was not his.",
  "judgment": "Archers hit him in the valley of Megiddo; his servants carried him to Jerusalem and he died. Jeremiah lamented for him, and the lament became an ordinance in Israel. The promise of a peaceful grave was kept in the sense that he did not see the evil that followed.",
  "refs": R("2 Chronicles 35:20-25", "2 Kings 23:29-30", "2 Kings 22:18-20", "2 Chronicles 34:27-28", "Zechariah 12:11"),
  "laws": ["22A.7", "22A.19", "22E.6", "2H.1"],
  "topics": ["seek-counsel", "army", "make-haste"],
  "themes": ["war", "kingship", "rashness"],
 },
 {
  "slug": "jehoiakim",
  "name": "Jehoiakim",
  "era": "Divided Kingdom",
  "charge": "Building with unrighteousness; shedding innocent blood; burning the scroll of the Lord's words",
  "verdict": "curse",
  "summary": "Necho's puppet king built a great house with unpaid labor, killed the prophet Urijah for prophesying like Jeremiah, and when Jeremiah's scroll was read to him, cut it with a penknife leaf by leaf and burned it in the hearth. Neither he nor his servants were afraid.",
  "offense": "Jeremiah's indictment: thine eyes and thine heart are not but for thy covetousness, and for to shed innocent blood, and for oppression, and for violence. Withholding wages, murder of a prophet, and the deliberate destruction of the written word.",
  "judgment": "He shall be buried with the burial of an ass, drawn and cast forth beyond the gates of Jerusalem. He shall have none to sit upon the throne of David, and his dead body shall be cast out in the day to the heat and in the night to the frost. His son reigned three months and went to Babylon; his brother was the last king.",
  "refs": R("Jeremiah 22:13-19", "Jeremiah 26:20-23", "Jeremiah 36:21-26", "Jeremiah 36:29-31", "2 Kings 24:1-4", "2 Kings 23:36-37", "Deuteronomy 4:2"),
  "laws": ["10A.2", "3J.7", "13A", "8A.7", "17C.18", "2F"],
  "topics": ["murder", "the-word", "covet", "persecution"],
  "themes": ["murder", "covetousness", "persecution", "kingship", "the-word"],
 },
 {
  "slug": "zedekiah",
  "name": "Zedekiah",
  "era": "Divided Kingdom",
  "charge": "Breaking his oath to Nebuchadnezzar; stiffening his neck against the Lord's word by Jeremiah",
  "verdict": "captivity",
  "summary": "Sworn by God to serve Babylon, Zedekiah rebelled against Nebuchadnezzar and would not humble himself before Jeremiah speaking from the mouth of the Lord. Warned to the last that surrender would save the city and his life, he feared the Jews who had defected more than he feared the word.",
  "offense": "Ezekiel names the oath-breaking as the Lord's own quarrel: seeing he despised the oath by breaking the covenant, when, lo, he had given his hand. Chronicles adds that he stiffened his neck and hardened his heart from turning unto the Lord God of Israel.",
  "judgment": "Taken fleeing by night near Jericho, he watched his sons slain at Riblah, then had his eyes put out, and was carried in chains to Babylon, where he died in prison. The city and the temple burned behind him. Ezekiel's thou profane wicked prince of Israel, whose day is come.",
  "refs": R("2 Chronicles 36:11-13", "2 Kings 25:1-7", "Jeremiah 37:1-2", "Jeremiah 38:17-23", "Jeremiah 52:8-11", "Ezekiel 17:12-19", "Ezekiel 21:25-27"),
  "laws": ["4D.2", "4D.15", "17F", "2H.1", "8A.4", "3L.16"],
  "topics": ["stiff-necked", "captivity", "agreement"],
  "themes": ["covenant", "stubbornness", "kingship", "captivity"],
 },
 {
  "slug": "israels-captivity",
  "name": "The captivity of Israel (the northern kingdom)",
  "era": "Divided Kingdom",
  "charge": "Two centuries of the sins of Jeroboam; secret sins; idols, high places, and children through the fire",
  "verdict": "captivity",
  "summary": "Second Kings 17 is the indictment of a nation: they feared other gods, walked in the statutes of the heathen and of the kings of Israel, built high places in every city, served idols the Lord had said they should not, made their sons and daughters pass through the fire, used divination and enchantments, and sold themselves to do evil.",
  "offense": "The Lord testified against Israel and against Judah by all the prophets and all the seers, and they hardened their necks like the necks of their fathers. Hosea's summary: swearing, lying, killing, stealing, adultery; my people are destroyed for lack of knowledge.",
  "judgment": "The Lord was very angry with Israel and removed them out of his sight: Assyria carried them away and placed them in Halah and Habor and the cities of the Medes. Deuteronomy had said it: the Lord shall scatter thee among all people. There was none left but the tribe of Judah only.",
  "refs": R("2 Kings 17:7-18", "2 Kings 17:21-23", "Hosea 4:1-2", "Hosea 4:6", "Amos 5:26-27", "Deuteronomy 28:36", "Deuteronomy 28:64", "Leviticus 26:33", "Sirach 48:15-16"),
  "laws": ["2D.15", "2H.3", "2I.9", "10H.3", "2G.4", "2G.1"],
  "topics": ["captivity", "scattered", "dispersed", "idolatry", "heathen-israel"],
  "themes": ["captivity", "idolatry", "corporate-judgment"],
 },
 {
  "slug": "judahs-captivity",
  "name": "The captivity of Judah",
  "era": "Divided Kingdom",
  "charge": "Polluting the house of the Lord; mocking the messengers of God; refusing the Sabbath and the land's sabbaths",
  "verdict": "captivity",
  "summary": "All the chief of the priests and the people transgressed very much after all the abominations of the heathen and polluted the house of the Lord. The Lord sent messengers because he had compassion; they mocked them, despised his words, and misused his prophets until there was no remedy.",
  "offense": "Ezekiel's catalogue of Jerusalem: princes shedding blood, fathers and mothers set light by, strangers oppressed, sabbaths profaned, incest, bribes for blood, usury, priests who put no difference between holy and profane, prophets daubing with untempered mortar. Jeremiah adds the Sabbath gates: bear no burden on the sabbath day, and they would not hear.",
  "judgment": "Nebuchadnezzar slew their young men in the sanctuary, burned the house of God, and carried the remnant to Babylon, to fulfil threescore and ten years until the land had enjoyed her sabbaths. Daniel and Baruch both confess it in the same words: the curse is poured upon us, as it is written in the law of Moses.",
  "refs": R("2 Chronicles 36:14-21", "Jeremiah 25:4-11", "Jeremiah 17:21-27", "Ezekiel 22:6-12", "Ezekiel 22:26-31", "Leviticus 26:33-35", "Daniel 9:11-14", "Lamentations 1:8", "Baruch 1:15-20", "Baruch 2:1-2", "Sirach 49:4-5"),
  "laws": ["9D.2", "9C.8", "2H.3", "20F.4", "20A.7", "4F.11", "16C.1", "2P.9"],
  "topics": ["captivity", "sabbath", "prophetic-warnings", "confusion-of-faces"],
  "themes": ["captivity", "sabbath", "corporate-judgment", "priesthood"],
 },
 {
  "slug": "hananiah",
  "name": "Hananiah the son of Azur",
  "era": "Divided Kingdom",
  "charge": "Prophesying a lie in the name of the Lord",
  "verdict": "death",
  "summary": "In the temple, before the priests and all the people, Hananiah declared that the Lord would break Babylon's yoke within two years and bring back the vessels and the captives. He broke the wooden yoke from Jeremiah's neck to prove it.",
  "offense": "Deuteronomy's test: the prophet who presumes to speak a word in my name which I have not commanded him, that prophet shall die. He made the people to trust in a lie and preached rebellion against the Lord, who had told Judah to serve Babylon.",
  "judgment": "Jeremiah: the Lord hath not sent thee. This year thou shalt die, because thou hast taught rebellion against the Lord. So Hananiah the prophet died the same year in the seventh month.",
  "refs": R("Jeremiah 28:1-4", "Jeremiah 28:10-17", "Deuteronomy 18:20-22", "Jeremiah 23:16", "Jeremiah 23:21"),
  "laws": ["20F.4", "4E.1", "3E.11", "2K.1", "20F.1"],
  "topics": ["false-prophets", "lying", "the-name"],
  "themes": ["false-prophets", "deceit"],
 },
 {
  "slug": "pashur",
  "name": "Pashur the son of Immer",
  "era": "Divided Kingdom",
  "charge": "Smiting the prophet and putting him in the stocks; prophesying lies",
  "verdict": "captivity",
  "summary": "Pashur, chief governor in the house of the Lord, heard Jeremiah prophesy the city's fall, struck him, and put him in the stocks at the high gate of Benjamin overnight. In the morning Jeremiah gave him a new name.",
  "offense": "A priest using his office to punish the word of God, while himself prophesying comfort that was a lie. The law reserves stripes for the wicked after judgment; he used them on the Lord's messenger before any.",
  "judgment": "The Lord hath not called thy name Pashur, but Magor-missabib, terror on every side. Thou shalt go into captivity to Babylon, and there thou shalt die and be buried, thou and all thy friends, to whom thou hast prophesied lies.",
  "refs": R("Jeremiah 20:1-6", "Jeremiah 19:14-15", "Jeremiah 26:8-11", "Deuteronomy 25:1-3"),
  "laws": ["8A.23", "20F.4", "19D.2", "20A.2"],
  "topics": ["persecution", "false-prophets", "captivity"],
  "themes": ["persecution", "priesthood", "false-prophets", "captivity"],
 },
 {
  "slug": "pelatiah",
  "name": "Pelatiah and the princes at the east gate",
  "era": "Divided Kingdom",
  "charge": "Devising mischief and giving wicked counsel in the city",
  "verdict": "death",
  "summary": "In vision Ezekiel saw twenty-five men at the east gate of the temple, princes of the people, Jaazaniah and Pelatiah among them, who said, it is not near; let us build houses: this city is the caldron, and we be the flesh. He was told to prophesy against them.",
  "offense": "Rulers who reassured the city against the prophets, treating Jerusalem as a safe pot for its own meat, while multiplying slain in its streets. The Lord: ye have not walked in my statutes, neither executed my judgments, but have done after the manners of the heathen.",
  "judgment": "As Ezekiel prophesied, Pelatiah the son of Benaiah died. The prophet fell on his face and cried out, wilt thou make a full end of the remnant of Israel?",
  "refs": R("Ezekiel 11:1-4", "Ezekiel 11:7-13", "Ezekiel 22:27", "Micah 3:9-11"),
  "laws": ["8A.9", "8A.13", "8A.19", "10A.2", "2G.1"],
  "topics": ["judgement", "prophetic-warnings", "the-wicked"],
  "themes": ["leadership", "false-security", "bloodshed"],
 },
 {
  "slug": "jerusalems-abominations",
  "name": "The elders with idols in the temple (Ezekiel 8)",
  "era": "Divided Kingdom",
  "charge": "The image of jealousy; creeping things on the walls; women weeping for Tammuz; twenty-five men worshipping the sun with their backs to the temple",
  "verdict": "death",
  "summary": "Carried in vision to Jerusalem, Ezekiel was shown four scenes of greater and greater abomination inside the house of the Lord: an idol at the gate, seventy elders with censers in a chamber of painted beasts, women mourning a pagan god, and men between the porch and the altar bowing east to the sun. The elders said, the Lord seeth us not.",
  "offense": "Idolatry practiced by the leadership in the sanctuary itself, in secret, on the assumption that God had forsaken the earth. The land was also full of blood and the city of perverseness. Ezekiel 14 adds: these men have set up their idols in their heart.",
  "judgment": "The glory departed by stages. Six men with slaughter weapons were told to begin at the sanctuary and slay utterly old and young, sparing only those marked who sighed and cried for the abominations. Mine eye shall not spare, neither will I have pity.",
  "refs": R("Ezekiel 8:5-6", "Ezekiel 8:10-12", "Ezekiel 8:14-18", "Ezekiel 9:4-10", "Ezekiel 14:1-8", "Ezekiel 10:18-19", "Deuteronomy 4:19"),
  "laws": ["2D.3", "2D.14", "2D.8", "10A.2", "2G.1", "2J.8"],
  "topics": ["idolatry", "secret-place", "exposed", "eyes-of-the-lord"],
  "themes": ["idolatry", "leadership", "corporate-judgment"],
 },
 {
  "slug": "the-shepherds-of-israel",
  "name": "The shepherds of Israel",
  "era": "Divided Kingdom",
  "charge": "Feeding themselves and not the flock; scattering the sheep",
  "verdict": "curse",
  "summary": "Ezekiel 34 arraigns the rulers and pastors of Israel as shepherds who ate the fat and clothed themselves with the wool, but did not strengthen the diseased, heal the sick, bind up the broken, bring back the driven away, or seek the lost. The flock was scattered on every hill and became meat to the beasts.",
  "offense": "With force and with cruelty have ye ruled them. Jeremiah brings the same charge: ye have scattered my flock and driven them away and not visited them. Zechariah's idol shepherd leaves the flock and is cursed in his arm and his eye.",
  "judgment": "Behold, I am against the shepherds; I will require my flock at their hand and cause them to cease from feeding the flock. Then the Lord promises to search his sheep himself and set up one shepherd, his servant David. Christ claimed the office: I am the good shepherd.",
  "refs": R("Ezekiel 34:1-10", "Ezekiel 34:11-16", "Ezekiel 34:23", "Jeremiah 23:1-2", "Zechariah 11:15-17", "John 10:11-13"),
  "laws": ["20F.9", "20F.3", "20A.13", "8A.9", "8A.17", "15B.6"],
  "topics": ["lost-sheep", "false-prophets", "poor"],
  "themes": ["leadership", "priesthood", "oppression"],
 },
 {
  "slug": "the-priests-of-malachi",
  "name": "The priests who despised the Name",
  "era": "Exile and Return",
  "charge": "Offering polluted bread and blemished beasts; being partial in the law",
  "verdict": "curse",
  "summary": "After the return, the priests offered the blind, the lame, and the sick on the altar and said the table of the Lord was contemptible and its service a weariness. Offer it now unto thy governor, Malachi says; will he be pleased with thee? They also departed out of the way and caused many to stumble at the law.",
  "offense": "Leviticus forbids any offering with a blemish; they kept the best for themselves and the defective for God, while men of other nations feared his name more than they did. Priests are to keep knowledge and teach the law; these corrupted the covenant of Levi.",
  "judgment": "I will curse your blessings; yea, I have cursed them already. I will spread dung upon your faces, even the dung of your solemn feasts. Therefore have I also made you contemptible and base before all the people, according as ye have been partial in the law.",
  "refs": R("Malachi 1:6-8", "Malachi 1:12-14", "Malachi 2:1-3", "Malachi 2:7-9", "Leviticus 22:20-22", "Deuteronomy 15:21"),
  "laws": ["20B.2", "20A.7", "20A.9", "4F.3", "20E.3", "20F.4"],
  "topics": ["honour", "the-name", "respect-of-persons", "kings-and-priests"],
  "themes": ["priesthood", "irreverence", "partiality"],
 },
 {
  "slug": "robbing-god",
  "name": "Judah robbing God in tithes and offerings",
  "era": "Exile and Return",
  "charge": "Withholding the tithe from the storehouse",
  "verdict": "curse",
  "summary": "Will a man rob God? Yet ye have robbed me. But ye say, wherein? In tithes and offerings. The returned community had left the Levites unsupported so that they fled to their fields, and the house of God was forsaken while every man ran to his own house.",
  "offense": "The tenth of the land's increase belongs to the Lord; withholding it is theft from him. Haggai had already named the consequence: ye have sown much and bring in little, because of mine house that is waste. Nehemiah found the same neglect on his return and contended with the rulers over it.",
  "judgment": "Ye are cursed with a curse: for ye have robbed me, even this whole nation. The remedy offered in the same breath: bring ye all the tithes into the storehouse, and prove me now herewith, if I will not open you the windows of heaven.",
  "refs": R("Malachi 3:7-12", "Nehemiah 13:10-12", "Haggai 1:4-11", "Leviticus 27:30", "Numbers 18:21", "Deuteronomy 14:22"),
  "laws": ["20E.4", "20E.1", "20E.3", "20E.13", "20E.6"],
  "topics": ["tithes-for-levi", "storehouse", "windows-of-heaven", "tithes-are-not-money"],
  "themes": ["theft", "tithes", "curse"],
 },
]
